### ISSUE TITLE
base64头颅无法使用

### ISSUE THREAD

**Issue by Score2** [InsinuateProjects/TrMenu#1]
```
[20:20:44 WARN]: [TrMenu] Plugin TrMenu v3.0-PRE-10 generated an exception while executing task 2519
java.lang.ClassCastException: class com.google.gson.JsonNull cannot be cast to class com.google.gson.JsonObject (com.google.gson.JsonNull and com.google.gson.JsonObject are in unnamed module of loader 'app')
        at me.arasple.mc.trmenu.util.bukkit.Heads$playerTexture$2.invoke(Heads.kt:83) ~[TrMenu-3.0-PRE-10.jar:?]
        at me.arasple.mc.trmenu.util.bukkit.Heads$playerTexture$2.invoke(Heads.kt:82) ~[TrMenu-3.0-PRE-10.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$6.run(BukkitExecutor.kt:89) ~[TrMenu-3.0-PRE-10.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-151]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-151]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Score2** [comment]
已尝试修复，但需要大规模测试

**Comment by Score2** [comment]
等待 TabooLib 6.0.0-pre29 更新.

**Comment by Score2** [comment]
Fixed
