### ISSUE TITLE
[问题]: TrMenu 于 Paper 1.8.x 启动时出现报错

### ISSUE THREAD

**Issue by TONY-All** [InsinuateProjects/TrMenu#102]
### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

无法正常使用命令..手动输入
```
  | Server OS: MacOS 12.0.1
  | Server software: git-PaperSpigot-"4c7641d" (MC: 1.8.8)
  | Java version: Oracle JDK 8u231

  | TabooLib: 
  | TrMenu: v3.0-RC3
Installed Plugins:
Plugins (12): ViaVersion, Vault, ViaBackwards, PlaceholderAPI, Multiverse-Core, ProtocolLib, TrMenu, ViaRewind, NoPlugins, GemsEconomy, Multiverse-Patches, DeluxeHub
(TrMenu 已 Disabled)
```

### 🔍 详细的描述

```
1. 使用任意1.8服务端
2. 安装TrMenu插件
3. 启动服务端
```

### 🗄 服务端日志

```log
[13:17:35 ERROR]: Error occurred while enabling TrMenu v3.0-RC-3 (Is it up to date?)
java.lang.AbstractMethodError: org.sqlite.Conn.isValid(I)Z
	at com.zaxxer.hikari_4_0_3.pool.PoolBase.checkValidationSupport(PoolBase.java:464) ~[?:?]
	at com.zaxxer.hikari_4_0_3.pool.PoolBase.checkDriverSupport(PoolBase.java:447) ~[?:?]
	at com.zaxxer.hikari_4_0_3.pool.PoolBase.setupConnection(PoolBase.java:416) ~[?:?]
	at com.zaxxer.hikari_4_0_3.pool.PoolBase.newConnection(PoolBase.java:369) ~[?:?]
	at com.zaxxer.hikari_4_0_3.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[?:?]
	at com.zaxxer.hikari_4_0_3.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[?:?]
	at com.zaxxer.hikari_4_0_3.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[?:?]
	at com.zaxxer.hikari_4_0_3.pool.HikariPool.<init>(HikariPool.java:115) ~[?:?]
	at com.zaxxer.hikari_4_0_3.HikariDataSource.<init>(HikariDataSource.java:81) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.module.database.Database.createDataSource(Database.kt:18) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.module.database.Database.createDataSource$default(Database.kt:17) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.module.database.Host.createDataSource(Host.kt:18) ~[?:?]
	at me.arasple.mc.trmenu.module.internal.database.DatabaseLocal.<init>(DatabaseLocal.kt:48) ~[?:?]
	at me.arasple.mc.trmenu.module.internal.data.Metadata$database$2.invoke(Metadata.kt:42) ~[?:?]
	at me.arasple.mc.trmenu.module.internal.data.Metadata$database$2.invoke(Metadata.kt:40) ~[?:?]
	at kotlin1521.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
	at me.arasple.mc.trmenu.module.internal.data.Metadata.getDatabase(Metadata.kt:40) ~[?:?]
	at me.arasple.mc.trmenu.TrMenu.onEnable(TrMenu.kt:45) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:61) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
```

### ⚙ 配置文件

```

```

**Comment by TONY-All** [comment]
我是憨批
