### ISSUE TITLE
[Bug]: /trmenu open命令无法打开制定页数

### ISSUE THREAD

**Issue by kankanbird** [InsinuateProjects/TrMenu#103]
### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

[```
TrMenu Dump Information (Date: xxxx-xx-xx xx:xx:xx)

  | Server OS: Ubuntu 18
  | Server software: Purpur 1414
  | Java version: 8-hotspot

  | TabooLib: 5.7.2
  | TrMenu: RC-3
Installed Plugins:
  · Fresh server

### 🔍 Detailed description

1. 无法使用/trmenu open <菜单>:[页码] 这条命令打开菜单指定页码
2. 动作类型  open: <菜单>:[页码] 无法打开指定菜单页

### 🗄 Server log

```
[13:13:26] [Server thread/WARN]: [TrMenu] Task #1927 for TrMenu v3.0-RC-3 generated an exception
java.lang.ArrayIndexOutOfBoundsException: 2
	at me.arasple.mc.trmenu.module.display.layout.MenuLayout.get-impl(MenuLayout.kt:25) ~[?:?]
	at me.arasple.mc.trmenu.module.display.MenuSession.layout(MenuSession.kt:93) ~[?:?]
	at me.arasple.mc.trmenu.module.display.Menu.page(Menu.kt:101) ~[?:?]
	at me.arasple.mc.trmenu.module.display.Menu.open(Menu.kt:58) ~[?:?]
	at me.arasple.mc.trmenu.api.action.impl.ActionOpen.onExecute(ActionOpen.kt:25) ~[?:?]
	at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1$1.invoke(AbstractAction.kt:41) ~[?:?]
	at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1$1.invoke(AbstractAction.kt:41) ~[?:?]
	at me.arasple.mc.trmenu.api.action.base.ActionOption.evalPlayers(ActionOption.kt:35) ~[?:?]
	at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1.invoke(AbstractAction.kt:41) ~[?:?]
	at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1.invoke(AbstractAction.kt:41) ~[?:?]
	at me.arasple.mc.trmenu.api.action.base.AbstractAction.run(AbstractAction.kt:43) ~[?:?]
	at me.arasple.mc.trmenu.api.action.Actions$runAction$2$1.invoke(Actions.kt:89) ~[?:?]
	at me.arasple.mc.trmenu.api.action.Actions$runAction$2$1.invoke(Actions.kt:89) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$5.run(BukkitExecutor.kt:79) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[Paper-1.12.2-b1596.jar:git-Paper-1596]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[Paper-1.12.2-b1596.jar:git-Paper-1596]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[Paper-1.12.2-b1596.jar:git-Paper-1596]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper-1.12.2-b1596.jar:git-Paper-1596]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Paper-1.12.2-b1596.jar:git-Paper-1596]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Paper-1.12.2-b1596.jar:git-Paper-1596]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]

```

### ⚙ Configurations

```

```

**Comment by Score2** [comment]
请放出菜单配置
