### ISSUE TITLE
[问题]: 启动服务器时抛 NPE

### ISSUE THREAD

**Issue by Taskeren** [InsinuateProjects/TrMenu#107]
### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

因为异常被 disable 了

服务端：Paper-1.18-39
插件：3.0-RC-4

### 🔍 详细的描述

```
1. 从很久以前的旧版更新到 3.0-RC-4 抛出错误 1
2. 删除 settings.yml 并重启后抛出错误 2
```

### 🗄 服务端日志

```
[19:35:50 ERROR]: Error occurred while enabling TrMenu v3.0-RC-4 (Is it up to date?)
>java.lang.NullPointerException: null
at me.arasple.mc.trmenu.module.internal.data.Metadata$database$2.invoke(Metadata.kt:41) ~[TrMenu-3.0-RC-4.jar:?]
at me.arasple.mc.trmenu.module.internal.data.Metadata$database$2.invoke(Metadata.kt:40) ~[TrMenu-3.0-RC-4.jar:?]
at kotlin160.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[TrMenu-3.0-RC-4.jar:?]
at me.arasple.mc.trmenu.module.internal.data.Metadata.getDatabase(Metadata.kt:40) ~[TrMenu-3.0-RC-4.jar:?]
at me.arasple.mc.trmenu.TrMenu.onEnable(TrMenu.kt:45) ~[TrMenu-3.0-RC-4.jar:?]
at me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:61) ~[TrMenu-3.0-RC-4.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.18.jar:git-Paper-39]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-39]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:35:50 INFO]: [TrMenu] Disabling TrMenu v3.0-RC-4
```

```
[19:43:45 ERROR]: Error occurred while enabling TrMenu v3.0-RC-4 (Is it up to date?)
>java.lang.NullPointerException: null
at me.arasple.mc.trmenu.taboolib.module.nms.MinecraftVersion$mapping$2.invoke(MinecraftVersion.kt:71) ~[TrMenu-3.0-RC-4.jar:?]
at me.arasple.mc.trmenu.taboolib.module.nms.MinecraftVersion$mapping$2.invoke(MinecraftVersion.kt:70) ~[TrMenu-3.0-RC-4.jar:?]
at kotlin160.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[TrMenu-3.0-RC-4.jar:?]
at me.arasple.mc.trmenu.taboolib.module.nms.MinecraftVersion.getMapping(MinecraftVersion.kt:70) ~[TrMenu-3.0-RC-4.jar:?]
at me.arasple.mc.trmenu.taboolib.module.nms.RefRemapper.field(RefRemapper.kt:16) ~[TrMenu-3.0-RC-4.jar:?]
at me.arasple.mc.trmenu.taboolib.common.reflect.ReflexClass.findField(ReflexClass.kt:52) ~[TrMenu-3.0-RC-4.jar:?]
at me.arasple.mc.trmenu.taboolib.common.reflect.Reflex.set(Reflex.kt:69) ~[TrMenu-3.0-RC-4.jar:?]
at me.arasple.mc.trmenu.taboolib.common.reflect.Reflex.write(Reflex.kt:36) ~[TrMenu-3.0-RC-4.jar:?]
at me.arasple.mc.trmenu.taboolib.common.reflect.Reflex$Companion.setProperty(Reflex.kt:142) ~[TrMenu-3.0-RC-4.jar:?]
at me.arasple.mc.trmenu.taboolib.common.reflect.Reflex$Companion.setProperty$default(Reflex.kt:138) ~[TrMenu-3.0-RC-4.jar:?]
at me.arasple.mc.trmenu.taboolib.platform.BukkitCommand$registerCommand$1.invoke(BukkitCommand.kt:76) ~[TrMenu-3.0-RC-4.jar:?]
at me.arasple.mc.trmenu.taboolib.platform.BukkitCommand$registerCommand$1.invoke(BukkitCommand.kt:66) ~[TrMenu-3.0-RC-4.jar:?]
at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$1.<init>(BukkitExecutor.kt:39) ~[TrMenu-3.0-RC-4.jar:?]
at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor.submit(BukkitExecutor.kt:36) ~[TrMenu-3.0-RC-4.jar:?]
at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor.start(BukkitExecutor.kt:28) ~[TrMenu-3.0-RC-4.jar:?]
at me.arasple.mc.trmenu.taboolib.common.platform.function.ExecutorKt.startExecutor(Executor.kt:11) ~[TrMenu-3.0-RC-4.jar:?]
at me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:64) ~[TrMenu-3.0-RC-4.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.18.jar:git-Paper-39]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-39]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:43:45 INFO]: [TrMenu] Disabling TrMenu v3.0-RC-4
```

### ⚙ 配置文件

```

Loader:
  Menu-Files:
    - 'plugins/CustomMenusFolder'

Menu:
  Settings:
    Bound-Item-Interval: 2000
  Icon:
    Inherit: false
    Item:
      Default-Name-Color: "&7"
      Default-Lore-Color: "&7"
      Pre-Color: false

Action:
  Inputer:
    Cancel-Words:
      - 'cancel|quit|end'
      - 'q'

Shortcuts:
  Offhand: [ ]
  Sneaking-Offhand:
    - condition: 'perm *trmenu.shortcut'
      execute: 'open: Example'
      deny: 'return'
  Right-Click-Player: 'open: Profile'
  Sneaking-Right-Click-Player: [ ]
  PlayerInventory-Border-Left: [ ]
  PlayerInventory-Border-Right: [ ]
  PlayerInventory-Border-Middle: [ ]

RegisterCommands:
  openMenus:
    aliases: [ ]
    permission: null
    execute:
      - 'tell: &7Argument `example` Required!'
    arguments:
      example: 'open: example'

```

**Comment by Score2** [comment]
等待@Bkm016 合并https://github.com/TabooLib/TabooLib/pull/217
