### ISSUE TITLE
[问题]: 1.18中菜单的papi加载会导致异常

### ISSUE THREAD

**Issue by 4o4E** [InsinuateProjects/TrMenu#110]
### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2021-12-12 20:55:35)

| Server OS: Linux amd64 3.10.0-1160.el7.x86_64
| Server software: git-Paper-66 (MC: 1.18) (1.18-R0.1-SNAPSHOT)
| Java version: 17.0.1

| TrMenu: 3.0
Installed Plugins: 
· AnimatedScoreboard - 0.2.5 (0 KB)
· AuthMe - 5.6.0-SNAPSHOT-b2509 (0 KB)
· Boom - 1.3.3 (0 KB)
· CMI - 9.1.0.2 (0 KB)
· CMILib - 1.1.0.2 (0 KB)
· CalendarEvents - 2.3.0 (0 KB)
· Citizens - 2.0.29-SNAPSHOT (build 2419) (0 KB)
· CoreProtect - 20.1 (0 KB)
· EWhiteList - 1.0.0 (0 KB)
· FastLeafDecay - 1.0 (0 KB)
· GCore - 8.33.0 (0 KB)
· IsThisASlimeChunk - 1.0.0 (0 KB)
· LWC - 2.2.8-dev-52b334e (0 KB)
· LaggRemover - 2.0.6 (0 KB)
· LuckPerms - 5.3.85 (0 KB)
· MMOItems - 6.6.4 (0 KB)
· MiniMOTD - 2.0.5 (0 KB)
· Multiverse-Core - 4.3.2-SNAPSHOT-b867 (0 KB)
· MythicLib - 1.2 (0 KB)
· PlaceholderAPI - 2.10.10 (0 KB)
· PlayerTitle - 2.9.7 (0 KB)
· PluginManager - 2.7 (0 KB)
· ProtocolLib - 4.8.0-SNAPSHOT-b538 (0 KB)
· QuestCreator - 6.33.1 (0 KB)
· QuickShop - 5.0.0.17-SNAPSHOT (0 KB)
· Residence - 5.0.1.0 (0 KB)
· SkinsRestorer - 14.1.10 (0 KB)
· TAB - 3.0.0 (0 KB)
· Tell - 1.0 (0 KB)
· TempFly - 3.1.0 (0 KB)
· TrChat - 1.90-R5 (0 KB)
· TrMenu - 3.0 (0 KB)
· UTools - 1.0.1 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· VeinMiner - 1.17.9 (0 KB)
· ViaVersion - 4.1.2-SNAPSHOT (0 KB)
· WorldEdit - 7.2.8+6008-1246d61 (0 KB)
· XConomy - 2.11.9 (0 KB)
```

### 🔍 详细的描述

```
1. 菜单的图标中使用 `%server_total_living_entities%` 和 `%server_total_entities%` 时后台报错
```

### 🗄 服务端日志

```
[21:07:13 FATAL]: Thread TConfigWatcherService-1 failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.18.jar:git-Paper-66]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2304) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftWorld.getNMSEntities(CraftWorld.java:990) ~[paper-1.18.jar:git-Paper-66]
        at org.bukkit.craftbukkit.v1_18_R1.CraftRegionAccessor.getEntitiesByClasses(CraftRegionAccessor.java:438) ~[paper-1.18.jar:git-Paper-66]
        at com.extendedclip.papi.expansion.server.ServerExpansion.onRequest(ServerExpansion.java:184) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:160) ~[PlaceholderAPI-2.10.10.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70) ~[PlaceholderAPI-2.10.10.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98) ~[PlaceholderAPI-2.10.10.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.compat.PlaceholderExpansionKt.replacePlaceholder(PlaceholderExpansion.kt:15) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.module.display.MenuSession.parse(MenuSession.kt:111) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.module.display.MenuSession.parse$default(MenuSession.kt:106) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.module.display.item.Lore.parse(Lore.kt:32) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.module.display.item.Item.lore(Item.kt:28) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.module.display.item.Item.build$default(Item.kt:38) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.module.display.item.Item.get(Item.kt:32) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon.settingItem(Icon.kt:81) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon.filter(Icon.kt:157) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon.onRefresh(Icon.kt:86) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.module.display.Menu.loadIcon(Menu.kt:152) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.module.display.Menu.open(Menu.kt:87) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.module.display.Menu.open$default(Menu.kt:45) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.module.conf.Loader$listen$1$1.invoke(Loader.kt:140) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.module.conf.Loader$listen$1$1.invoke(Loader.kt:139) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.module.display.Menu$forSessions$2.invoke(Menu.kt:188) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.module.display.Menu$forSessions$2.invoke(Menu.kt:188) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.module.display.Menu.forViewers(Menu.kt:233) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.module.display.Menu.forSessions(Menu.kt:188) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.module.conf.Loader$listen$1.invoke(Loader.kt:139) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.module.conf.Loader$listen$1.invoke(Loader.kt:111) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.util.file.FileListener.listener$lambda-0(FileListener.kt:20) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.taboolib.common5.FileWatcher.lambda$addSimpleListener$2(FileWatcher.java:66) ~[TrMenu-3.0.jar:?]
        at me.arasple.mc.trmenu.taboolib.common5.FileWatcher.lambda$null$0(FileWatcher.java:47) ~[TrMenu-3.0.jar:?]
        at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common5.FileWatcher.lambda$new$1(FileWatcher.java:42) ~[TrMenu-3.0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:07:13 WARN]: java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
[21:07:13 WARN]:        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16)
[21:07:13 WARN]:        at net.minecraft.server.level.WorldServer.I(WorldServer.java:2304)
[21:07:13 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftWorld.getNMSEntities(CraftWorld.java:990)
[21:07:13 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftRegionAccessor.getEntitiesByClasses(CraftRegionAccessor.java:438)
[21:07:13 WARN]:        at com.extendedclip.papi.expansion.server.ServerExpansion.onRequest(ServerExpansion.java:184)
[21:07:13 WARN]:        at PlaceholderAPI-2.10.10.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:160)
[21:07:13 WARN]:        at PlaceholderAPI-2.10.10.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70)
[21:07:13 WARN]:        at PlaceholderAPI-2.10.10.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.taboolib.platform.compat.PlaceholderExpansionKt.replacePlaceholder(PlaceholderExpansion.kt:15)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.module.display.MenuSession.parse(MenuSession.kt:111)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.module.display.MenuSession.parse$default(MenuSession.kt:106)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.module.display.item.Lore.parse(Lore.kt:32)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.module.display.item.Item.lore(Item.kt:28)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.module.display.item.Item.build$default(Item.kt:38)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.module.display.item.Item.get(Item.kt:32)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.module.display.icon.Icon.settingItem(Icon.kt:81)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.module.display.icon.Icon.filter(Icon.kt:157)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.module.display.icon.Icon.onRefresh(Icon.kt:86)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.module.display.Menu.loadIcon(Menu.kt:152)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.module.display.Menu.open(Menu.kt:87)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.module.display.Menu.open$default(Menu.kt:45)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.module.conf.Loader$listen$1$1.invoke(Loader.kt:140)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.module.conf.Loader$listen$1$1.invoke(Loader.kt:139)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.module.display.Menu$forSessions$2.invoke(Menu.kt:188)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.module.display.Menu$forSessions$2.invoke(Menu.kt:188)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.module.display.Menu.forViewers(Menu.kt:233)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.module.display.Menu.forSessions(Menu.kt:188)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.module.conf.Loader$listen$1.invoke(Loader.kt:139)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.module.conf.Loader$listen$1.invoke(Loader.kt:111)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.util.file.FileListener.listener$lambda-0(FileListener.kt:20)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.taboolib.common5.FileWatcher.lambda$addSimpleListener$2(FileWatcher.java:66)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.taboolib.common5.FileWatcher.lambda$null$0(FileWatcher.java:47)
[21:07:13 WARN]:        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
[21:07:13 WARN]:        at TrMenu-3.0.jar//me.arasple.mc.trmenu.taboolib.common5.FileWatcher.lambda$new$1(FileWatcher.java:42)
[21:07:13 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[21:07:13 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[21:07:13 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[21:07:13 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[21:07:13 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:07:13 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### ⚙ 配置文件

```yaml
  服务器信息:
    update: 10
    display:
      mats: "head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGQxOWM2ODQ2MTY2NmFhY2Q3NjI4ZTM0YTFlMmFkMzlmZTRmMmJkZTMyZTIzMTk2M2VmM2IzNTUzMyJ9fX0="
      name: "&f服务器信息"
      lore:
        - "&8▪ &f内存: &a%server_ram_used%&7/&2%server_ram_total% MB &8(%math_2_({server_ram_used}/{server_ram_total})*100%%&8)"
        - "&8▪ &f在线/历史人数: &e%server_online% &f/ &a%server_unique_joins%"
        - "&8▪ &f活跃/实体数: &e%server_total_living_entities% &f/ &a%server_total_entities%"
        - "&8▪ &fTPS: &a%server_tps_1%"
        - "&8▪ &f运行时间: &e%server_uptime%"
```

**Comment by 157946a** [comment]
把"&8▪ &f活跃/实体数: &e%server_total_living_entities% &f/ &a%server_total_entities%"删除看看

**Comment by 4o4E** [comment]
> 把"&8▪ &f活跃/实体数: &e%server_total_living_entities% &f/ &a%server_total_entities%"删除看看

我知道问题是这个，并且已经删除了，主要是这个papi在以前的版本中是可以正常使用的，所以开了个issue

**Comment by 157946a** [comment]
可问题来了,trmenu只是解析papi变量,并不是直接将变量设置为一个表达式,报错指向是主线程检查调用区块实体失败,你试试在别处使用,比如chat或者hd

**Comment by 157946a** [comment]
{ke: papi *%server_total_living_entities%}暂时先使用kether语法解析变量,目前这个方法是可行的,维护者已经在处理这个问题了

**Comment by 157946a** [comment]
使用最新查看是否修复

**Comment by 4o4E** [comment]
> 使用最新查看是否修复

3.1.10已修复
