### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 849025143** [InsinuateProjects/TrMenu#111]
### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

插件裂开了，无法执行

### 🔍 Detailed description

没有,因为我只是拖到plugins然后启动

### 🗄 Server log

[18:27:37] [Server thread/ERROR]: Runtime environment setup failed, please feedback! initializing TrMenu v3.01 (Is it up to date?)
java.lang.RuntimeException: Runtime environment setup failed, please feedback!
        at me.arasple.mc.trmenu.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:140) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:86) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.onLoad(BukkitPlugin.java:47) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:364) [CraftServer.class:git-CatServer-1.12.2-5d66f2e]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:340) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:634) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]

### ⚙ Configurations

 没有任何配置文件生成

**Comment by 157946a** [comment]
运行环境设置失败,你尝试更新核心看看,如果是最新的尝试下载前几个版本试试

**Comment by 157946a** [comment]
更新并删除libs重新下载
