### ISSUE TITLE
[Bug]: Error at starting the server

### ISSUE THREAD

**Issue by Adriianh** [InsinuateProjects/TrMenu#112]
### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

TrMenu Dump Information (Date: 2021-12-16 14:53:09)

| Server OS: Windows 10 amd64 10.0
| Server software: git-Purpur-1443 (MC: 1.18.1) (1.18.1-R0.1-SNAPSHOT)
| Java version: 17.0.1

| TrMenu: 3.01
Installed Plugins: 
· CMILib - 1.1.0.2 (0 KB)
· CharacterDialogue - 0.7.1 (0 KB)
· Citizens - 2.0.29-SNAPSHOT (build 2420) (0 KB)
· HolographicDisplays - 3.0.0-SNAPSHOT (0 KB)
· Jobs - 5.0.1.0 (0 KB)
· PlaceholderAPI - 2.10.10 (0 KB)
· TrMenu - 3.01 (0 KB)
· Vault - 1.7.3-b131 (0 KB)

### 🔍 Detailed description

```
1. When i start the server (with the latest build available), i get this error.
2. Also, none of the sample menus work. When opening one, it gives an error.
```

### 🗄 Server log

```
[14:51:44 INFO]: [TrMenu] Enabling TrMenu v3.01
[14:51:44 INFO]: [PlaceholderAPI] Successfully registered expansion: trmenu
[14:51:46 WARN]: java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
[14:51:46 WARN]:        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
[14:51:46 WARN]:        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
[14:51:46 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.util.concurrent.TaskConcurrent.start$lambda-3(TaskConcurrent.kt:30)
[14:51:46 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[14:51:46 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[14:51:46 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[14:51:46 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[14:51:46 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[14:51:46 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[14:51:46 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[14:51:46 WARN]: Caused by: java.lang.ExceptionInInitializerError
[14:51:46 WARN]:        at TrMenu-3.01.jar//org.openjdk.nashorn.internal.runtime.Context.compile(Context.java:1509)
[14:51:46 WARN]:        at TrMenu-3.01.jar//org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:783)
[14:51:46 WARN]:        at TrMenu-3.01.jar//org.openjdk.nashorn.api.scripting.NashornScriptEngine.asCompiledScript(NashornScriptEngine.java:486)
[14:51:46 WARN]:        at TrMenu-3.01.jar//org.openjdk.nashorn.api.scripting.NashornScriptEngine.compile(NashornScriptEngine.java:178)
[14:51:46 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.taboolib.common5.NashornCompilerKt.compileJS(NashornCompiler.kt:27)
[14:51:46 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.module.internal.script.js.JavaScriptAgent.preCompile$lambda-2(JavaScriptAgent.kt:41)
[14:51:46 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
[14:51:46 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.module.internal.script.js.JavaScriptAgent.preCompile(JavaScriptAgent.kt:40)
[14:51:46 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.api.action.impl.ActionJavaScript.<init>(ActionJavaScript.kt:15)
[14:51:46 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.api.action.impl.ActionJavaScript$Companion$parser$1.invoke(ActionJavaScript.kt:27)
[14:51:46 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.api.action.impl.ActionJavaScript$Companion$parser$1.invoke(ActionJavaScript.kt:26)
[14:51:46 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.api.action.Actions.readAction(Actions.kt:132)
[14:51:46 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.api.action.pack.Reaction$Companion.of(Reaction.kt:22)
[14:51:46 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.api.action.pack.Reactions$Companion.ofReaction(Reactions.kt:21)
[14:51:46 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.module.conf.MenuSerializer$loadIconProperty$1.invoke(MenuSerializer.kt:242)
[14:51:46 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.module.conf.MenuSerializer$loadIconProperty$1.invoke(MenuSerializer.kt:226)
[14:51:46 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.module.conf.MenuSerializer.serializeIcons-YkZ8m0M(MenuSerializer.kt:190)
[14:51:46 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.module.conf.MenuSerializer.serializeMenu(MenuSerializer.kt:77)
[14:51:46 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.module.conf.Loader$loadMenus$2.invoke(Loader.kt:72)
[14:51:46 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.module.conf.Loader$loadMenus$2.invoke(Loader.kt:69)
[14:51:46 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.util.concurrent.TaskConcurrent.start$lambda-3$lambda-1$lambda-0(TaskConcurrent.kt:26)
[14:51:46 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[14:51:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[14:51:46 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[14:51:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[14:51:46 WARN]: Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: no such method: sun.misc.Unsafe.defineAnonymousClass(Class,byte[],Object[])Class/invokeVirtual
[14:51:46 WARN]:        at TrMenu-3.01.jar//org.openjdk.nashorn.internal.runtime.Context$AnonymousContextCodeInstaller.lambda$getDefineAnonymousClass$0(Context.java:335)
[14:51:46 WARN]:        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
[14:51:46 WARN]:        at TrMenu-3.01.jar//org.openjdk.nashorn.internal.runtime.Context$AnonymousContextCodeInstaller.getDefineAnonymousClass(Context.java:327)
[14:51:46 WARN]:        at TrMenu-3.01.jar//org.openjdk.nashorn.internal.runtime.Context$AnonymousContextCodeInstaller.<clinit>(Context.java:317)
[14:51:46 WARN]:        ... 25 more
[14:51:46 WARN]: Caused by: java.lang.NoSuchMethodException: no such method: sun.misc.Unsafe.defineAnonymousClass(Class,byte[],Object[])Class/invokeVirtual
[14:51:46 WARN]:        at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:976)
[14:51:46 WARN]:        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1117)
[14:51:46 WARN]:        at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3649)
[14:51:46 WARN]:        at java.base/java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2680)
[14:51:46 WARN]:        at TrMenu-3.01.jar//org.openjdk.nashorn.internal.runtime.Context$AnonymousContextCodeInstaller.lambda$getDefineAnonymousClass$0(Context.java:329)
[14:51:46 WARN]:        ... 28 more
[14:51:46 WARN]: Caused by: java.lang.NoSuchMethodError: 'java.lang.Class sun.misc.Unsafe.defineAnonymousClass(java.lang.Class, byte[], java.lang.Object[])'
[14:51:46 WARN]:        at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
[14:51:46 WARN]:        at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1085)
[14:51:46 WARN]:        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114)
[14:51:46 WARN]:        ... 31 more
[14:51:50 INFO]: [TrMenu] FINE | 43 menus were loaded (5721 ms)
[14:51:50 INFO]: [com.zaxxer.hikari_4_0_3.HikariDataSource] HikariPool-1 - Starting...
[14:51:50 INFO]: [com.zaxxer.hikari_4_0_3.HikariDataSource] HikariPool-1 - Start completed.
[14:51:50 INFO]: [TrMenu] INFO | Plugin has been enabled. Currently running version 3.01.
[14:51:50 INFO]: [TrMenu] HOOK | Soft-Dependency Vault is hooked.
```

### ⚙ Configurations

```
- Default config.
```

**Comment by Score2** [comment]
https://github.com/TabooLib/TabooLib/issues/219

**Comment by MrTwoc** [comment]
yes,I'm in this situation too

**Comment by 157946a** [comment]
You can solve it by deleting all the content related to js in your configuration, or you can download a js engine. I don't know which js engine plugins are available in spigot. Someone in China develops them.

**Comment by Adriianh** [comment]
> You can solve it by deleting all the content related to js in your configuration, or you can download a js engine. I don't know which js engine plugins are available in spigot. Someone in China develops them.

Thanks for replying but it doesn't work. I mean using a JS Engine. 
And i won't delete my settings, I need them that's why i reported the error.....

**Comment by 157946a** [comment]
Really, then I have time to look at spigotmc to see if there are plug-ins available, by the way, why do you need js?

**Comment by 157946a** [comment]
https://www.spigotmc.org/resources/jsengine.92709/
Try this and see if it works
