### ISSUE TITLE
1.12.2的猫端无法使用

### ISSUE THREAD

**Issue by Baikele** [InsinuateProjects/TrMenu#12]
[01:04:41] [Craft Scheduler Thread - 45/WARN] [me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin]: [TrMenu] Plugin TrMenu v3.0-PRE-14 generated an exception while executing task 124
java.lang.ClassFormatError: Failed to remap class me.arasple.mc.trmenu.taboolib.module.ui.receptacle.NMSImpl
	at catserver.server.remapper.target.CatClassLoader.remappedFindClass(CatClassLoader.java:68) ~[CatClassLoader.class:git-CatServer-1.12.2-26208f0]
	at catserver.server.remapper.target.CatClassLoader.defineClassRemap(CatClassLoader.java:53) ~[CatClassLoader.class:git-CatServer-1.12.2-26208f0]
	at me.arasple.mc.trmenu.taboolib.module.nms.AsmClassLoader.createNewClass(AsmClassLoader.kt:16) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.module.nms.AsmClassTransfer.run(AsmClassTransfer.kt:23) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.module.nms.MinecraftServerUtilKt.nmsProxy$lambda-1(MinecraftServerUtil.kt:27) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source) ~[?:1.8.0_301]
	at me.arasple.mc.trmenu.taboolib.module.nms.MinecraftServerUtilKt.nmsProxy(MinecraftServerUtil.kt:25) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.module.ui.receptacle.PacketInventory$DefaultImpls.send(PacketInventory.kt:16) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.module.ui.receptacle.PacketWindowSetSlot.send(PacketWindowSetSlot.kt:21) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.module.ui.receptacle.Receptacle.setItem(Receptacle.kt:59) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.module.ui.receptacle.Receptacle.setItem(Receptacle.kt:53) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.module.ui.receptacle.Receptacle.setItem$default(Receptacle.kt:52) ~[?:?]
	at me.arasple.mc.trmenu.module.display.icon.Icon.settingItem(Icon.kt:75) ~[?:?]
	at me.arasple.mc.trmenu.module.display.icon.Icon.onUpdate(Icon.kt:67) ~[?:?]
	at me.arasple.mc.trmenu.module.display.icon.Icon$startup$1$1.invoke(Icon.kt:26) ~[?:?]
	at me.arasple.mc.trmenu.module.display.icon.Icon$startup$1$1.invoke(Icon.kt:25) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$2.run(BukkitExecutor.kt:51) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-26208f0]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-26208f0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_301]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]

**Comment by Score2** [comment]
TabooLib 6 暂时不支持 CatServer 等 forge 服务端, 请等待适配.

**Comment by Score2** [comment]
尝试使用 pre23
