### ISSUE TITLE
[Bug]: mongo-java-driver-3.12.7.pom not found

### ISSUE THREAD

**Issue by Teyir** [InsinuateProjects/TrMenu#122]
### 📚 Have you checked the Wiki

- [x] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

```
TrMenu Dump Information (Date: 2022-01-02 15:35:05)

| Server OS: Linux amd64 4.19.0-18-amd64
| Server software: git-Pufferfish-27 (MC: 1.18.1) (1.18.1-R0.1-SNAPSHOT)
| Java version: 17.0.1

| TrMenu: 3.01
Installed Plugins: 
· BungeeGuard - 1.2-SNAPSHOT (0 KB)
· BuycraftX - 12.0.8 (0 KB)
· CMI - 9.1.0.4 (0 KB)
· CMILib - 1.1.0.4 (0 KB)
· Citizens - 2.0.29-SNAPSHOT (build 2430) (0 KB)
· FeatherBoard - 5.1.0 (0 KB)
· HeadDatabase - 4.15.1 (0 KB)
· LuckPerms - 5.3.86 (0 KB)
· Multiverse-Core - 4.3.1-SNAPSHOT-b860 (0 KB)
· PlaceholderAPI - 2.10.10-DEV-132 (0 KB)
· Plan - 5.4 build 1516 (0 KB)
· PlayerPoints - 3.1.0 (0 KB)
· Quests - 4.1.3-b286 (0 KB)
· QuestsGUI - 0.37 (0 KB)
· SuperiorSkyblock2 - 1.8.3.426 (0 KB)
· TAB - 3.0.2-pre1 (0 KB)
· TrMenu - 3.01 (0 KB)
· Vault - 1.7.3-b${env.TRAVIS_BUILD_NUMBER} (0 KB)
· WorldEdit - 7.2.8+6008-1246d61 (0 KB)
· WorldGuard - 7.0.6+1cff55f (0 KB)
· spark - 1.6.4 (0 KB)

```

### 🔍 Detailed description

```
I have just start my server.
```

### 🗄 Server log

```
[15:33:00 WARN]: java.io.FileNotFoundException: https://repo.tabooproject.org/repository/releases/public/mongo-java-driver/3.12.7/mongo-java-driver-3.12.7.pom
>.... [15:33:00 WARN]: at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
>.... [15:33:00 WARN]: at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
>.... [15:33:00 WARN]: at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
>.... [15:33:00 WARN]: at java.base/java.net.URL.openStream(URL.java:1161)
>.... [15:33:00 WARN]: at TrMenu-3.01.jar//me.arasple.mc.trmenu.taboolib.common.env.RuntimeEnv.loadDependency(RuntimeEnv.java:147)
>.... [15:33:00 WARN]: at TrMenu-3.01.jar//me.arasple.mc.trmenu.taboolib.common.env.RuntimeEnv.inject(RuntimeEnv.java:45)
>.... [15:33:00 WARN]: at TrMenu-3.01.jar//me.arasple.mc.trmenu.taboolib.common.platform.PlatformFactory.init(PlatformFactory.kt:23)
>.... [15:33:00 WARN]: at TrMenu-3.01.jar//me.arasple.mc.trmenu.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:122)
>.... [15:33:00 WARN]: at TrMenu-3.01.jar//me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:34)
>.... [15:33:00 WARN]: at java.base/java.lang.Class.forName0(Native Method)
>.... [15:33:00 WARN]: at java.base/java.lang.Class.forName(Class.java:467)
>.... [15:33:00 WARN]: at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:73)
>.... [15:33:00 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153)
>.... [15:33:00 WARN]: at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414)
>.... [15:33:00 WARN]: at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322)
>.... [15:33:00 WARN]: at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:422)
>.... [15:33:00 WARN]: at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:287)
>.... [15:33:00 WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1204)
>.... [15:33:00 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319)
>.... [15:33:00 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Score2** [comment]
Fixed in latest version.
