### ISSUE TITLE
[问题]: 加载菜单失败

### ISSUE THREAD

**Issue by lava114514** [InsinuateProjects/TrMenu#128]
### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

TrMenu Dump Information (Date: 2022-01-12 10:57:39)

| Server OS: Windows 10 amd64 10.0
| Server software: git-Paper-399 (MC: 1.17.1) (1.17.1-R0.1-SNAPSHOT)
| Java version: 17.0.1

| TrMenu: 3.01
Installed Plugins: 
· AureliumSkills - Beta 1.2.7 (0 KB)
· BentoBox - 1.18.0 (0 KB)
· BlessingSkinSync - 1.6-SNAPSHOT (0 KB)
· CMILib - 1.1.0.4 (0 KB)
· CatSeedLogin - 1.3.9-SNAPSHOT (0 KB)
· Coins - 1.10.8 (0 KB)
· ConfigItem - 1.0.0 (0 KB)
· CustomForging - 1.2.0 (0 KB)
· EastLandLog4jFixer - 1.0.0 (0 KB)
· EliteMobs - 7.3.8-SNAPSHOT-3 (0 KB)
· GSit - 1.0.5 (0 KB)
· Magic - 10.3-56ba297 (0 KB)
· MiaoBoard - 2.5.1-git-3f193bbf460541fb71a29af94bca98f8317e2ea7 (0 KB)
· MineTinker - 1.7.1 (0 KB)
· MzLib - 10.0.1-pre15 (0 KB)
· PlaceholderAPI - 2.10.10 (0 KB)
· PlayerWarps - 6.12.1 (0 KB)
· ProtocolLib - 4.8.0-SNAPSHOT-b538 (0 KB)
· QuickShop - 5.0.0.16 (0 KB)
· Residence - 5.0.1.0 (0 KB)
· SkinsRestorer - 14.1.10 (0 KB)
· SkyDream - 4.4.1 (0 KB)
· SunSTCore - 1.2.2 (0 KB)
· SunSTKotlinLib - 1.0.0 (0 KB)
· TrMenu - 3.01 (0 KB)
· UltiCore - 1.1.9 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· ViaVersion - 4.1.1 (0 KB)
· iConomy - 5.14 (0 KB)

### 🔍 详细的描述

加载菜单时出错
菜单加载失败

### 🗄 服务端日志

```
> trmenu reload
[10:52:06 WARN]: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class org.openjdk.nashorn.internal.runtime.Context$AnonymousContextCodeInstaller
[10:52:06 WARN]:        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
[10:52:06 WARN]:        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
[10:52:06 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.util.concurrent.TaskConcurrent.start$lambda-3(TaskConcurrent.kt:30)
[10:52:06 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[10:52:06 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[10:52:06 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[10:52:06 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[10:52:06 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[10:52:06 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[10:52:06 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[10:52:06 WARN]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.openjdk.nashorn.internal.runtime.Context$AnonymousContextCodeInstaller
[10:52:06 WARN]:        at TrMenu-3.01.jar//org.openjdk.nashorn.internal.runtime.Context.compile(Context.java:1509)
[10:52:06 WARN]:        at TrMenu-3.01.jar//org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:783)
[10:52:06 WARN]:        at TrMenu-3.01.jar//org.openjdk.nashorn.api.scripting.NashornScriptEngine.asCompiledScript(NashornScriptEngine.java:486)
[10:52:06 WARN]:        at TrMenu-3.01.jar//org.openjdk.nashorn.api.scripting.NashornScriptEngine.compile(NashornScriptEngine.java:178)
[10:52:06 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.taboolib.common5.NashornCompilerKt.compileJS(NashornCompiler.kt:27)
[10:52:06 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.module.internal.script.js.JavaScriptAgent.preCompile$lambda-2(JavaScriptAgent.kt:41)
[10:52:06 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
[10:52:06 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.module.internal.script.js.JavaScriptAgent.preCompile(JavaScriptAgent.kt:40)
[10:52:06 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.api.action.impl.ActionJavaScript.<init>(ActionJavaScript.kt:15)
[10:52:06 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.api.action.impl.ActionJavaScript$Companion$parser$1.invoke(ActionJavaScript.kt:27)
[10:52:06 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.api.action.impl.ActionJavaScript$Companion$parser$1.invoke(ActionJavaScript.kt:26)
[10:52:06 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.api.action.Actions.readAction(Actions.kt:132)
[10:52:06 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.api.action.pack.Reaction$Companion.of(Reaction.kt:22)
[10:52:06 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.api.action.pack.Reactions$Companion.ofReaction(Reactions.kt:21)
[10:52:06 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.module.conf.MenuSerializer$loadIconProperty$1.invoke(MenuSerializer.kt:242)
[10:52:06 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.module.conf.MenuSerializer$loadIconProperty$1.invoke(MenuSerializer.kt:226)
[10:52:06 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.module.conf.MenuSerializer.serializeIcons-YkZ8m0M(MenuSerializer.kt:190)
[10:52:06 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.module.conf.MenuSerializer.serializeMenu(MenuSerializer.kt:77)
[10:52:06 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.module.conf.Loader$loadMenus$2.invoke(Loader.kt:72)
[10:52:06 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.module.conf.Loader$loadMenus$2.invoke(Loader.kt:69)
[10:52:06 WARN]:        at TrMenu-3.01.jar//me.arasple.mc.trmenu.util.concurrent.TaskConcurrent.start$lambda-3$lambda-1$lambda-0(TaskConcurrent.kt:26)
[10:52:06 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[10:52:06 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:52:06 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:52:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### ⚙ 配置文件

```
Title: '你好, %player_name%!' 
Title-Update: 80

Layout:
  - - '########`Close`'
    - '    P    '
    - '  DEHAF  '
    - '    M    '
    - '####*###`Next`'

  - - '########`Close`'
    - '         '
    - ' OK      '
    - '         '
    - '`Pre`########'

PlayerInventory:
  - - '         '
    - '         '
    - '         '
    - '         '

Options:
  Arguments: false
  Default-Arguments: [ ]
  # Not work with animated title
  Free-Slots:
    - 71-73
  Default-Layout: 0
  Hide-Player-Inventory: false
  Min-Click-Delay: 200
  Depend-Expansions: [ 'server', 'player', 'progress', 'animations' ]

Bindings:
  Commands:
    - '(?i)example(-)?(gui)?(s)?'
  Items:
    - 'material:compass'
    - 'material:clock,lore:MENU'
    - 'texture:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDRmNDUyZDk5OGVhYmFjNDY0MmM2YjBmZTVhOGY0ZTJlNjczZWRjYWUyYTZkZmQ5ZTZhMmU4NmU3ODZlZGFjMCJ9fX0='

Events:
  Open:
      actions:
        - 'sound: BLOCK_CHEST_OPEN-1-0'
      deny:
        - 'sound: ENTITY_ITEM_BREAK-1-0'
        - 'title: `&c&lPermission Required` `&7&lYou need permission &6&ltrmenu.use &7&lto open this menu` 15 20 15'
        - 'return'
  Close:
    - 'sound: BLOCK_CHEST_CLOSE-1-0'

Icons:
  '#':
    update: [ -1, 10, 15, -1 ]
    display:
      material: Gray Stained Glass Pane
      name: [ '&7菜&8单', '&7菜&8单', '&7菜&8单','&7菜&8单' ]
    actions:
      all: 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'

  Close:
    update: [ -1, 5, -1, -1 ]
    display:
      material: Red Stained Glass Pane
      name: [ '&c关&7闭', '&c关&7闭', '&c关&7闭', '&c关&7闭', '&c关&7闭' ]
    actions:
      all: close

  Next:
    display:
      material: Cyan Stained Glass Pane
      name: '&b下&3一页'
      lore:
      - '一些合成配方'

    actions:
      all:
        - 'page: 1'
        - 'sound: BLOCK_CHEST_OPEN-1-2'
  Pre:
    display:
      material: Lime Stained Glass Pane
      name: '&a上&2一页'
    actions:
      all:
        - 'page: 0'
        - 'sound: BLOCK_CHEST_OPEN-1-2'

  '*':
    update: [ -1, 5, 20, -1 ]
    display:
      material: <skull:9842dc3b917b1a796c303e15105474a8e315de7982b6ca54feafb5a4d13d4e95>
      name:
        - '&3&l服务器内存占用：'
      lore:
        - ''
        - '&8| &7RAM: &2%server_ram_used%/%server_ram_total% &7MB'
        - '&8[ %progress_bar_{server_ram_used}_m:{server_ram_total}_c:&3■_p:&7■_r:&8■_l:20% &8]'
        - ''
        - '&b${flash_➥} &3左键 &7显示更多.'
    actions:
      left:
        - 'set-meta: icon_server_hide true'
        - 'sound: BLOCK_NOTE_BLOCK_BIT-1-0'
        - 'refresh: *'
    icons:
      - condition: 'check &icon_server_hide is *true'
        priority: 5
        inherit: true
        display:
          lore:
            - ''
            - '&8| &7RAM: &2%server_ram_used%/%server_ram_total% &7MB'
            - '&8[ %progress_bar_{server_ram_used}_m:{server_ram_total}_c:&3■_p:&7■_r:&8■_l:20% &8]'
            - ''
            - '&8| &7在线: &e%server_online% &6${js: utils.getOnlinePlayers().size() > 1 ? "Players" : "Player"}'
            - '&8| &7UPTIME: &e%server_uptime%'
            - '&8| &7TPS: &a%server_tps%'
            - ''
            - '&a${flash_➥} &2右键 &7恢复.'
        actions:
          right:
            - 'rem-meta: icon_server_hide'
            - 'sound: BLOCK_NOTE_BLOCK_BIT-1-2'
            - 'refresh: *'

  P:
    update: 20
    display:
      material: 'head:%player_name%'
      name: '&2&l%player_name%'
      lore:
        - ''
        - '你好, %player_name%! 这是你的信息.'
        - ''
        - '&8| &7生命值: &c%player_health_rounded% ♥'
        - '&8| &7经验等级: &3Lv.%player_level%'
        - '&8| &7时间: &3%player_world_time_24%'
        - ''
        - '&8| &7注册日期: &3%player_first_join_date%'
        - '&8| &7IP: &3%player_ip%'
        - '&8| &7延迟: ${js: varInt("%player_ping%") < 60 ? "&a" : "&2"}%player_ping% ms'
        - ''
        - '&8➥ &7点击数字 &66 &7进行一次高跳'
        - ''
        - '&8%player_uuid%'
    actions:
      all: 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
      number_key_6:
        - 'close'
        - 'title: `&b&LGET READY` &6&l3 10 20 40 &&& sound: ENTITY_ENDER_DRAGON_FLAP-1-0'
        - 'title: `&3&LGET READY` &6&l2 &&& sound: ENTITY_ENDER_DRAGON_FLAP-1-0 {Delay=20}'
        - 'title: `&9&LGET READY` &c&l1 &&& sound: ENTITY_ENDER_DRAGON_FLAP-1-0 {Delay=40}'
        - 'js: player.setVelocity(player.getVelocity().setY(25)) &&& js: player.setNoDamageTicks(600) &&& sound: ENTITY_ENDER_DRAGON_FLAP-1-1 {Delay=50}'
        - 'js: player.setVelocity(player.getVelocity().setY(45)) &&& title: &d&LAGAIN &7&lHIGHER! &&& sound: ENTITY_ENDER_DRAGON_FLAP-1-2 {Delay=100}'

  H:
    update: 20
    display:
      material: beacon
      name: '&b传&3送'
    actions:
      all: 
      - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
      - 'menu: transmission'
  A:
    update: 20
    display:
      material: orange_stained_glass_pane
      name: '&4查看工会（精英怪）等级'
    actions:
      all:
      - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
      - 'command *"ag"'
  E:
    update: 20
    display:
      material: enchanted_book
      name: '&5更多&d附魔'
    actions:
      all:
      - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
      - 'command *"mt mods"'

  M:
    update: 40
    display:
      material: 
      - sunflower
      - tnt
      - sunflower
      name: '&6查看&e自己的资产'
    actions:
      all:
      - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
      - 'command *"money"'
  D:
    update: 40
    display:
      material:
      - iron_sword
      name: '&3技能'
    actions:
      all:
      - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
      - 'command *"sk"'

    O:
    update: 40
    display :
      material:
      - amethyst_shard
      name: '&5紫水晶'

  F:
    update: 40
    display:
      material:
      - dark_oak_planks
      name: '&3Gsit'      
      lore:
        - '/sit坐下'
        - '/lay躺下'
        - '/crawl趴下'
      actions:
      all:
      - 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
      - 'command *"sit"'

  Bee:
    update: 20
    display:
      material: 'head:b727d0ab03f5cd022f8705d3f7f133ca4920eae8e1e47b5074433a137e691e4e'
      name: '&eBee ~'
      slots:
        - [ 9 ]
        - [ 18 ]
        - [ 28 ]
        - [ 29 ]
        - [ 30 ]
        - [ 31 ]
        - [ 32 ]
        - [ 33 ]
        - [ 34 ]
        - [ 35 ]
        - [ 26 ]
        - [ 16 ]
        - [ 15 ]
        - [ 14 ]
        - [ 13 ]
        - [ 12 ]
        - [ 11 ]
        - [ 10 ]
    actions:
      all:
        - 'set-meta: angryBee true'
        - 'sound: ENTITY_ENDERMAN_HURT-1-2'
        - 'rem-meta: angryBee &&& refresh: Bee &&& sound: ENTITY_SPIDER_STEP-1-2 {Delay=80}'
        - 'refresh: Bee'
    icons:
      - condition: 'check &angryBee is *true'
        display:
          name: '&cBee &4~'
          material: 'head:e6b74e052b74288799ba6d9f35c5d0221cf8b04331547ec2f68d73597ae2c9b'
          lore:
            - '受伤...'
        actions:
          all: 'sound: ENTITY_ENDERMAN_HURT-1-2'

Tasks:
  tikTok:
    period: 80
    task:
      - condition: '$ sender.isOp()'
        actions:
          - 'sound: BLOCK_NOTE_BLOCK_BIT-1-2'

Functions:
  flash: |-
    function flash() {
      var display = new Date().getSeconds() % 2 == 0
      return display ? args[0] : "  "
    }
    flash()

  bStats:
    servers: vars("${bStats.query_servers_&a_&7 servers}")
    players: vars("${bStats.query_players_&6_&7 players}")
    menus: vars("${bStats.query_menus_&2_&7 menus}")
    opens: |-
      function opens() {
        var data = utils.query("https://bstats.org/api/v1/plugins/5742/charts/menu_open_counts/data?maxElements=1")
        if (data.has()){
          return "&b" + data.asJson().getAsJsonArray().get(0).getAsJsonArray().get(1) + "&7"
        }
        return "&8Loading." + vars("${flash_.}") + "&7"
      }
      opens()
    query: |-
      function query() {
        var data = utils.query("https://bstats.org/api/v1/plugins/5742/charts/" + args[0] + "/data?maxElements=1")
        if (data.has()){
          return args[1] + data.asJson().getAsJsonArray().get(0).getAsJsonArray().get(1) + args[2]
        }
        return "&8Loading." + vars("${flash_.}")
      }
      query()

```

**Comment by 157946a** [comment]
更新插件,另外,这个跟trmenu本身无太大关系,是因为高版本缺少js引擎导致的,你可以去bbs搜miaonashorn安装使用

**Comment by Score2** [comment]
你 更新到最新版了吗(3.1.1)？
