### ISSUE TITLE
在菜单Options中加入Pure-Packet: false后间歇泉还是无法翻译 

### ISSUE THREAD

**Issue by lava114514** [InsinuateProjects/TrMenu#132]
### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 🔍 详细的描述

```
间歇泉输出：
[ERROR] 无法翻译数据包 ClientboundContainerSetContentPacket
java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
        at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:102) ~[Geyser.jar:?]
        at org.geysermc.geyser.inventory.updater.InventoryUpdater.updateInventory(InventoryUpdater.java:43) ~[Geyser.jar:?]
        at org.geysermc.geyser.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:50) ~[Geyser.jar:?]
        at org.geysermc.geyser.translator.inventory.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56) ~[Geyser.jar:?]
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:55) ~[Geyser.jar:?]
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:37) ~[Geyser.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[Geyser.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[Geyser.jar:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [Geyser.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [Geyser.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
> java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
        at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:102)
        at org.geysermc.geyser.inventory.updater.InventoryUpdater.updateInventory(InventoryUpdater.java:43)
        at org.geysermc.geyser.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:50)
        at org.geysermc.geyser.translator.inventory.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56)
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:55)
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:37)
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### ⚙ 配置文件

```
Options:
  Pure-Packet: false
  Arguments: false
  Default-Arguments: [ ]
  # Not work with animated title
  Free-Slots:
    - 71-73
  Default-Layout: 0
  Hide-Player-Inventory: false
  Min-Click-Delay: 200
  Depend-Expansions: [ 'server', 'player', 'progress', 'animations' ]
```

**Comment by Score2** [comment]
已更换方式实现该功能，请安装Floodgate-bukkit
