### ISSUE TITLE
[问题]: 点击按钮无效，后台抛出错误

### ISSUE THREAD

**Issue by GuNanOvO** [InsinuateProjects/TrMenu#133]
### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [x] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

服务器版本1.18.1
trmenu是来自https://github.com/InsinuateProjects/TrMenu/actions/runs/1682029842的3.1.1版本

### 🔍 详细的描述

这是升级trmenu版本后出现的问题。
只有使用了捕获器的按钮出现这个问题。

### 🗄 服务端日志

[14:12:41 WARN]: [TrMenu] Task #946224 for TrMenu v3.1.1 generated an exception
java.lang.ClassCastException: class me.arasple.mc.trmenu.taboolib.platform.type.BukkitPlayer cannot be cast to class org.bukkit.entity.Player (me.arasple.mc.trmenu.taboolib.platform.type.BukkitPlayer is in unnamed module of loader '[T][菜单]TrMenu-3.1.1.jar' @1b2a2e87; org.bukkit.entity.Player is in unnamed module of loader java.net.URLClassLoader @53e25b76)
        at me.arasple.mc.trmenu.taboolib.platform.BukkitAdapter.adaptPlayer(BukkitAdapter.kt:37) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.function.AdapterKt.adaptPlayer(Adapter.kt:35) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.action.impl.ActionActionbar.onExecute(ActionActionbar.kt:16) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1$1.invoke(AbstractAction.kt:39) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1$1.invoke(AbstractAction.kt:39) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionOption.evalPlayers(ActionOption.kt:34) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1.invoke(AbstractAction.kt:39) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1.invoke(AbstractAction.kt:39) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.action.base.AbstractAction.run(AbstractAction.kt:41) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.action.Actions.runAction(Actions.kt:51) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.action.Actions$Companion.runAction(Actions.kt:121) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.reaction.Reactions.eval(Reactions.kt:16) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.action.InternalActionKt.eval(InternalAction.kt:37) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.module.internal.inputer.Inputer.run(Inputer.kt:48) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.module.internal.inputer.Inputer.startInput(Inputer.kt:43) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.action.impl.func.ActionCatcher.onExecute(ActionCatcher.kt:22) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.action.InternalAction.onExecute(InternalAction.kt:31) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1$1.invoke(AbstractAction.kt:39) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1$1.invoke(AbstractAction.kt:39) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionOption.evalPlayers(ActionOption.kt:34) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1.invoke(AbstractAction.kt:39) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1.invoke(AbstractAction.kt:39) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.action.base.AbstractAction.run(AbstractAction.kt:41) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.action.Actions.runAction(Actions.kt:51) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.action.Actions$Companion.runAction(Actions.kt:121) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.reaction.Reactions.eval(Reactions.kt:16) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.api.action.InternalActionKt.eval(InternalAction.kt:37) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.IconProperty.handleClick(IconProperty.kt:42) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1$1.invoke(Layout.kt:93) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1$1.invoke(Layout.kt:91) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$7.run(BukkitExecutor.kt:98) ~[[T][菜单]TrMenu-3.1.1.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.1.jar:git-Purpur-1497]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.1.jar:git-Purpur-1497]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1574) ~[purpur-1.18.1.jar:git-Purpur-1497]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1497]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1497) ~[purpur-1.18.1.jar:git-Purpur-1497]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1285) ~[purpur-1.18.1.jar:git-Purpur-1497]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1497]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### ⚙ 配置文件

  'A':
    display:
      material: 'Music_Disc_Cat'
      name: '&e♩ &f&l搜索音乐 &e♩'
      lore:
        - '&8[&a&l·&8] &f使用指令搜索音乐'
        - '&8[&a&l·&8] &f'
        - '&8[&a&l·&8] &f/music search '
        - '&8[&a&l·&8] &f'
        - '&8[&a&l·&8] &f搜索结果点击播放'
    actions:
      all:
        - catcher:
            song:
              type: SIGN
              start: 
                - 'actionbar: &c&l输入想要搜索的歌曲名进行搜索'
                - 'tell: &6&l| &r搜索歌曲，输入 cancel 取消搜歌'
              cancel: 'tell: &6&l| &r已取消搜歌'
              end:
                - condition: null
                  actions:
                    - 'close'
                    - 'chat: /music search {meta:input}'

**Comment by GuNanOvO** [comment]
这个问题解决了，又发现了问题，我就不开新问题了。
周期任务不起作用，后台没有错误，以前是好的，更新了之后就不行了。
```

Tasks:
  close:
    period: 1
    task:
      - condition: 'perm *trmenu.use'
        actions:
          - 'tell: aaaa'
```


空动作按钮点击会提示未知音效，同样后台没有错误：
```
  'A1':
    update: 20
    display:
      material: 'clock'
      name: 'xxx'
      lore:
        - 'xxx'
    actions:
      all:
        - ''
```
如果把动作改成actions: []那就没有问题。我不确定这是个问题，但是它在以前的版本中写成像上面这种也没有问题。

**Comment by 157946a** [comment]
周期任务已经知道了,之前有在尝试修复,但因为维护者学业原因,并且出现了更严重的问题,就放一边了,至于第二个,如果你不写动作,完全可以将actions以下的删除,不需要- ''或者all: []
