### ISSUE TITLE
[问题]: 使用trmenu item save指令保存物品后台会刷新该物品的报错

### ISSUE THREAD

**Issue by yese-233** [InsinuateProjects/TrMenu#137]
### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

TrMenu Dump Information (Date: 2022-01-30 04:47:45)

| Server OS: Windows Server 2016 amd64 10.0
| Server software: git-CatServer-1.12.2-50610c7 (MC: 1.12.2) (1.12.2-R0.1-SNAPSHOT)
| Java version: 1.8.0_321

| TrMenu: 3.1.1
Installed Plugins: 
· BetterRandTp - 1.0.0 (0 KB)
· CMI - 8.6.27.4 (0 KB)
· CrazyCrates - 1.10.1-SNAPSHOT-Build#87 (0 KB)
· CtOnlineReward - 0.1.6 (0 KB)
· CustomTags - 1.0-SNAPSHOT (0 KB)
· DeluxeTags - 1.8.1 (0 KB)
· EndBattle - 1.0.2-SNAPSHOT (0 KB)
· Fixer - 1.6.3-SNAPSHOT (0 KB)
· FriendsPremium - 1.1.0.9.3 (0 KB)
· GermPlugin - 4.0.1 (0 KB)
· GlazedPay - 1.0.0 (0 KB)
· HamsterAPI - 2.4.4-SNAPSHOT (0 KB)
· HamsterEssentials - 2.1.3-SNAPSHOT (0 KB)
· HamsterLegendPixelmon-Bukkit - 1.1.5-SNAPSHOT (0 KB)
· HamsterService-Bukkit - 2.6.2-SNAPSHOT (0 KB)
· HamsterSync - 2.4.0-SNAPSHOT (0 KB)
· LaggRemover - 2.0.5 (0 KB)
· LuckPerms - 4.4.27 (0 KB)
· LuckyBlock - 1.0.0-SNAPSHOT (0 KB)
· MarketPlace - 3.2.2 (0 KB)
· MiaoChat - 1.9.5-git-45ec56bebe0a3122ac9ffec02101cd4818547608 (0 KB)
· Multiverse-Core - 1.1 (0 KB)
· MyCommand - 5.7.1 (0 KB)
· NyEconomy - 1.4.5-SNAPSHOT (0 KB)
· OnlineRewardSuu_Q - 0.1 (0 KB)
· PixelmonEssentials - 1.3.1-8.0.2-public (0 KB)
· PlaceholderAPI - 2.9.2 (0 KB)
· PlayerCommands - 1.0.0 (0 KB)
· PlayerPoints - 2.1.5-SNAPSHOT (0 KB)
· PokeClear - 1.4 (0 KB)
· PokeEggs - 1.2.7 (0 KB)
· PokeTaskPlugin - 2.2.2-SNAPSHOT (0 KB)
· PokeTrainerRankPlugin - 0.1.7.5 (0 KB)
· PokemonAPI - 3.2.0.11-SNAPSHOT (0 KB)
· PokemonHuntArean - 1.6.2-SNAPSHOT (0 KB)
· PokemonPapiPro - 1.1.0 (0 KB)
· ProtocolLib - 4.4.0 (0 KB)
· QuestsPokemon - 0.1 (0 KB)
· RandomCommand - 1.0 (0 KB)
· RechargePlaceholder - 0.1 (0 KB)
· Residence - 4.7.8.1 (0 KB)
· SQLibrary - 7.1 (0 KB)
· Suu_Q_PluginLib_Outside - 0.1 (0 KB)
· TrMenu - 3.1.1 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· VoidGen - 2.0 (0 KB)
· WorldEdit - 6.1.9;caf0ad9 (0 KB)
· XConomy - 2.11.9 (0 KB)

### 🔍 详细的描述

1.使用trmenu item save物品后后台会刷新报错
2.该报错定时出现

### 🗄 服务端日志

```

```
 [TrMenu] Plugin TrMenu v3.1.1 generated an exception while executing task 93
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_321]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_321]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_321]
        at me.arasple.mc.trmenu.taboolib.common.platform.ScheduleLoader$inject$1.invoke(ScheduleLoader.kt:22) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.ScheduleLoader$inject$1.invoke(ScheduleLoader.kt:22) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$2.run(BukkitExecutor.kt:51) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-50610c7]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-50610c7]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_321]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_321]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_321]
Caused by: java.lang.IllegalArgumentException: Unsupported material from item: ARMOURERS_WORKSHOP_ITEMSKIN (0)
        at me.arasple.mc.trmenu.taboolib.library.xseries.XMaterial.lambda$matchXMaterial$1(XMaterial.java:1701) ~[?:?]
        at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_321]
        at me.arasple.mc.trmenu.taboolib.library.xseries.XMaterial.matchXMaterial(XMaterial.java:1701) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.library.xseries.XItemStack.serialize(XItemStack.java:99) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.library.xseries.XItemStackKt.setItemStack(XItemStack.kt:11) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.item.ItemRepository.save(ItemRepository.kt:34) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.item.ItemRepository.saveTask(ItemRepository.kt:26) ~[?:?]
        ... 12 more

### ⚙ 配置文件

```

```

**Comment by 157946a** [comment]
使用最新构建

**Comment by 157946a** [comment]
重启失效是正常的,因为这个是bug https://github.com/InsinuateProjects/TrMenu/issues/155

**Comment by 157946a** [comment]
保存成功的话,关闭该问题吧

**Comment by yese-233** [comment]
> 保存成功的话,关闭该问题吧

。。。老版本的是没有这个问题的，我建议保存物品应该加个nbt

**Comment by 157946a** [comment]
知道,所以有可能会重写,这个一早就知道的了

**Comment by 157946a** [comment]
或者你自己写上nbt,display有这个功能

**Comment by 157946a** [comment]
如果你是说2的话，他确实没问题，3的初代版本就已经出现这种问题了，只是不是那么频繁，重启就消失
