### ISSUE TITLE
[问题]: Trmenu无法正确加载

### ISSUE THREAD

**Issue by 1636578433** [InsinuateProjects/TrMenu#145]
### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
无法使用此指令因为没有成功加载插件
https://pastebin.com/5hTBLYuP
```

### 🔍 详细的描述

```
1. 开启伺服器
2. 成功开启伺服器并且/plugins指令有显示trmenu
3. 无法使用任何/trmenu指令
```

### 🗄 服务端日志

```
我觉得可能跟下面有关,完整纪录在下面
[20:28:42] [Server thread/INFO] [me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin/]: [TrMenu] Enabling TrMenu v3.1.1
[20:28:42] [Server thread/INFO] [me.clip.placeholderapi.PlaceholderAPIPlugin/]: [PlaceholderAPI] Successfully registered expansion: TrMenu [3.1.1]
[20:28:43] [ForkJoinPool.commonPool-worker-0/INFO] [/]: [0;30;1m[[0;36;22mTr[0;36;1mMenu[0;30;1m] [0;32;1mFINE [0;30;1m| [0;32;1m7 [0;36;22mmenus were loaded [0;30;1m(597 ms)[m
[20:28:43] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling TrMenu v3.1.1 (Is it up to date?)
java.lang.NoClassDefFoundError: org/slf4j/spi/SLF4JServiceProvider
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_212]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_212]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_212]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_212]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_212]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_212]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_212]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_212]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411) ~[?:1.8.0_212]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.1.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370) ~[?:1.8.0_212]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[?:1.8.0_212]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[?:1.8.0_212]
	at org.slf4j.LoggerFactory.findServiceProviders(LoggerFactory.java:104) ~[?:?]
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:147) ~[?:?]
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:139) ~[?:?]
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:421) ~[?:?]
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:407) ~[?:?]
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:356) ~[?:?]
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:382) ~[?:?]
	at com.zaxxer.hikari_4_0_3.HikariConfig.<clinit>(HikariConfig.java:51) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.module.database.Database.createDataSource(Database.kt:18) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.module.database.Database.createDataSource$default(Database.kt:17) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.module.database.Host.createDataSource(Host.kt:22) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.module.database.Host.createDataSource$default(Host.kt:21) ~[?:?]
	at me.arasple.mc.trmenu.module.internal.database.DatabaseSQLite.<init>(DatabaseSQLite.kt:46) ~[?:?]
	at me.arasple.mc.trmenu.module.internal.data.Metadata$database$2.invoke(Metadata.kt:40) ~[?:?]
	at me.arasple.mc.trmenu.module.internal.data.Metadata$database$2.invoke(Metadata.kt:38) ~[?:?]
	at kotlin1610.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
	at me.arasple.mc.trmenu.module.internal.data.Metadata.getDatabase(Metadata.kt:38) ~[?:?]
	at me.arasple.mc.trmenu.TrMenu.onEnable(TrMenu.kt:50) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:61) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:412) ~[forge:1.16.5-9e46bd3]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:323) ~[forge:1.16.5-9e46bd3]
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:426) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:344) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:217) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:724) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:264) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: org.slf4j.spi.SLF4JServiceProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	... 49 more

完整纪录:
[latest (2).log](https://github.com/InsinuateProjects/TrMenu/files/8008041/latest.2.log)

```

### ⚙ 配置文件

```

```

**Comment by 157946a** [comment]
似乎和DiscordSRV冲突了,又好像是nbtapi,你尝试先删除discordsrv看看

**Comment by 1636578433** [comment]
https://pastebin.com/uzpG6Ja6
两个插件我都删过了,还是不行
