### ISSUE TITLE
1.16.5paper776 Java11 无法读取菜单文件

### ISSUE THREAD

**Issue by wzq20010724** [InsinuateProjects/TrMenu#15]
[12:22:12 WARN]: java.lang.NullPointerException
[12:22:12 WARN]:        at io.izzel.taboolib.module.inject.THookLoader.activeLoad(THookLoader.java:22)
[12:22:12 WARN]:        at io.izzel.taboolib.TabooLibLoader.lambda$activeLoadClass$9(TabooLibLoader.java:280)
[12:22:12 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[12:22:12 WARN]:        at io.izzel.taboolib.TabooLibLoader.activeLoadClass(TabooLibLoader.java:277)
[12:22:12 WARN]:        at io.izzel.taboolib.PluginLoader$1.onActivated(PluginLoader.java:78)
[12:22:12 WARN]:        at io.izzel.taboolib.PluginLoader.lambda$active$4(PluginLoader.java:213)
[12:22:12 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[12:22:12 WARN]:        at io.izzel.taboolib.PluginLoader.active(PluginLoader.java:213)
[12:22:12 WARN]:        at ray.mintcat.wizard.boot.PluginBase.lambda$onEnable$0(PluginBase.java:64)
[12:22:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[12:22:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[12:22:12 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1078)
[12:22:12 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[12:22:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[12:22:12 WARN]: java.lang.NullPointerException
[12:22:12 WARN]:        at io.izzel.taboolib.module.inject.THookLoader.activeLoad(THookLoader.java:22)
[12:22:12 WARN]:        at io.izzel.taboolib.TabooLibLoader.lambda$activeLoadClass$9(TabooLibLoader.java:280)
[12:22:12 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[12:22:12 WARN]:        at io.izzel.taboolib.TabooLibLoader.activeLoadClass(TabooLibLoader.java:277)
[12:22:12 WARN]:        at io.izzel.taboolib.PluginLoader$1.onActivated(PluginLoader.java:78)
[12:22:12 WARN]:        at io.izzel.taboolib.PluginLoader.lambda$active$4(PluginLoader.java:213)
[12:22:12 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[12:22:12 WARN]:        at io.izzel.taboolib.PluginLoader.active(PluginLoader.java:213)
[12:22:12 WARN]:        at ray.mintcat.wizard.boot.PluginBase.lambda$onEnable$0(PluginBase.java:64)
[12:22:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[12:22:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[12:22:12 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1078)
[12:22:12 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[12:22:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

[12:22:12 WARN]: [TrMenu] Task #137 for TrMenu v3.0-PRE-14 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class me.arasple.mc.trmenu.taboolib.common5.FileWatcher
        at me.arasple.mc.trmenu.TrMenu$onEnable$1.invoke(TrMenu.kt:42) ~[?:?]
        at me.arasple.mc.trmenu.TrMenu$onEnable$1.invoke(TrMenu.kt:41) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$7.run(BukkitExecutor.kt:98) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-776]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1078) ~[patched_1.16.5.jar:git-Paper-776]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-776]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Score2** [comment]
请完整提供latest.log文件

**Comment by wzq20010724** [comment]
> 请完整提供latest.log文件

[latest.log](https://github.com/InsinuateProjects/TrMenu/files/6952152/latest.log)

**Comment by Score2** [comment]
无法复现，此外，你的paper是776，1.16.5的最新版paper是785，尝试更新一下，然后再测试一次

**Comment by wzq20010724** [comment]
测试基于paper786
经过2小时测试，结果为：
当插件数量大于等于25，且安装了
https://github.com/Rothes/ProtocolStringReplacer
插件时，
会导致菜单无法加载

**Comment by wzq20010724** [comment]
> 无法复现，此外，你的paper是776，1.16.5的最新版paper是785，尝试更新一下，然后再测试一次

测试基于paper786
经过2小时测试，结果为：
当插件数量大于等于25，且安装了
https://github.com/Rothes/ProtocolStringReplacer
插件时，
会导致菜单无法加载

**Comment by wzq20010724** [comment]
[https://wwe.lanzoui.com/ilrBVserkqf](url)

**Comment by Score2** [comment]
Rothes/ProtocolStringReplacer#9

ProtocolStringReplacer作者已修复该问题
