### ISSUE TITLE
[问题]: 貌似有些模组的物品矿石出售和收购不了shop-example配置文件里面的

### ISSUE THREAD

**Issue by yuankun1** [InsinuateProjects/TrMenu#158]
### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

TrMenu Dump Information (Date: 2022-03-09 22:59:25)

| Server OS: Windows Server 2019 amd64 10.0
| Server software: git-Mohist-1.12.2-309 (MC: 1.12.2) (1.12.2-R0.1-SNAPSHOT)
| Java version: 1.8.0_291

| TrMenu: 3.1.8
Installed Plugins: 
· AntiBuild - 1.3.2-SNAPSHOT (0 KB)
· AntiExplosion - 1.0.1 (0 KB)
· AsyncKeepAlive - 0.3 (0 KB)
· AudioBuffer - 1.0.3 (0 KB)
· AuthMe - 5.6.0-SNAPSHOT-b2481 (0 KB)
· BanIt - 1.1.0 (0 KB)
· BeatPoke - 1.0 (0 KB)
· BlockParticles - 1.11.1-RELEASE (0 KB)
· CMI - 9.1.1.1 (0 KB)
· CMILib - 1.1.2.0 (0 KB)
· CombatPower - 1.0.3-SNAPSHOT (0 KB)
· CoreProtect - 2.14.4 (0 KB)
· CowSuperJoin - 1.71 (0 KB)
· CrazyAuctionsPlus - 1.2.0.1 (0 KB)
· CrazyCrates - 1.10.1-RELEASE (0 KB)
· CtOnlineReward - 0.1.7 (0 KB)
· CustomBossHealth - ULTX (0 KB)
· DomainAudio - 1.0.0 (0 KB)
· DragonCore - 2.5.4 (0 KB)
· DreamChest - 1.0.4-SNAPSHOT (0 KB)
· EpicPluginLib - 1.6.6 (0 KB)
· EscapeLag - 2.1.0-b557 (0 KB)
· FastAsyncWorldEdit - ${version} (0 KB)
· FileListener - 1.0.0 (0 KB)
· Fixer - 1.6.8-SNAPSHOT (0 KB)
· HeroAction - 4.0 (0 KB)
· IllegalStack - 2.4.2a (0 KB)
· LegendarySpawnExpand - 1.2 (0 KB)
· LiteInvitation - 1.4.5-SNAPSHOT (0 KB)
· LiteSignIn - 1.4.0 (0 KB)
· LuckPerms - 5.2.76 (0 KB)
· MinePay - Release 2.6.9 (0 KB)
· MiniMOTD - 2.0.4 (0 KB)
· MobFarmManager - 2.0.2.1 (0 KB)
· Multiverse-Core - 2.5.0-b727 (0 KB)
· Multiverse-Patches - 1.0.0-SNAPSHOT (0 KB)
· NBTAPI - 2.8.0 (0 KB)
· NyEconomy - 1.4.5-SNAPSHOT (0 KB)
· NyPhysical - 1.2.6-SNAPSHOT (0 KB)
· PTweaks - 6.0.16-b13 (0 KB)
· PixelExtras - 1.5.1-SNAPSHOT (0 KB)
· PixelVip - 3.0.3 (0 KB)
· PixelmonEssentials - 1.3.1-8.0.2-public (0 KB)
· PixelmonExpSpring - 1.3-SNAPSHOT (0 KB)
· PixelmonPvp - 2.3.1.0-SNAPSHOT (0 KB)
· PlaceholderAPI - 2.10.9 (0 KB)
· PlayMoreSounds - 3.3.0 (0 KB)
· PlayerPoints - 3.0.3 (0 KB)
· PlayerTitle - 2.10.4 (0 KB)
· PlotSquared - 19.12.10-b4c257b-788 (0 KB)
· PlugMan - 2.2.5 (0 KB)
· PokeBoss - 3.6 (0 KB)
· PokeBreedLimit - 1.1 (0 KB)
· PokeDexLimit - 1.0 (0 KB)
· PokeDialogue - 1.2 (0 KB)
· PokeEvo - 1.0-SNAPSHOT (0 KB)
· PokeExplore - 1.0 (0 KB)
· PokeMessage - 1.0 (0 KB)
· PokeMsg - 2.1-SNAPSHOT (0 KB)
· PokePlate - 1.4.5 (0 KB)
· PokeStar - 1.1.3-SNAPSHOT (0 KB)
· PokeTaskPlugin - 2.1.9-RELEASE (0 KB)
· PokeTools - 1.1.4-SNAPSHOT (0 KB)
· PokemonAPI - 3.2.1.0-SNAPSHOT (0 KB)
· PokemonHuntArean - 1.6.2-SNAPSHOT (0 KB)
· PokemonInfo - 1.9.8-SNAPSHOT (0 KB)
· PokemonJianding - 1.0 (0 KB)
· PokemonMoreExp - 1.0 (0 KB)
· PokemonSkin - 1.0 (0 KB)
· PokemonTrain - 1.0 (0 KB)
· ProtocolLib - 4.7.0 (0 KB)
· PuerkasMarriage - 1.9.5-BETA (0 KB)
· QuickShop - 2.3.1-git-8edb488ab24519236553cabd943e946c6f223b02 (0 KB)
· RandomGrowth - 1.0.0-SNAPSHOT (0 KB)
· SpawnLegTime - 2.0 (0 KB)
· SuperTrailsPro - v1.2.17 (0 KB)
· TXZ - 1.4.6-SNAPSHOT (0 KB)
· TimedWorld - 1.1 (0 KB)
· TitleDomain - 1.2.1 (0 KB)
· TrChat - 1.90-R3 (0 KB)
· TrMenu - 3.1.8 (0 KB)
· TradeBlackList - 1.1 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· VeinMiner - 1.11.3 (0 KB)
· VoidGen - 2.0 (0 KB)
· WorldBorder - 1.8.7 (0 KB)
· WorldEdit - 6.1.9-0.3-SNAPSHOT (0 KB)
· XConomy - 2.11.4 (0 KB)
· XinxinApi - 1.1.0-SNAPSHOT (0 KB)
· XinxinPokeConnection - 1.0.1-SNAPSHOT (0 KB)
· YukiNoaAPI - 1.0.0 (0 KB)

### 🔍 详细的描述

```
1.shop-example收购和出售商城配置文件
2. 貌似mod物品的东西都不能点击购买收购和出售
2. ...
3. ...
```

### 🗄 服务端日志

[22:57:17 WARN]: [TrMenu] Task #30126 for TrMenu v3.1.8 generated an exception
 java.lang.IllegalArgumentException: No enum constant me.arasple.mc.trmenu.taboolib.library.xseries.XMaterial.PIXELMON_FIRE_STONE_ORE
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_291]
        at me.arasple.mc.trmenu.taboolib.library.xseries.XMaterial.valueOf(XMaterial.java:69) ~[?:?]
        at me.arasple.mc.trmenu.util.bukkit.ItemMatcher.buildItem(ItemMatcher.kt:88) ~[?:?]
        at me.arasple.mc.trmenu.api.action.impl.func.GiveItem.onExecute(GiveItem.kt:24) ~[?:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29) ~[?:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29) ~[?:?]
        at me.arasple.mc.trmenu.api.action.base.ActionBase$Option.evalPlayers(ActionBase.kt:115) ~[?:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29) ~[?:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29) ~[?:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry.execute(ActionEntry.kt:31) ~[?:?]
        at me.arasple.mc.trmenu.api.action.ActionHandle.runAction(ActionHandle.kt:92) ~[?:?]
        at me.arasple.mc.trmenu.api.reaction.Reactions.eval(Reactions.kt:16) ~[?:?]
        at me.arasple.mc.trmenu.module.display.icon.IconProperty.handleClick(IconProperty.kt:42) ~[?:?]
        at me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1$1.invoke(Layout.kt:93) ~[?:?]
        at me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1$1.invoke(Layout.kt:91) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$7.run(BukkitExecutor.kt:98) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[CraftTask.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:422) [CraftScheduler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]

### ⚙ 配置文件

  'T':
    display:
      material: '{"type":"PIXELMON_CRYSTAL","data":0,"amount":1,"meta":{}}'
      lore:
        - ''
        - '&8▪ &7购买价格: &e$20.0'
        - '&8▪ &7出售价格: &2$3.5'
        - ''
        - '&e➥ &c左键 &8| &6购买'
        - '&e➥ &2右键 &8| &4出售'
    actions:
      all:
        - 'sound: UI_BUTTON_CLICK-1-2'
      left:
        - 'open: 购买菜单 矿石商城 PIXELMON_CRYSTAL 20 1 64'
      right:
        - 'open: 出售菜单 矿石商城 PIXELMON_CRYSTAL 3.5 1 64'

**Comment by 157946a** [comment]
更新插件
