### ISSUE TITLE
[问题]: TrMenu 3.1.8 在 NachoSpigot 上无法正常启动

### ISSUE THREAD

**Issue by Yurinann** [InsinuateProjects/TrMenu#161]
### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
  | Server OS: Windows Server 2019
  | Server software: NachoSpigot
  | Java version: Azul Zulu 17.0.2

  | TabooLib: ?
  | TrMenu: 3.1.8
```

### 🔍 详细的描述

```
1. 启动服务器
2. 插件加载时报错
```

### 🗄 服务端日志

```
[20:45:27 INFO]: [TrMenu] Enabling TrMenu v3.1.8
[20:45:27 INFO]: [PlaceholderAPI] Successfully registered expansion: TrMenu [3.1.8]
[20:45:28 INFO]: [TrMenu] 良好 | 7 个菜单已加载 (1162 ms)

[20:45:28 INFO]: HikariPool-1 - Starting...
[20:45:28 INFO]: HikariPool-1 - Driver does not support get/set network timeout for connections. (Receiver class org.sqlite.Conn does not define or inherit an implementation of the resolved method 'abstract int getNetworkTimeout()' of interface java.sql.Connection.)
[20:45:28 ERROR]: HikariPool-1 - Failed to execute isValid() for connection, configure connection test query (Receiver class org.sqlite.Conn does not define or inherit an implementation of the resolved method 'abstract boolean isValid(int)' of interface java.sql.Connection.).
[20:45:28 ERROR]: Error occurred while enabling TrMenu v3.1.8 (Is it up to date?)
java.lang.AbstractMethodError: Receiver class org.sqlite.Conn does not define or inherit an implementation of the resolved method 'abstract boolean isValid(int)' of interface java.sql.Connection.
        at com.zaxxer.hikari_4_0_3.pool.PoolBase.checkValidationSupport(PoolBase.java:464) ~[?:?]
        at com.zaxxer.hikari_4_0_3.pool.PoolBase.checkDriverSupport(PoolBase.java:447) ~[?:?]
        at com.zaxxer.hikari_4_0_3.pool.PoolBase.setupConnection(PoolBase.java:416) ~[?:?]
        at com.zaxxer.hikari_4_0_3.pool.PoolBase.newConnection(PoolBase.java:369) ~[?:?]
        at com.zaxxer.hikari_4_0_3.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[?:?]
        at com.zaxxer.hikari_4_0_3.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[?:?]
        at com.zaxxer.hikari_4_0_3.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[?:?]
        at com.zaxxer.hikari_4_0_3.pool.HikariPool.<init>(HikariPool.java:115) ~[?:?]
        at com.zaxxer.hikari_4_0_3.HikariDataSource.<init>(HikariDataSource.java:81) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.database.Database.createDataSource(Database.kt:18) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.database.Database.createDataSource$default(Database.kt:17) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.database.Host.createDataSource(Host.kt:22) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.database.Host.createDataSource$default(Host.kt:21) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.database.DatabaseSQLite.<init>(DatabaseSQLite.kt:46) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.data.Metadata$database$2.invoke(Metadata.kt:41) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.data.Metadata$database$2.invoke(Metadata.kt:39) ~[?:?]
        at kotlin1610.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.data.Metadata.getDatabase(Metadata.kt:39) ~[?:?]
        at me.arasple.mc.trmenu.TrMenu.onEnable(TrMenu.kt:53) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:61) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[NachoSpigot.jar:git-NachoSpigot-"adae067"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [NachoSpigot.jar:git-NachoSpigot-"adae067"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:393) [NachoSpigot.jar:git-NachoSpigot-"adae067"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:392) [NachoSpigot.jar:git-NachoSpigot-"adae067"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:351) [NachoSpigot.jar:git-NachoSpigot-"adae067"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:403) [NachoSpigot.jar:git-NachoSpigot-"adae067"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:367) [NachoSpigot.jar:git-NachoSpigot-"adae067"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:329) [NachoSpigot.jar:git-NachoSpigot-"adae067"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:295) [NachoSpigot.jar:git-NachoSpigot-"adae067"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [NachoSpigot.jar:git-NachoSpigot-"adae067"]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[20:45:28 INFO]: [TrMenu] Disabling TrMenu v3.1.8
```

### ⚙ 配置文件

```
无，默认菜单
```

**Comment by 157946a** [comment]
1.8请看Wiki

**Comment by Yurinann** [comment]
是的，已按照 Wiki 中的方法进行调整，该问题也已经解决。但这或许可以拥有更好的解决方法？例如在启动时首先检测核心版本，手动 set 为对应值。

当然，或许此问题下潜藏着一些个人并未察觉的更严重问题，因此由您来决定是否关闭此议题，感谢您的帮助。
