### ISSUE TITLE
[功能]: 请更新1.18.2适配

### ISSUE THREAD

**Issue by srlss123** [InsinuateProjects/TrMenu#163]
### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 🔍 详细的描述

1.支持1.18.2

### ⚙ 配置文件

目前版本报错:
[13:41:53 INFO]: alglt issued server command: /trmenu open menu
[13:41:53 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'trmenu' in plugin TrMenu v3.1.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905) ~[purpur-1.18.2.jar:git-Purpur-1588]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2380) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2191) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2172) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1588]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[purpur-1.18.2.jar:git-Purpur-1588]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1588]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1403) ~[purpur-1.18.2.jar:git-Purpur-1588]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1396) ~[purpur-1.18.2.jar:git-Purpur-1588]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1374) ~[purpur-1.18.2.jar:git-Purpur-1588]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1256) ~[purpur-1.18.2.jar:git-Purpur-1588]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1588]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.LinkageError: loader me.arasple.mc.trmenu.taboolib.module.nms.AsmClassLoader @483ce175 attempted duplicate class definition for me.arasple.mc.trmenu.api.receptacle.NMSImpl. (me.arasple.mc.trmenu.api.receptacle.NMSImpl is in unnamed module of loader me.arasple.mc.trmenu.taboolib.module.nms.AsmClassLoader @483ce175, parent loader 'TrMenu-3.1.3.jar' @4c1f3e4c)
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.nms.AsmClassLoader.createNewClass(AsmClassLoader.kt:18) ~[TrMenu-3.1.3.jar:?]
        at me.arasple.mc.trmenu.taboolib.module.nms.AsmClassTransfer.run(AsmClassTransfer.kt:23) ~[TrMenu-3.1.3.jar:?]
        at me.arasple.mc.trmenu.taboolib.module.nms.MinecraftServerUtilKt.nmsProxy$lambda-1(MinecraftServerUtil.kt:27) ~[TrMenu-3.1.3.jar:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.nms.MinecraftServerUtilKt.nmsProxy(MinecraftServerUtil.kt:25) ~[TrMenu-3.1.3.jar:?]
        at me.arasple.mc.trmenu.api.receptacle.PacketInventory$DefaultImpls.send(PacketInventory.kt:16) ~[TrMenu-3.1.3.jar:?]
        at me.arasple.mc.trmenu.api.receptacle.PacketWindowItems.send(PacketWindowItems.kt:16) ~[TrMenu-3.1.3.jar:?]
        at me.arasple.mc.trmenu.api.receptacle.Receptacle.refresh(Receptacle.kt:76) ~[TrMenu-3.1.3.jar:?]
        at me.arasple.mc.trmenu.api.receptacle.Receptacle.refresh$default(Receptacle.kt:70) ~[TrMenu-3.1.3.jar:?]
        at me.arasple.mc.trmenu.api.receptacle.Receptacle.clear(Receptacle.kt:66) ~[TrMenu-3.1.3.jar:?]
        at me.arasple.mc.trmenu.api.receptacle.Receptacle.clear$default(Receptacle.kt:63) ~[TrMenu-3.1.3.jar:?]
        at me.arasple.mc.trmenu.module.display.Menu.page(Menu.kt:115) ~[TrMenu-3.1.3.jar:?]
        at me.arasple.mc.trmenu.module.display.Menu.open(Menu.kt:61) ~[TrMenu-3.1.3.jar:?]
        at me.arasple.mc.trmenu.module.internal.command.impl.CommandOpen$command$1$1$2.invoke(CommandOpen.kt:47) ~[TrMenu-3.1.3.jar:?]
        at me.arasple.mc.trmenu.module.internal.command.impl.CommandOpen$command$1$1$2.invoke(CommandOpen.kt:36) ~[TrMenu-3.1.3.jar:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandExecutor.exec(CommandBuilder.kt:185) ~[TrMenu-3.1.3.jar:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:95) ~[TrMenu-3.1.3.jar:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:87) ~[TrMenu-3.1.3.jar:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandBase.execute(CommandBuilder.kt:108) ~[TrMenu-3.1.3.jar:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandRegisterKt$command$1.execute(CommandRegister.kt:23) ~[TrMenu-3.1.3.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitCommand$registerCommand$1.invoke$lambda-0(BukkitCommand.kt:69) ~[TrMenu-3.1.3.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 21 more

**Comment by srlss123** [comment]
没事了 才发现有3.1.9
正常
