### ISSUE TITLE
[问题]: /trmenu item toJson 在 1.8 版本出现错误

### ISSUE THREAD

**Issue by Yurinann** [InsinuateProjects/TrMenu#165]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2022-03-17 00:34:00)

| Server OS: Windows Server 2019 amd64 10.0
| Server software: git-NachoSpigot-"0f4e14e" (MC: 1.8.8) (1.8.8-R0.2-SNAPSHOT)
| Java version: 17.0.2

| TrMenu: 3.1.9
Installed Plugins: 
· Citizens - 2.0.29-SNAPSHOT (build 2501) (0 KB)
· GadgetsMenu - 5.1.4 (0 KB)
· LuckPerms - 5.4.9 (0 KB)
· PlaceholderAPI - 2.11.1 (0 KB)
· PlayerBalancerAddon - 2.3.2-SNAPSHOT (0 KB)
· PlayerPoints - 3.2.1 (0 KB)
· ProtocolLib - 4.8.0 (0 KB)
· SuperLobby - 4.3.8 (0 KB)
· TAB-Bridge - 2.0.0 (0 KB)
· TrMenu - 3.1.9 (0 KB)
· UserPrefix - 2.4.3 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· ViaVersion - 4.2.1 (0 KB)
· momojs - 1.0.3 (0 KB)
```

### 🔍 详细的描述

```
1. 1.8 Minecraft, 手持任意物品输入 /trm item toJson
2. 无输出，后台报错
```

### 🗄 服务端日志

```
[00:32:53 INFO]: Yurinann issued server command: /trm item toJson
[00:32:53 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'trm' in plugin TrMenu v3.1.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[NachoSpigot.jar:git-NachoSpigot-"0f4e14e"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:147) ~[NachoSpigot.jar:git-NachoSpigot-"0f4e14e"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:704) ~[NachoSpigot.jar:git-NachoSpigot-"0f4e14e"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1362) ~[NachoSpigot.jar:git-NachoSpigot-"0f4e14e"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1174) ~[NachoSpigot.jar:git-NachoSpigot-"0f4e14e"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:55) ~[NachoSpigot.jar:git-NachoSpigot-"0f4e14e"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[NachoSpigot.jar:git-NachoSpigot-"0f4e14e"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:6) ~[NachoSpigot.jar:git-NachoSpigot-"0f4e14e"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [NachoSpigot.jar:git-NachoSpigot-"0f4e14e"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [NachoSpigot.jar:git-NachoSpigot-"0f4e14e"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:398) [NachoSpigot.jar:git-NachoSpigot-"0f4e14e"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:723) [NachoSpigot.jar:git-NachoSpigot-"0f4e14e"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [NachoSpigot.jar:git-NachoSpigot-"0f4e14e"]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'org.bukkit.inventory.ItemStack org.bukkit.inventory.EntityEquipment.getItemInOffHand()'
        at me.arasple.mc.trmenu.taboolib.type.BukkitEquipment.getItem(BukkitEquipment.java:182) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.type.BukkitEquipment.getItems(BukkitEquipment.java:310) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.type.BukkitEquipment.getItems(BukkitEquipment.java:297) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.command.impl.CommandItem$command$1$1$2.invoke(CommandItem.kt:47) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.command.impl.CommandItem$command$1$1$2.invoke(CommandItem.kt:41) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandExecutor.exec(CommandBuilder.kt:185) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:95) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:87) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandBase.execute(CommandBuilder.kt:108) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandRegisterKt$command$1.execute(CommandRegister.kt:23) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitCommand$registerCommand$1.invoke$lambda-0(BukkitCommand.kt:69) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[NachoSpigot.jar:git-NachoSpigot-"0f4e14e"]
        ... 15 more
```

### ⚙ 配置文件

```
无
```

**Comment by 157946a** [comment]
尝试使用最新构建
