### ISSUE TITLE
[问题]: TrMenu 在低版本使用数字 Id (?) 保存菜单自动重载菜单 Icon 时出现 NPE 报错

### ISSUE THREAD

**Issue by Yurinann** [InsinuateProjects/TrMenu#166]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2022-03-17 09:12:04)

| Server OS: Windows Server 2019 amd64 10.0
| Server software: git-NachoSpigot-"0f4e14e" (MC: 1.8.8) (1.8.8-R0.2-SNAPSHOT)
| Java version: 17.0.2

| TrMenu: 3.1.9
Installed Plugins: 
· Citizens - 2.0.29-SNAPSHOT (build 2501) (0 KB)
· GadgetsMenu - 5.1.4 (0 KB)
· LuckPerms - 5.4.9 (0 KB)
· PlaceholderAPI - 2.11.1 (0 KB)
· PlayerBalancerAddon - 2.3.2-SNAPSHOT (0 KB)
· PlayerPoints - 3.2.1 (0 KB)
· ProtocolLib - 4.8.0 (0 KB)
· SuperLobby - 4.3.8 (0 KB)
· TAB-Bridge - 2.0.0 (0 KB)
· TrMenu - 3.1.9 (0 KB)
· UserPrefix - 2.4.3 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· ViaVersion - 4.2.1 (0 KB)
· momojs - 1.0.3 (0 KB)
```

### 🔍 详细的描述

```
1. Ctrl + S
2. 报错 ( Icon 能够正常显示 )
```

### 🗄 服务端日志

```
[09:08:08 WARN]: java.lang.NullPointerException
[09:08:08 WARN]:        at me.arasple.mc.trmenu.module.display.texture.Texture$Companion.parseMaterial(Texture.kt:155)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.module.display.texture.Texture$Companion.access$parseMaterial(Texture.kt:73)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.module.display.texture.Texture.generate(Texture.kt:40)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.api.menu.IItem$DefaultImpls.generate(IItem.kt:22)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.module.display.item.Item.generate(Item.kt:16)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.module.display.item.Item.build(Item.kt:39)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.module.display.item.Item.build$default(Item.kt:34)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.module.display.item.Item.get(Item.kt:31)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.module.display.icon.Icon.settingItem(Icon.kt:80)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.module.display.icon.Icon.filter(Icon.kt:156)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.module.display.icon.Icon.onRefresh(Icon.kt:85)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.module.display.Menu.loadIcon(Menu.kt:155)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.module.display.Menu.open(Menu.kt:90)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.module.display.Menu.open$default(Menu.kt:48)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.module.conf.Loader$listen$1$1.invoke(Loader.kt:154)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.module.conf.Loader$listen$1$1.invoke(Loader.kt:153)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.module.display.Menu$forSessions$2.invoke(Menu.kt:191)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.module.display.Menu$forSessions$2.invoke(Menu.kt:191)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.module.display.Menu.forViewers(Menu.kt:236)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.module.display.Menu.forSessions(Menu.kt:191)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.module.conf.Loader$listen$1.invoke(Loader.kt:153)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.module.conf.Loader$listen$1.invoke(Loader.kt:125)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.util.file.FileListener.listener$lambda-0(FileListener.kt:20)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.taboolib.common5.FileWatcher.lambda$addSimpleListener$2(FileWatcher.java:66)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.taboolib.common5.FileWatcher.lambda$null$0(FileWatcher.java:47)
[09:08:08 WARN]:        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
[09:08:08 WARN]:        at me.arasple.mc.trmenu.taboolib.common5.FileWatcher.lambda$new$1(FileWatcher.java:42)
[09:08:08 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[09:08:08 WARN]:        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[09:08:08 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[09:08:08 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[09:08:08 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[09:08:08 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### ⚙ 配置文件

```
  'A':
    display:
      material: 355
      name: '&c起床战争 &7(&fBedWars&7)'
      lore:
        - '&8团队协作/竞技'
        - ''
        - '&f与队友保护我方床'
        - '&f同时破坏其他队伍床'
        - '&f与你的队友并肩合作并击杀敌人!'
        - ''
        - '▪ &6&l点击连接'
        - '%pb_pc_bedwars% 名玩家正在进行游玩中！'
    actions:
      all: 
       - 'close'
```

**Comment by 157946a** [comment]
将配置全文上传
