### ISSUE TITLE
[问题]: 

### ISSUE THREAD

**Issue by Hdm980129** [InsinuateProjects/TrMenu#171]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2022-03-24 16:09:16)

  | Server OS: Windows 10 amd64
  | Server software: git-Purpur-1598 (MC: 1.18.2) (1.18.2-R0.1-SNAPSHOT)
  | Java version: 17.0.1

  | TrMenu: 3.1.9
Installed Plugins:
无法填写，指令不能使用
```

### 🔍 详细的描述

```
1. trmenu指令除了help其他全部不能使用包括/trmenu list  /trmenu debug dump 等，都提示Incorrect argument for command
![QQ图片20220324161227](https://user-images.githubusercontent.com/36358015/159872114-8a6df4c6-2174-4425-85b2-fa9a6011a044.png)

2. 菜单每次重启服务器后只能打开一次并且所有东西都可以拿出来但不能使用会自动消失
```

### 🗄 服务端日志

```
[16:03:12] [pool-42-thread-1/WARN]: java.lang.NoSuchFieldException: channel at class net.minecraft.server.network.PlayerConnection
[16:03:12] [pool-42-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.common.reflect.Reflex.get(Reflex.kt:60)
[16:03:12] [pool-42-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.common.reflect.Reflex.read(Reflex.kt:25)
[16:03:12] [pool-42-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.common.reflect.Reflex$Companion.getProperty(Reflex.kt:128)
[16:03:12] [pool-42-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.common.reflect.Reflex$Companion.getProperty$default(Reflex.kt:124)
[16:03:12] [pool-42-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.module.nms.ChannelExecutor.getPlayerChannel(ChannelExecutor.kt:27)
[16:03:12] [pool-42-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.module.nms.ChannelExecutor.addPlayerChannel$lambda-0(ChannelExecutor.kt:36)
[16:03:12] [pool-42-thread-1/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[16:03:12] [pool-42-thread-1/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[16:03:12] [pool-42-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:03:12] [pool-42-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:03:12] [pool-42-thread-1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

[16:17:26] [pool-43-thread-1/WARN]: java.lang.NoSuchFieldException: channel at class net.minecraft.server.network.PlayerConnection
[16:17:26] [pool-43-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.common.reflect.Reflex.get(Reflex.kt:60)
[16:17:26] [pool-43-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.common.reflect.Reflex.read(Reflex.kt:25)
[16:17:26] [pool-43-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.common.reflect.Reflex$Companion.getProperty(Reflex.kt:128)
[16:17:26] [pool-43-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.common.reflect.Reflex$Companion.getProperty$default(Reflex.kt:124)
[16:17:26] [pool-43-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.module.nms.ChannelExecutor.getPlayerChannel(ChannelExecutor.kt:27)
[16:17:26] [pool-43-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.module.nms.ChannelExecutor.removePlayerChannel$lambda-1(ChannelExecutor.kt:46)
[16:17:26] [pool-43-thread-1/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[16:17:26] [pool-43-thread-1/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[16:17:26] [pool-43-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:17:26] [pool-43-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:17:26] [pool-43-thread-1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:17:26] [pool-23-thread-1/WARN]: java.io.IOException: 另一个程序已锁定文件的一部分，进程无法访问。
[16:17:26] [pool-23-thread-1/WARN]: 	at java.base/java.io.FileInputStream.read0(Native Method)
[16:17:26] [pool-23-thread-1/WARN]: 	at java.base/java.io.FileInputStream.read(FileInputStream.java:228)
[16:17:26] [pool-23-thread-1/WARN]: 	at java.base/java.io.DataInputStream.readChar(DataInputStream.java:368)
[16:17:26] [pool-23-thread-1/WARN]: 	at [F][异步创世神]FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-134.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.readSize(DiskOptimizedClipboard.java:150)
[16:17:26] [pool-23-thread-1/WARN]: 	at [F][异步创世神]FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-134.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.<init>(DiskOptimizedClipboard.java:131)
[16:17:26] [pool-23-thread-1/WARN]: 	at [F][异步创世神]FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-134.jar//com.sk89q.worldedit.entity.Player.loadClipboardFromDisk(Player.java:466)
[16:17:26] [pool-23-thread-1/WARN]: 	at [F][异步创世神]FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-134.jar//com.sk89q.worldedit.bukkit.BukkitPlayer.<init>(BukkitPlayer.java:113)
[16:17:26] [pool-23-thread-1/WARN]: 	at [F][异步创世神]FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-134.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.wrapPlayer(WorldEditPlugin.java:558)
[16:17:26] [pool-23-thread-1/WARN]: 	at [F][异步创世神]FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-134.jar//com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:145)
[16:17:26] [pool-23-thread-1/WARN]: 	at com.griefdefender.internal.provider.GDWorldEditProvider.revertVisuals(GDWorldEditProvider.java:270)
[16:17:26] [pool-23-thread-1/WARN]: 	at com.griefdefender.listener.PlayerEventHandler.lambda$onPlayerQuit$0(PlayerEventHandler.java:243)
[16:17:26] [pool-23-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:17:26] [pool-23-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:17:26] [pool-23-thread-1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:17:26] [pool-23-thread-1/WARN]: java.lang.RuntimeException: java.io.IOException: 另一个程序已锁定文件的一部分，进程无法访问。
[16:17:26] [pool-23-thread-1/WARN]: 	at [F][异步创世神]FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-134.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.readSize(DiskOptimizedClipboard.java:157)
[16:17:26] [pool-23-thread-1/WARN]: 	at [F][异步创世神]FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-134.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.<init>(DiskOptimizedClipboard.java:131)
[16:17:26] [pool-23-thread-1/WARN]: 	at [F][异步创世神]FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-134.jar//com.sk89q.worldedit.entity.Player.loadClipboardFromDisk(Player.java:466)
[16:17:26] [pool-23-thread-1/WARN]: 	at [F][异步创世神]FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-134.jar//com.sk89q.worldedit.bukkit.BukkitPlayer.<init>(BukkitPlayer.java:113)
[16:17:26] [pool-23-thread-1/WARN]: 	at [F][异步创世神]FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-134.jar//com.sk89q.worldedit.bukkit.WorldEditPlugin.wrapPlayer(WorldEditPlugin.java:558)
[16:17:26] [pool-23-thread-1/WARN]: 	at [F][异步创世神]FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-134.jar//com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:145)
[16:17:26] [pool-23-thread-1/WARN]: 	at com.griefdefender.internal.provider.GDWorldEditProvider.revertVisuals(GDWorldEditProvider.java:270)
[16:17:26] [pool-23-thread-1/WARN]: 	at com.griefdefender.listener.PlayerEventHandler.lambda$onPlayerQuit$0(PlayerEventHandler.java:243)
[16:17:26] [pool-23-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:17:26] [pool-23-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:17:26] [pool-23-thread-1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:17:26] [pool-23-thread-1/WARN]: Caused by: java.io.IOException: 另一个程序已锁定文件的一部分，进程无法访问。
[16:17:26] [pool-23-thread-1/WARN]: 	at java.base/java.io.FileInputStream.read0(Native Method)
[16:17:26] [pool-23-thread-1/WARN]: 	at java.base/java.io.FileInputStream.read(FileInputStream.java:228)
[16:17:26] [pool-23-thread-1/WARN]: 	at java.base/java.io.DataInputStream.readChar(DataInputStream.java:368)
[16:17:26] [pool-23-thread-1/WARN]: 	at [F][异步创世神]FastAsyncWorldEdit-Bukkit-2.1.1-SNAPSHOT-134.jar//com.fastasyncworldedit.core.extent.clipboard.DiskOptimizedClipboard.readSize(DiskOptimizedClipboard.java:150)
[16:17:26] [pool-23-thread-1/WARN]: 	... 10 more
```

### ⚙ 配置文件

```
无论是什么菜单都无法打开，包括插件自带的几个都无法打开都是重启后只能打开一次然后就不能打开了
```

**Comment by Score2** [comment]
建议你切换到paper环境来尝试复现该问题

**Comment by Hdm980129** [comment]
> 建议你切换到paper环境来尝试复现该问题

你好，尝试使用paper1.18.2 267 该问题依旧存在，打开任何菜单或者第二次尝试但无法打开的时候都是没有报错的
下面是我的服务端详细信息和相关启动时的报错以及完整日志文件也上传了
[Uploading latest.log…]()


服务端详细信息
TrMenu Dump Information (Date: 2022-03-25 19:17:47)

| Server OS: Windows Server 2019 amd64 10.0
| Server software: git-Paper-267 (MC: 1.18.2) (1.18.2-R0.1-SNAPSHOT)
| Java version: 17.0.1

| TrMenu: 3.1.9
Installed Plugins: 
· AdvancedChests - 23.0 (0 KB)
· Bank - 4.5.5-RELEASE (0 KB)
· BattlePass - 3.7.0 (0 KB)
· BetterFarming - 4.3.1 (0 KB)
· CMI - 9.1.3.1 (0 KB)
· CMIEInjector - 1.0.2.3 (0 KB)
· CMILib - 1.1.2.4 (0 KB)
· Chunky - 1.2.164 (0 KB)
· ChunkyBorder - 1.0.64 (0 KB)
· Citizens - 2.0.29-SNAPSHOT (build 2510) (0 KB)
· Constructor - 2.0.7 (0 KB)
· CoreProtect - 21.2 (0 KB)
· CrazyAuctionsPlus - 1.2.0.1 (0 KB)
· CustomSprays - 1.5 (0 KB)
· CutsceneStudio - 1.2.1 (0 KB)
· DailyShop - 3.7 (0 KB)
· Dantiao - EX-27 (0 KB)
· DisplayShops - 1.6.6 (0 KB)
· EasyBackup - 3.3.7 (0 KB)
· EasyBackupCore - 3.3.6 (0 KB)
· EpicCraftingsPlus - 7.5.2 (0 KB)
· FartherViewDistance - 9.1.2 (0 KB)
· FastAsyncWorldEdit - 2.1.1-SNAPSHOT-134;465c81d (0 KB)
· GCore - 8.36.0 (0 KB)
· GDHooks - 0.7-DEV (0 KB)
· Geekinvite - SNAPSHOT-1.02 (0 KB)
· GriefDefender - 2.1.3 (0 KB)
· HeadDatabase - 4.16.0 (0 KB)
· InteractionVisualizer - 1.17.2.5 (0 KB)
· Iris - 2.0.2-1.18.X (0 KB)
· ItemsAdder - 3.0.4 (0 KB)
· LibsDisguises - 10.0.28 (0 KB)
· LiteSignIn - 1.5.6 (0 KB)
· LiveRecorder - 1.6.3 (0 KB)
· LoneLibs - 1.0.18 (0 KB)
· LuckPerms - 5.4.13 (0 KB)
· MinePay - Alpha 2.6.15 (0 KB)
· ModelEngine - R2.5.0 (0 KB)
· MotionCaptureRewritten - 2.2.4 (0 KB)
· Multiverse-Core - 4.3.2-SNAPSHOT-b868 (0 KB)
· MyPet - 3.12 (0 KB)
· MysqlPlayerDataBridge - 4.2.0 (0 KB)
· MythicKeysPlugin - 1.4 (0 KB)
· MythicLib - 1.2 (0 KB)
· MythicMobs - 5.0.3-SNAPSHOT-b75d29a2 (0 KB)
· MythicMobsExtension - 1.739-SNAPSHOT (0 KB)
· Oraxen - 1.130.1 (0 KB)
· PlaceholderAPI - 2.11.1 (0 KB)
· PlayerPoints - 3.2.1 (0 KB)
· PluginManagerPlus - 1.5.7 (0 KB)
· ProMCCore - 1.0.3.8 (0 KB)
· ProSkillAPI - 1.1.7.16 (0 KB)
· ProtocolLib - 4.8.0-b547 (0 KB)
· PyroFishingPro - 4.6.6 (0 KB)
· PyroLib - 1.0.2 (0 KB)
· PyroMining - 4.3.7 (0 KB)
· QuestCreator - 6.36.0 (0 KB)
· RPGInventory - 1.6.6 (0 KB)
· RainbowsPro - 1.2.1 (0 KB)
· React - 6.655 (0 KB)
· RevoltCrates - 2.1.0-Beta (0 KB)
· SafariNet - 1.15.35-SNAPSHOT (0 KB)
· Stp - 1.0.1 (0 KB)
· TrMenu - 3.1.9 (0 KB)
· UltimateTimber - 2.3.2 (0 KB)
· UltraCustomizer - 1.9.4 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· VentureChat - 3.3.2 (0 KB)
· ViaBackwards - 4.2.1 (0 KB)
· ViaRewind - 2.0.2 (0 KB)
· ViaVersion - 4.2.1 (0 KB)
· VoidGen - 2.2.1 (0 KB)
· bloodmoon-advanced - 4.2.0 (0 KB)
· dynmap - 3.4-beta-2-761 (0 KB)
· mcMMO - 2.1.211 (0 KB)
· mcmmo-placeholders - 1.0-SNAPSHOT (0 KB)
· spark - 1.8.16 (0 KB)

相关报错日志
[19:17:35] [pool-42-thread-1/WARN]: java.lang.NoSuchFieldException: channel at class net.minecraft.server.network.PlayerConnection
[19:17:35] [pool-42-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.common.reflect.Reflex.get(Reflex.kt:60)
[19:17:35] [pool-42-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.common.reflect.Reflex.read(Reflex.kt:25)
[19:17:35] [pool-42-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.common.reflect.Reflex$Companion.getProperty(Reflex.kt:128)
[19:17:35] [pool-42-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.common.reflect.Reflex$Companion.getProperty$default(Reflex.kt:124)
[19:17:35] [pool-42-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.module.nms.ChannelExecutor.getPlayerChannel(ChannelExecutor.kt:27)
[19:17:35] [pool-42-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.module.nms.ChannelExecutor.addPlayerChannel$lambda-0(ChannelExecutor.kt:36)
[19:17:35] [pool-42-thread-1/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[19:17:35] [pool-42-thread-1/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[19:17:35] [pool-42-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:17:35] [pool-42-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:17:35] [pool-42-thread-1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

[19:17:47] [Server thread/INFO]: Alan issued server command: /trmenu debug dump
[19:18:51] [Server thread/INFO]: [MysqlPlayerDataBridge] Saving data and kicking all players...
[19:18:51] [Server thread/INFO]: Alan lost connection: Server is restarting please come back in 20 seconds.
[19:18:51] [pool-43-thread-1/WARN]: java.lang.NoSuchFieldException: channel at class net.minecraft.server.network.PlayerConnection
[19:18:51] [pool-43-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.common.reflect.Reflex.get(Reflex.kt:60)
[19:18:51] [pool-43-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.common.reflect.Reflex.read(Reflex.kt:25)
[19:18:51] [pool-43-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.common.reflect.Reflex$Companion.getProperty(Reflex.kt:128)
[19:18:51] [pool-43-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.common.reflect.Reflex$Companion.getProperty$default(Reflex.kt:124)
[19:18:51] [pool-43-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.module.nms.ChannelExecutor.getPlayerChannel(ChannelExecutor.kt:27)
[19:18:51] [pool-43-thread-1/WARN]: 	at TrMenu-3.1.9.jar//me.arasple.mc.trmenu.taboolib.module.nms.ChannelExecutor.removePlayerChannel$lambda-1(ChannelExecutor.kt:46)
[19:18:51] [pool-43-thread-1/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[19:18:51] [pool-43-thread-1/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[19:18:51] [pool-43-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:18:51] [pool-43-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:18:51] [pool-43-thread-1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Score2** [comment]
已了解到是与插件FartherViewDistance发生冲突，该插件将playerConnection.channel 字段名称进行了更改，导致依赖该字段的taboolib无法获取到该字段而出现该报错

**Comment by Hdm980129** [comment]
> 已了解到是与插件FartherViewDistance发生冲突，该插件将playerConnection.channel 字段名称进行了更改，导致依赖该字段的taboolib无法获取到该字段而出现该报错

好的感谢，那我暂时先删了FartherViewDistance等待更新了，感谢回复

**Comment by Score2** [comment]
已联系fvd作者，请等待他的修复

**Comment by Score2** [comment]
请更新到最新版fvd以解决该问题
