### ISSUE TITLE
[Bug]: PKIX path building failed

### ISSUE THREAD

**Issue by cheaterSK** [InsinuateProjects/TrMenu#176]
### 🚀 Have you tried the latest version

- [X] I have updated TrMenu to the latest version and the same bug is reproduced.

### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

```
I am unable to provide this, as plugin doesn't even start.
```

### 🔍 Detailed description

```
On server startup the plugin throws errors as shown in the attached log, the plugin doesn't even start, so I am unable to provide any more information/dump.
```

### 🗄 Server log

```
[04:02:26] [Server thread/WARN]: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:370)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:313)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:200)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2887)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2796)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1927)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[04:02:26] [Server thread/WARN]: 	at java.base/java.net.URL.openStream(URL.java:1161)
[04:02:26] [Server thread/WARN]: 	at TrMenu-3.1.10.jar//me.arasple.mc.trmenu.taboolib.common.env.RuntimeEnv.loadDependency(RuntimeEnv.java:179)
[04:02:26] [Server thread/WARN]: 	at TrMenu-3.1.10.jar//me.arasple.mc.trmenu.taboolib.common.env.RuntimeEnv.setup(RuntimeEnv.java:54)
[04:02:26] [Server thread/WARN]: 	at TrMenu-3.1.10.jar//me.arasple.mc.trmenu.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:117)
[04:02:26] [Server thread/WARN]: 	at TrMenu-3.1.10.jar//me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:34)
[04:02:26] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[04:02:26] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:467)
[04:02:26] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71)
[04:02:26] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153)
[04:02:26] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415)
[04:02:26] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323)
[04:02:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:417)
[04:02:26] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:288)
[04:02:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
[04:02:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[04:02:26] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[04:02:26] [Server thread/WARN]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:249)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
[04:02:26] [Server thread/WARN]: 	... 34 more
[04:02:26] [Server thread/WARN]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
[04:02:26] [Server thread/WARN]: 	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
[04:02:26] [Server thread/WARN]: 	... 39 more
[04:02:26] [Server thread/WARN]: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:370)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:313)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:200)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2887)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2796)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1927)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[04:02:26] [Server thread/WARN]: 	at java.base/java.net.URL.openStream(URL.java:1161)
[04:02:26] [Server thread/WARN]: 	at TrMenu-3.1.10.jar//me.arasple.mc.trmenu.taboolib.common.env.RuntimeEnv.loadDependency(RuntimeEnv.java:179)
[04:02:26] [Server thread/WARN]: 	at TrMenu-3.1.10.jar//me.arasple.mc.trmenu.taboolib.common.env.RuntimeEnv.setup(RuntimeEnv.java:54)
[04:02:26] [Server thread/WARN]: 	at TrMenu-3.1.10.jar//me.arasple.mc.trmenu.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:117)
[04:02:26] [Server thread/WARN]: 	at TrMenu-3.1.10.jar//me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:34)
[04:02:26] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[04:02:26] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:467)
[04:02:26] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71)
[04:02:26] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153)
[04:02:26] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415)
[04:02:26] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323)
[04:02:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:417)
[04:02:26] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:288)
[04:02:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
[04:02:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[04:02:26] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[04:02:26] [Server thread/WARN]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:249)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
[04:02:26] [Server thread/WARN]: 	... 34 more
[04:02:26] [Server thread/WARN]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
[04:02:26] [Server thread/WARN]: 	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
[04:02:26] [Server thread/WARN]: 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
[04:02:26] [Server thread/WARN]: 	... 39 more
[04:02:27] [Server thread/WARN]: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:370)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:313)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:200)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2887)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2796)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1927)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[04:02:27] [Server thread/WARN]: 	at java.base/java.net.URL.openStream(URL.java:1161)
[04:02:27] [Server thread/WARN]: 	at TrMenu-3.1.10.jar//me.arasple.mc.trmenu.taboolib.common.env.RuntimeEnv.loadDependency(RuntimeEnv.java:179)
[04:02:27] [Server thread/WARN]: 	at TrMenu-3.1.10.jar//me.arasple.mc.trmenu.taboolib.common.env.RuntimeEnv.setup(RuntimeEnv.java:54)
[04:02:27] [Server thread/WARN]: 	at TrMenu-3.1.10.jar//me.arasple.mc.trmenu.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:117)
[04:02:27] [Server thread/WARN]: 	at TrMenu-3.1.10.jar//me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:34)
[04:02:27] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[04:02:27] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:467)
[04:02:27] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71)
[04:02:27] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153)
[04:02:27] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415)
[04:02:27] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323)
[04:02:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:417)
[04:02:27] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:288)
[04:02:27] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
[04:02:27] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[04:02:27] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[04:02:27] [Server thread/WARN]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:249)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
[04:02:27] [Server thread/WARN]: 	... 34 more
[04:02:27] [Server thread/WARN]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
[04:02:27] [Server thread/WARN]: 	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
[04:02:27] [Server thread/WARN]: 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
[04:02:27] [Server thread/WARN]: 	... 39 more
```

### ⚙ Configurations

```
This issue is not related to configuration.
```

**Comment by 157946a** [comment]
try the latest build
