### ISSUE TITLE
[问题]: Plugin TrMenu v3.1.10 generated an exception while executing task 22543410

### ISSUE THREAD

**Issue by Dreeam-qwq** [InsinuateProjects/TrMenu#180]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2022-04-28 18:55:42)

| Server OS: Windows Server 2016 amd64 10.0
| Server software: git-Pufferfish-47 (MC: 1.18.1) (1.18.1-R0.1-SNAPSHOT)
| Java version: 17.0.2

| TrMenu: 3.1.10
Installed Plugins: 
· AdvancedHelp - 1.12.7 (0 KB)
· AdvancedPlHide - 2.2 (0 KB)
· BookNews - 6.2 (0 KB)
· Bookshelf - 3.0.8.7 (0 KB)
· CoreProtect - 21.2 (0 KB)
· EastLandLog4jFixer - 1.0.4 (0 KB)
· Essentials - 2.20.0-dev+5-d891268 (0 KB)
· GoldenDupes - 1.4.7 (0 KB)
· InteractionVisualizer - 1.17.2.6 (0 KB)
· LagAssist - 2.28.0 (0 KB)
· LoginLocationFix - 0.5 (0 KB)
· LuckPerms - 5.4.18 (0 KB)
· Mczf - 1.0.0-b22 (0 KB)
· NoCheatPlus - 3.17-SNAPSHOT-Updated-b137 (0 KB)
· OpenInv - 4.1.9 (0 KB)
· Panilla - 1.7.6 (0 KB)
· PlaceholderAPI - 2.11.2-DEV-152 (0 KB)
· Plan - 5.4 build 1633 (0 KB)
· PlugManX - 2.3.0 (0 KB)
· ProtocolLib - 5.0.0-SNAPSHOT-b124 (0 KB)
· RandomSpawnPlus - 3.4.4 (0 KB)
· RoseStacker - 1.4.6 (0 KB)
· SimpleLay - 1.1.1 (0 KB)
· SkinsRestorer - 14.2.0-SNAPSHOT (0 KB)
· Surf - 3.2.5 (0 KB)
· TAB - 3.1.1 (0 KB)
· TrMenu - 3.1.10 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· ViaBackwards - 4.3.0-22w16b-SNAPSHOT (0 KB)
· ViaRewind - 2.0.3-SNAPSHOT (0 KB)
· ViaVersion - 4.3.0-22w16b-SNAPSHOT (0 KB)
· sleep-most - 4.15.1 (0 KB)
· spark - 1.8.22 (0 KB)
```

### 🔍 详细的描述

```
1. 安装Trmenu最新版
2. 玩家进服
3. 在控制台看到报错
```

### 🗄 服务端日志

```
[18:51:02 INFO]: [+] Dreeam
[18:51:02 INFO]: Dreeam[<ip address withheld>] logged in with entity id 140381 at ([world]coord)
[18:51:02 WARN]: [TrMenu] Plugin TrMenu v3.1.10 generated an exception while executing task 22543410
java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.resolve(String)" because "this.skinsFolder" is null
        at net.skinsrestorer.shared.storage.SkinStorage.getSkinData(SkinStorage.java:292) ~[[正版皮肤]SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.storage.SkinStorage.getSkinData(SkinStorage.java:268) ~[[正版皮肤]SkinsRestorer.jar:?]
        at net.skinsrestorer.api.SkinsRestorerAPI.getSkinData(SkinsRestorerAPI.java:114) ~[[正 版皮肤]SkinsRestorer.jar:?]
        at me.arasple.mc.trmenu.module.internal.hook.impl.HookSkinsRestorer.getPlayerSkinTexture(HookSkinsRestorer.kt:26) ~[[Tr-菜单]TrMenu-3.1.10.jar:?]
        at me.arasple.mc.trmenu.util.bukkit.Heads.playerTexture(Heads.kt:77) ~[[Tr-菜单]TrMenu-3.1.10.jar:?]
        at me.arasple.mc.trmenu.util.bukkit.Heads.getPlayerHead(Heads.kt:47) ~[[Tr-菜单]TrMenu-3.1.10.jar:?]
        at me.arasple.mc.trmenu.module.internal.listener.ListenerJoin$onJoin$1.invoke(ListenerJoin.kt:21) ~[[Tr-菜单]TrMenu-3.1.10.jar:?]
        at me.arasple.mc.trmenu.module.internal.listener.ListenerJoin$onJoin$1.invoke(ListenerJoin.kt:19) ~[[Tr-菜单]TrMenu-3.1.10.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$6.run(BukkitExecutor.kt:89) ~[[Tr-菜单]TrMenu-3.1.10.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### ⚙ 配置文件

```
默认配置
```

**Comment by 157946a** [comment]
我不知道你哪来的14.2.0版本的skinsrestorer,但你先使用4.1.15看看https://www.spigotmc.org/resources/skinsrestorer.2124/

**Comment by Dreeam-qwq** [comment]
> 

用的是codemc构建站的最新dev版
https://ci.codemc.io/view/All/job/SkinsRestorer/job/SkinsRestorerX-DEV/

**Comment by 157946a** [comment]
但你先用4.1.15看看https://www.spigotmc.org/resources/skinsrestorer.2124/

**Comment by 157946a** [comment]
使用最新版本
