### ISSUE TITLE
[Bug]:  TrMenu v3.1.10报错 偶尔跳出来报错

### ISSUE THREAD

**Issue by yuankun1** [InsinuateProjects/TrMenu#187]
### 🚀 Have you tried the latest version

- [X] I have updated TrMenu to the latest version and the same bug is reproduced.

### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

https://paste.helpch.at/xilaqorece

### 🔍 Detailed description

```
1. 
2. ...
3. ...
```

### 🗄 Server log

[21:41:51 ERROR]: Could not pass event PacketReceiveEvent to TrMenu v3.1.10
 java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_291]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_291]
        at me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [SimplePluginManager.class:?]
        at me.arasple.mc.trmenu.taboolib.platform.type.BukkitProxyEvent.call(BukkitProxyEvent.kt:39) [%5BT%5D%5B功能菜单%5DTrMenu-3.1.10.jar:?]
        at me.arasple.mc.trmenu.taboolib.module.nms.ChannelHandler.channelRead(ChannelHandler.kt:24) [%5BT%5D%5B功能菜单%5DTrMenu-3.1.10.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [ChannelInboundHandlerAdapter.class:4.1.24.Final]
        at me.arasple.mc.trchat.taboolib.module.nms.ChannelHandler.channelRead(ChannelHandler.kt:25) [%5BT%5D%5B聊天%5DTrChat-2.0.0-PRE-6.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:280) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:70) [NetworkDispatcher.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [SimpleChannelInboundHandler.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288) [ByteToMessageDecoder.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [ByteToMessageDecoder.class:4.1.24.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [ByteToMessageDecoder.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292) [%5BP%5D%5B前置变量%5DProtocolLib.jar:4.8.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [ByteToMessageDecoder.class:4.1.24.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [ByteToMessageDecoder.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [ByteToMessageDecoder.class:4.1.24.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [ByteToMessageDecoder.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [IdleStateHandler.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [DefaultChannelPipeline$HeadContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [AbstractChannelHandlerContext.class:4.1.24.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [DefaultChannelPipeline.class:4.1.24.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [AbstractNioByteChannel$NioByteUnsafe.class:4.1.24.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [NioEventLoop.class:4.1.24.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [NioEventLoop.class:4.1.24.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [NioEventLoop.class:4.1.24.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [NioEventLoop.class:4.1.24.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [SingleThreadEventExecutor$5.class:4.1.24.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 54
        at me.arasple.mc.trmenu.api.receptacle.vanilla.window.WindowReceptacle.refresh(WindowReceptacle.kt:71) ~[?:?]
        at me.arasple.mc.trmenu.api.receptacle.ReceptacleInteractEvent.refresh(ReceptacleInteractEvent.kt:18) ~[?:?]
        at me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1$cancelEvent$1.invoke(Layout.kt:82) ~[?:?]
        at me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1$cancelEvent$1.invoke(Layout.kt:80) ~[?:?]
        at me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2.invoke(Layout.kt:88) ~[?:?]
        at me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2.invoke(Layout.kt:78) ~[?:?]
        at me.arasple.mc.trmenu.api.receptacle.vanilla.window.WindowReceptacle.callEventClick(WindowReceptacle.kt:97) ~[?:?]
        at me.arasple.mc.trmenu.api.receptacle.vanilla.window.WindowListener.onPacket(WindowListener.kt:43) ~[?:?]
        ... 66 more

### ⚙ Configurations

```

```

**Comment by 157946a** [comment]
你是否使用了老廖的扩展插件
