### ISSUE TITLE
[问题]: Could not pass event PlayerInteractEvent to TrMenu v3.1.10 java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by katerina644** [InsinuateProjects/TrMenu#189]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

TrMenu Dump Information (Date: 2022-05-29 10:10:22)

| Server OS: Linux amd64 3.10.0-1160.el7.x86_64
| Server software: 1.16.5-6480230e (MC: 1.16.5) (1.16.5-R0.1-SNAPSHOT)
| Java version: 1.8.0_332

| TrMenu: 3.1.9
Installed Plugins: 
· 7yAPI - 1.1.4 (0 KB)
· 7yPay - 1.1.17 (0 KB)
· 7yPayReward - 1.1.13 (0 KB)
· Admin-GUI - 1.5.0 (0 KB)
· AdvancedAchievements - 6.2.1 (0 KB)
· AdvancedCleaner - 1.4 (0 KB)
· AtLite - 1.1-SNAPSHOT (0 KB)
· AuctionHouse - 2.2.3 (0 KB)
· BBSToper - 3.6.7 (0 KB)
· BanIt - 1.1.1 (0 KB)
· BlessingSkinSync - 1.7-SNAPSHOT (0 KB)
· BlockLocker - 1.10.4 (0 KB)
· CMI - 9.1.4.5 (0 KB)
· CMILib - 1.1.2.5 (0 KB)
· Citizens - 2.0.29-SNAPSHOT (build 2553) (0 KB)
· CitizensCMD - 2.6.3 (0 KB)
· ColorMOTD - 1.5.3 (0 KB)
· EasyGuiShop - 1.3.11 (0 KB)
· GoldenCrates - 3.11.0 (0 KB)
· GroupManager - 2.9 (Phoenix) (0 KB)
· HolographicDisplays - 2.4.9 (0 KB)
· JukeBox - 1.20.6 (0 KB)
· LiteInvitation - 1.4.7-SNAPSHOT (0 KB)
· LiteSignIn - 1.6.0 (0 KB)
· MiaoChat - 2.1.2 (0 KB)
· MultiLogin - 0.3.14 (0 KB)
· Multiverse-Core - 4.3.1-b861 (0 KB)
· NBTAPI - 2.9.1 (0 KB)
· NekoMaid - 0.2.5 (0 KB)
· NexEngine - 2.0.6 (0 KB)
· NoteBlockAPI - 1.6.1-SNAPSHOT (0 KB)
· PlaceholderAPI - 2.11.1 (0 KB)
· PlayerPoints - 3.2.3 (0 KB)
· PlayerTitle - 2.10.8 (0 KB)
· PlotSquared - 4.4.495 (0 KB)
· PlugMan - 2.1.7 (0 KB)
· ProtocolLib - 4.8.0 (0 KB)
· Residence - 4.9.3.4 (0 KB)
· SimplePassiveMode - 2.0 (0 KB)
· SkinsRestorer - 14.1.15 (0 KB)
· TempFly - 3.1.7 (0 KB)
· TitleManager - 2.3.3 (0 KB)
· TrMenu - 3.1.9 (0 KB)
· Uniporter - 1.3.3-SNAPSHOT (0 KB)
· Vault - 1.7.3-CMI (0 KB)
· VipSystem - 4.13 (0 KB)
· WorldEdit - 7.2.10+1742f98 (0 KB)
· YukiNoaAPI - 1.0.0 (0 KB)
· eBackup - 1.3.1 (0 KB)

### 🔍 详细的描述

```
1. 服务端后台不定时出现报错
2. 暂时无法稳定复现
```

### 🗄 服务端日志

```
[08:52:44] [Server thread/ERROR] [Minecraft]: Could not pass event PlayerInteractEvent to TrMenu v3.1.10
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor306.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
	at me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:39) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
	at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:38) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:593) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:578) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:431) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:398) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:394) ~[forge:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_175087_a(ServerPlayNetHandler.java:1822) ~[?:?]
	at net.minecraft.network.play.client.CAnimateHandPacket.func_148833_a(SourceFile:31) ~[?:?]
	at net.minecraft.network.play.client.CAnimateHandPacket.func_148833_a(SourceFile:9) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:872) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:169) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:849) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:835) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:767) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332]
Caused by: java.lang.NullPointerException
```

### ⚙ 配置文件

```

```

**Comment by 157946a** [comment]
使用最新版本再提,核心是什么

**Comment by katerina644** [comment]
已经使用了最新构建的插件,,核心是CatServer-1.16.5-6480230e-server.jar,同样为最新版本cat核心

**Comment by katerina644** [comment]
> 使用最新版本再提,核心是什么
已经使用了最新构建的插件,服务器核心是CatServer-1.16.5-6480230e-server.jar,同样为最新版本cat核心

**Comment by 157946a** [comment]
最新版本是3.1.10,而不是3.1.9,不要以Release为准

**Comment by katerina644** [comment]
> 最新版本是3.1.10,而不是3.1.9,不要以Release为准

我是因为3.1.10有问题才换的3.1.9，不过可以确定报错是一样的，服务器上只有trmenu换成了3.1.9，其他插件都没有改动

**Comment by katerina644** [comment]
这一点可以看报错日志，报错是3.1.10版本

**Comment by katerina644** [comment]
> 这一点可以看报错日志，报错是3.1.10版本

如果需要的话我可以明天提供日志，现在服务器里面人比较多，不太方便加载3.1.10导出日志

**Comment by 157946a** [comment]
这个问题是出自交互事件,你说你服务器里有人,并且人数较多,并且是forge核心,有可能是因为绑定部分的物品,你检查配置的绑定选项里的物品绑定,排查是否是绑定物品的问题

**Comment by katerina644** [comment]
> 这个问题是出自交互事件,你说你服务器里有人,并且人数较多,并且是forge核心,有可能是因为绑定部分的物品,你检查配置的绑定选项里的物品绑定,排查是否是绑定物品的问题

检查了一遍菜单，并没有菜单绑定到物品

**Comment by 157946a** [comment]
等待维护者回复

**Comment by 157946a** [comment]
最新版本是否还会出现

**Comment by katerina644** [comment]
啊这，服务器已经换别的菜单插件了=.=
