### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MuMuMuCODE** [InsinuateProjects/TrMenu#198]
### 🚀 Have you tried the latest version

- [X] I have updated TrMenu to the latest version and the same bug is reproduced.

### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

```
TrMenu Dump Information (Date: xxxx-xx-xx xx:xx:xx)

  | Server OS: 2019server
  | Java version: Java18
  | TabooLib: 最新
  | TrMenu: 3.1.12


### 🔍 Detailed description


1. 无法调用skin的API ，应该是无法获得头颅信息


### 🗄 Server log

[16:57:13 WARN]: [TrMenu] Plugin TrMenu v3.1.12 generated an exception while executing task 41722
java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.resolve(String)" because "this.skinsFolder" is null
        at net.skinsrestorer.shared.storage.SkinStorage.getSkinData(SkinStorage.java:292) ~[SkinsRestorer14.2.1.jar:?]
        at net.skinsrestorer.shared.storage.SkinStorage.getSkinData(SkinStorage.java:268) ~[SkinsRestorer14.2.1.jar:?]
        at net.skinsrestorer.api.SkinsRestorerAPI.getSkinData(SkinsRestorerAPI.java:114) ~[SkinsRestorer14.2.1.jar:?]
        at me.arasple.mc.trmenu.module.internal.hook.impl.HookSkinsRestorer.getPlayerSkinTexture(HookSkinsRestorer.kt:26) ~[TrMenu-3.1.12.jar:?]
        at me.arasple.mc.trmenu.util.bukkit.Heads.playerTexture(Heads.kt:77) ~[TrMenu-3.1.12.jar:?]
        at me.arasple.mc.trmenu.util.bukkit.Heads.getPlayerHead(Heads.kt:47) ~[TrMenu-3.1.12.jar:?]
        at me.arasple.mc.trmenu.module.internal.listener.ListenerJoin$onJoin$1.invoke(ListenerJoin.kt:21) ~[TrMenu-3.1.12.jar:?]
        at me.arasple.mc.trmenu.module.internal.listener.ListenerJoin$onJoin$1.invoke(ListenerJoin.kt:19) ~[TrMenu-3.1.12.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$6.run(BukkitExecutor.kt:89) ~[TrMenu-3.1.12.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### ⚙ Configurations

```

```

**Comment by 157946a** [comment]
更新最新版本
