### ISSUE TITLE
[问题]: TrMenu对于SkinRestorer的Bungee模式获取不正常

### ISSUE THREAD

**Issue by SnivyJ** [InsinuateProjects/TrMenu#199]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

TrMenu Dump Information (Date: 2022-07-01 20:28:05)

| Server OS: Windows 10 amd64 10.0
| Server software: git-Paper-33 (MC: 1.19) (1.19-R0.1-SNAPSHOT)
| Java version: 17.0.1

| TrMenu: 3.1.12
Installed Plugins: 
· AdvancedCleaner - 1.4 (0 KB)
· BungeeTabListPlus - 3.5.0 (0 KB)
· CustomPlaceholder - 1.0 (0 KB)
· DecentHolograms - 2.4.2 (0 KB)
· DeluxeHub - 3.5.2 (0 KB)
· Dongmuleather - 1.0-SNAPSHOT (0 KB)
· EpicRename - 3.10.2 (0 KB)
· Essentials - 2.19.5-dev+22-9c5536b (0 KB)
· EssentialsProtect - 2.19.5-dev+22-9c5536b (0 KB)
· ExcellentEnchants - 3.2.2 (0 KB)
· GSit - 1.1.0 (0 KB)
· GeekTicket - 2.01 (0 KB)
· HuskHomes - 2.11.2 (0 KB)
· HuskHomesGUI - 1.2.3 (0 KB)
· Images - 2.2.6 (0 KB)
· KeepInventory - 1.3-SNAPSHOT (0 KB)
· LuckPerms - 5.4.30 (0 KB)
· Multiverse-Core - 4.3.1-b861 (0 KB)
· NexEngine - 2.2.0 build-18/06/2022 (0 KB)
· PlaceholderAPI - 2.11.1 (0 KB)
· PlayerPoints - 3.2.4 (0 KB)
· PlayerWarps - 6.17.3 (0 KB)
· PlugMan - 2.2.5 (0 KB)
· Prism - 2.1.7-6 (0 KB)
· ProtectItemFrame - 1.0 (0 KB)
· ProtocolLib - 5.0.0-SNAPSHOT-b560 (0 KB)
· SbPlaceholder - 1.0-SNAPSHOT (0 KB)
· SkinsRestorer - 14.2.1 (0 KB)
· TrChat - 2.0.0-PRE-10 (0 KB)
· TrMenu - 3.1.12 (0 KB)
· TreeFeller - 1.16.2 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· ViaVersion - 4.3.1 (0 KB)
· WTF - 1.2.0 (0 KB)
· XConomy - 2.18.12 (0 KB)
· spark - 1.7.2 (0 KB)

### 🔍 详细的描述

玩家进入服务器弹出task 70报错
在菜单拥有material: 'head:%player_name%'时弹出相关报错，设置为头颅的图标无法加载
服务器的SkinsRestorer使用Bungee Mode

### 🗄 服务端日志

```
[19:47:36 WARN]: [TrMenu] Plugin TrMenu v3.1.12 generated an exception while executing task 70
java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.resolve(String)" because "this.skinsFolder" is null
        at net.skinsrestorer.shared.storage.SkinStorage.getSkinData(SkinStorage.java:292) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.storage.SkinStorage.getSkinData(SkinStorage.java:268) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.api.SkinsRestorerAPI.getSkinData(SkinsRestorerAPI.java:114) ~[SkinsRestorer.jar:?]
        at me.arasple.mc.trmenu.module.internal.hook.impl.HookSkinsRestorer.getPlayerSkinTexture(HookSkinsRestorer.kt:26) ~[TrMenu-3.1.12.jar:?]
        at me.arasple.mc.trmenu.util.bukkit.Heads.playerTexture(Heads.kt:77) ~[TrMenu-3.1.12.jar:?]
        at me.arasple.mc.trmenu.util.bukkit.Heads.getPlayerHead(Heads.kt:47) ~[TrMenu-3.1.12.jar:?]
        at me.arasple.mc.trmenu.module.internal.listener.ListenerJoin$onJoin$1.invoke(ListenerJoin.kt:21) ~[TrMenu-3.1.12.jar:?]
        at me.arasple.mc.trmenu.module.internal.listener.ListenerJoin$onJoin$1.invoke(ListenerJoin.kt:19) ~[TrMenu-3.1.12.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$6.run(BukkitExecutor.kt:89) ~[TrMenu-3.1.12.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-33]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.jar:git-Paper-33]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
```
[20:19:39 INFO]: Dragon_AJiaoCat issued server command: /menus
[20:19:39 WARN]: java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.resolve(String)" because "this.skinsFolder" is null
[20:19:39 WARN]:        at SkinsRestorer.jar//net.skinsrestorer.shared.storage.SkinStorage.getSkinData(SkinStorage.java:292)
[20:19:39 WARN]:        at SkinsRestorer.jar//net.skinsrestorer.shared.storage.SkinStorage.getSkinData(SkinStorage.java:268)
[20:19:39 WARN]:        at SkinsRestorer.jar//net.skinsrestorer.api.SkinsRestorerAPI.getSkinData(SkinsRestorerAPI.java:114)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.module.internal.hook.impl.HookSkinsRestorer.getPlayerSkinTexture(HookSkinsRestorer.kt:26)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.util.bukkit.Heads.playerTexture(Heads.kt:77)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.util.bukkit.Heads.getPlayerHead(Heads.kt:47)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.util.bukkit.Heads.getHead(Heads.kt:40)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.module.display.texture.Texture.generate(Texture.kt:41)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.api.menu.IItem$DefaultImpls.generate(IItem.kt:22)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.module.display.item.Item.generate(Item.kt:16)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.module.display.item.Item.build(Item.kt:39)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.module.display.item.Item.build$default(Item.kt:34)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.module.display.item.Item.get(Item.kt:31)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.module.display.icon.Icon.settingItem(Icon.kt:80)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.module.display.icon.Icon.filter(Icon.kt:156)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.module.display.icon.Icon.onRefresh(Icon.kt:85)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.module.display.Menu.loadIcon(Menu.kt:155)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.module.display.Menu.open(Menu.kt:90)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.api.action.impl.menu.Open.onExecute(Open.kt:30)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.api.action.base.ActionBase$Option.evalPlayers(ActionBase.kt:115)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.api.action.base.ActionEntry.execute(ActionEntry.kt:31)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.api.action.ActionHandle.runAction(ActionHandle.kt:92)[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.api.reaction.Reactions.eval(Reactions.kt:16)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.module.internal.service.RegisterCommands$load$2$2$2.invoke(RegisterCommands.kt:70)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.module.internal.service.RegisterCommands$load$2$2$2.invoke(RegisterCommands.kt:67)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandExecutor.exec(CommandBuilder.kt:185)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandBase.execute(CommandBuilder.kt:59)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.taboolib.common.platform.command.CommandRegisterKt$command$1.execute(CommandRegister.kt:23)
[20:19:39 WARN]:        at TrMenu-3.1.12.jar//me.arasple.mc.trmenu.taboolib.platform.BukkitCommand$registerCommand$1.invoke$lambda-0(BukkitCommand.kt:69)
[20:19:39 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[20:19:39 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[20:19:39 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:907)
[20:19:39 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2376)
[20:19:39 WARN]:        at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2289)
[20:19:39 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.chat(CraftPlayer.java:676)
[20:19:39 WARN]:        at WTF.jar//net.zerodream.wtf.runCommand(wtf.java:111)
[20:19:39 WARN]:        at WTF.jar//net.zerodream.wtf.onPlayerSwapHandItems(wtf.java:64)
[20:19:39 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor92.execute(Unknown Source)
[20:19:39 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[20:19:39 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[20:19:39 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:19:39 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664)
[20:19:39 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1744)
[20:19:39 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:42)
[20:19:39 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:15)
[20:19:39 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[20:19:39 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:19:39 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[20:19:39 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[20:19:39 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1358)
[20:19:39 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
[20:19:39 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[20:19:39 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1335)
[20:19:39 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1328)
[20:19:39 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[20:19:39 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1306)
[20:19:39 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1191)
[20:19:39 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
[20:19:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[20:19:39 INFO]: ICON: P
```

### ⚙ 配置文件

```
  P:
    display:
      material: 'head:%player_name%'
      name: '&2&l玩家信息'
```

**Comment by Score2** [comment]
暂时无法从trmenu方面定位问题，根据报错是skin restorer的皮肤文件夹空指针导致获取皮肤失败？

**Comment by SnivyJ** [comment]
Bungee模式下的SkinRestorer在Spigot端下面的文件夹是空的 ，仅有一个(README) Use bungee config for settings! (README)的文件在plugins\SkinsRestorer

**Comment by Dirt233** [comment]
子服不要装skins，装了无效
