### ISSUE TITLE
[问题]: 1.12.2paper无法使用最新构建

### ISSUE THREAD

**Issue by Dirt233** [InsinuateProjects/TrMenu#200]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

插件无法正常启动，故无法提供

### 🔍 详细的描述

启动报错
类库加载完报错

[20:09:45 INFO]: This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[20:09:45 INFO]: Previous version: git-Paper-1618 (MC: 1.12.2)
Paper如上所示

[20:05:16 ERROR]: Could not load 'plugins\TrMenu.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.InternalError: Malformed class name
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.InternalError: Malformed class name
        at java.lang.Class.getSimpleName(Unknown Source) ~[?:1.8.0_301]
        at me.arasple.mc.trmenu.taboolib.common.io.Project1Kt.getInstance(Project1.kt:42) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.inject.RuntimeInjector.inject(RuntimeInjector.java:87) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.inject.RuntimeInjector.injectAll(RuntimeInjector.java:65) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:126) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:37) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_301]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_301]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1620]
        ... 6 more

### 🗄 服务端日志

```
[20:05:16 ERROR]: Could not load 'plugins\TrMenu.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.InternalError: Malformed class name
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.InternalError: Malformed class name
        at java.lang.Class.getSimpleName(Unknown Source) ~[?:1.8.0_301]
        at me.arasple.mc.trmenu.taboolib.common.io.Project1Kt.getInstance(Project1.kt:42) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.inject.RuntimeInjector.inject(RuntimeInjector.java:87) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.inject.RuntimeInjector.injectAll(RuntimeInjector.java:65) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:126) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:37) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_301]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_301]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1620]
        ... 6 more
```

### ⚙ 配置文件

```

```

**Comment by 157946a** [comment]
更换至Java11即可
