### ISSUE TITLE
[问题]: Spigot服务端 spigot.yml BungeeCord 选项影响TrMenu API利用问题

### ISSUE THREAD

**Issue by NoobKing666** [InsinuateProjects/TrMenu#203]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2022-07-19 13:02:15)

| Server OS: Windows 10 amd64 10.0
| Server software: git-Spigot-21fe707-741a1bd (MC: 1.8.8) (1.8.8-R0.1-SNAPSHOT)
| Java version: 1.8.0_241

| TrMenu: 3.1.10
Installed Plugins: 
· AsyncKeepAlive - 1.1 (0 KB)
· BunKai - 1.0 (0 KB)
· CMILib - 1.2.1.2 (0 KB)
· Citizens - 2.0.29-SNAPSHOT (build 2464) (0 KB)
· CustomBaoShi - 1.2 (0 KB)
· Forge - 1.0 (0 KB)
· LevelCtrlU - 1.0 (0 KB)
· MinePrefix - 1.0 (0 KB)
· MobHealth - 10.0.1 (0 KB)
· PlaceholderAPI - 2.11.2 (0 KB)
· ProtocolLib - 4.8.0 (0 KB)
· Residence - 5.0.1.7 (0 KB)
· SkinsRestorer - 14.2.1 (0 KB)
· TrMenu - 3.1.10 (0 KB)
· UltraEconomy - 2.0.9 (0 KB)
· UltraPermissions - 5.2.3 (0 KB)
· UltraPunishments - 1.9.9 (0 KB)
· UltraScoreboards - 1.1.5 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· WarpSystem - 5.1.2-free (0 KB)
· WelcomeTitle - 1.0 (0 KB)
```

### 🔍 详细的描述

```
1. 当 spigot.yml BungeeCord: true 时 SkinsRestorer 生成BC专属的配置文件TrMenu报错
2. 当 spigot.yml BungeeCord: false 时 SkinsRestorer 生成普通的配置文件 TrMenu插件修复 
3. 问题：怎么能让BungeeCord:true 的时候 TrMenu不报错
```

### 🗄 服务端日志

```
[13:01:21] [Server thread/INFO]: Starting minecraft server version 1.8.8
[13:01:21] [Server thread/INFO]: Loading properties
[13:01:21] [Server thread/INFO]: Default game type: SURVIVAL
[13:01:22] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-21fe707-741a1bd (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[13:01:22] [Server thread/INFO]: Debug logging is disabled
[13:01:22] [Server thread/INFO]: Server Ping Player Sample Count: 12
[13:01:22] [Server thread/INFO]: Using 4 threads for Netty based IO
[13:01:22] [Server thread/INFO]: Generating keypair
[13:01:22] [Server thread/INFO]: Starting Minecraft server on *:10241
[13:01:22] [Server thread/INFO]: Using default channel type
[13:01:22] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[13:01:22] [Server thread/INFO]: Loading libraries, please wait...
[13:01:25] [Server thread/INFO]: [AsyncKeepAlive] Loading AsyncKeepAlive v1.1
[13:01:25] [Server thread/INFO]: [MobHealth] Loading MobHealth v10.0.1
[13:01:25] [Server thread/INFO]: [CustomBaoShi] Loading CustomBaoShi v1.2
[13:01:25] [Server thread/INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.11.2
[13:01:25] [Server thread/INFO]: [UltraPunishments] Loading UltraPunishments v1.9.9
[13:01:25] [Server thread/INFO]: [UltraScoreboards] Loading UltraScoreboards v1.1.5
[13:01:25] [Server thread/INFO]: [WelcomeTitle] Loading WelcomeTitle v1.0
[13:01:25] [Server thread/INFO]: [LevelCtrlU] Loading LevelCtrlU v1.0
[13:01:25] [Server thread/INFO]: [BunKai] Loading BunKai v1.0
[13:01:25] [Server thread/INFO]: [MinePrefix] Loading MinePrefix v1.0
[13:01:25] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.8.0
[13:01:25] [Server thread/INFO]: [SkinsRestorer] Loading SkinsRestorer v14.2.1
[13:01:25] [Server thread/INFO]: [UltraEconomy] Loading UltraEconomy v2.0.9
[13:01:25] [Server thread/INFO]: [Forge] Loading Forge v1.0
[13:01:25] [Server thread/INFO]: [Vault] Loading Vault v1.7.3-b131
[13:01:25] [Server thread/INFO]: [UltraPermissions] Loading UltraPermissions v5.2.3
[13:01:25] [Server thread/INFO]: [TrMenu] Loading TrMenu v3.1.10
[13:01:25] [Server thread/INFO]: [m[m
[13:01:25] [Server thread/INFO]: [0;37;22m正在加载 [0;36;22mTr[0;36;1mMenu [0;37;1m[21mPremium... [0;30;1mgit-Spigot-21fe707-741a1bd (MC: 1.8.8)[m
[13:01:25] [Server thread/INFO]: [m[m
[13:01:25] [Server thread/INFO]: [Citizens] Loading Citizens v2.0.29-SNAPSHOT (build 2464)
[13:01:25] [Server thread/INFO]: [CMILib] Loading CMILib v1.2.1.2
[13:01:25] [Server thread/INFO]: [WarpSystem] Loading WarpSystem v5.1.2-free
[13:01:25] [Server thread/INFO]: [Residence] Loading Residence v5.0.1.7
[13:01:25] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.8.0
[13:01:25] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[13:01:26] [Server thread/INFO]: [UltraEconomy] Enabling UltraEconomy v2.0.9
[13:01:26] [Server thread/INFO]: [0;36;1m[[0;37;22mUltraEconomy[0;36;1m] [mLoading Plugin...[m
[13:01:27] [Server thread/ERROR]: [UltraEconomy] Plugin UltraEconomy v2.0.9 has failed to register events for class me.TechsCode.UltraEconomy.item.ItemRedeemManager because org/bukkit/event/entity/EntityPickupItemEvent does not exist.
[13:01:27] [Server thread/ERROR]: [UltraEconomy] Plugin UltraEconomy v2.0.9 has failed to register events for class me.TechsCode.UltraEconomy.item.CurrencyItemDisableEvents because org/bukkit/event/inventory/PrepareAnvilEvent does not exist.
[13:01:27] [Server thread/INFO]: [0;36;1m[[0;37;22mUltraEconomy[0;36;1m] [mSuccessfully loaded in 627 ms[m
[13:01:27] [Server thread/INFO]: [Vault] Enabling Vault v1.7.3-b131
[13:01:27] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[13:01:27] [Server thread/INFO]: [Vault] Enabled Version 1.7.3-b131
[13:01:27] [Server thread/INFO]: [0;36;1m[[0;37;22mUltraEconomy[0;36;1m] [mHooked into Vault[m
[13:01:27] [Server thread/INFO]: [UltraPermissions] Enabling UltraPermissions v5.2.3
[13:01:27] [Server thread/INFO]: [0;36;1m[[0;37;22mUltraPermissions[0;36;1m] [mLoading Plugin...[m
[13:01:28] [Server thread/INFO]: [0;36;1m[[0;37;22mUltraPermissions[0;36;1m] [mHooked into Vault[m
[13:01:28] [Server thread/INFO]: [0;36;1m[[0;37;22mUltraPermissions[0;36;1m] [mSuccessfully loaded in 1164 ms[m
[13:01:28] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[13:01:28] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[13:01:28] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[13:01:28] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[13:01:28] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[13:01:28] [Server thread/INFO]: Preparing level "world"
[13:01:28] [Server thread/INFO]: -------- World Settings For [world] --------
[13:01:28] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[13:01:28] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:01:28] [Server thread/INFO]: Item Despawn Rate: 6000
[13:01:28] [Server thread/INFO]: Item Merge Radius: 2.5
[13:01:28] [Server thread/INFO]: Chunks to Grow per Tick: 650
[13:01:28] [Server thread/INFO]: Clear tick list: false
[13:01:28] [Server thread/INFO]: Experience Merge Radius: 3.0
[13:01:28] [Server thread/INFO]: Arrow Despawn Rate: 1200
[13:01:28] [Server thread/INFO]: View Distance: 10
[13:01:28] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[13:01:28] [Server thread/INFO]: Max Entity Collisions: 8
[13:01:28] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[13:01:28] [Server thread/INFO]: Anti X-Ray: true
[13:01:28] [Server thread/INFO]: 	Engine Mode: 1
[13:01:28] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[13:01:28] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[13:01:28] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[13:01:28] [Server thread/INFO]: Sending up to 10 chunks per packet
[13:01:28] [Server thread/INFO]: Mob Spawn Range: 4
[13:01:28] [Server thread/INFO]: Random Lighting Updates: false
[13:01:28] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:01:28] [Server thread/INFO]: Structure Info Saving: true
[13:01:28] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[13:01:28] [Server thread/INFO]: Cactus Growth Modifier: 100%
[13:01:28] [Server thread/INFO]: Cane Growth Modifier: 100%
[13:01:28] [Server thread/INFO]: Melon Growth Modifier: 100%
[13:01:28] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[13:01:28] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[13:01:28] [Server thread/INFO]: Sapling Growth Modifier: 100%
[13:01:28] [Server thread/INFO]: Wheat Growth Modifier: 100%
[13:01:28] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[13:01:28] [Server thread/INFO]: Max TNT Explosions: 100
[13:01:28] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:01:28] [Server thread/INFO]: Preparing start region for level 0 (Seed: 4947409902272617954)
[13:01:29] [Server thread/INFO]: [AsyncKeepAlive] Enabling AsyncKeepAlive v1.1
[13:01:29] [Server thread/INFO]: AsyncKeepAlive has been enbale.
[13:01:29] [Server thread/INFO]: [MobHealth] Enabling MobHealth v10.0.1
[13:01:29] [Server thread/INFO]: [MobHealth] healthPrefix is:§r§f§r
[13:01:29] [Server thread/INFO]: [MobHealth] Example monster bar:§fMob§r§f§r: [§a|||||§c|||||§f]
[13:01:29] [Server thread/INFO]: [MobHealth] Permissions Disabled.
[13:01:29] [Server thread/INFO]: [MobHealth] Spout Enabled.
[13:01:29] [Server thread/INFO]: [MobHealth] Player Notifications Enabled.
[13:01:29] [Server thread/INFO]: [MobHealth] Monster Notifications Enabled.
[13:01:29] [Server thread/INFO]: [MobHealth] Animals Notifications Enabled.
[13:01:29] [Server thread/INFO]: [MobHealth] Pet Notifications Enabled.
[13:01:29] [Server thread/INFO]: [MobHealth] Update check disabled.
[13:01:29] [Server thread/INFO]: [CustomBaoShi] Enabling CustomBaoShi v1.2
[13:01:29] [Server thread/INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.2
[13:01:29] [Server thread/INFO]: [PlaceholderAPI] Fetching available expansion information...
[13:01:29] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: uecon [1.0.0]
[13:01:29] [Server thread/INFO]: [0;36;1m[[0;37;22mUltraEconomy[0;36;1m] [mHooked into PlaceholderAPI[m
[13:01:29] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: uperms [1.0.0]
[13:01:29] [Server thread/INFO]: [0;36;1m[[0;37;22mUltraPermissions[0;36;1m] [mHooked into PlaceholderAPI[m
[13:01:29] [Server thread/INFO]: [UltraPunishments] Enabling UltraPunishments v1.9.9
[13:01:29] [Server thread/INFO]: [0;36;1m[[0;37;22mUltraPunishments[0;36;1m] [mLoading Plugin...[m
[13:01:30] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: upun [1.0.0]
[13:01:30] [Server thread/INFO]: [0;36;1m[[0;37;22mUltraPunishments[0;36;1m] [mSuccessfully loaded in 458 ms[m
[13:01:30] [Server thread/INFO]: [UltraScoreboards] Enabling UltraScoreboards v1.1.5
[13:01:30] [Server thread/INFO]: [0;36;1m[[0;37;22mUltraScoreboards[0;36;1m] [mLoading Plugin...[m
[13:01:30] [Server thread/INFO]: [0;36;1m[[0;37;22mUltraScoreboards[0;36;1m] [mSuccessfully loaded in 437 ms[m
[13:01:30] [Server thread/INFO]: [WelcomeTitle] Enabling WelcomeTitle v1.0
[13:01:30] [Server thread/INFO]: [LevelCtrlU] Enabling LevelCtrlU v1.0
[13:01:30] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: LC [1.0]
[13:01:30] [Server thread/INFO]: [BunKai] Enabling BunKai v1.0
[13:01:30] [Server thread/INFO]: [MinePrefix] Enabling MinePrefix v1.0
[13:01:30] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: MinePrefix [1.0.0]
[13:01:30] [Server thread/INFO]: [MinePrefix] 插件加载完成
[13:01:30] [Server thread/INFO]: [SkinsRestorer] Enabling SkinsRestorer v14.2.1
[13:01:30] [Server thread/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[32;1mDetected Minecraft [33;1mv1_8_R3[32;1m, using [33;1mSpigotSkinRefresher[32;1m.[0;39m[m
[13:01:30] [Server thread/INFO]: [Forge] Enabling Forge v1.0
[13:01:30] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: dz [1.0]
[13:01:30] [Server thread/INFO]: PlaceholderAPI Enable
[13:01:30] [Server thread/INFO]: [TrMenu] Enabling TrMenu v3.1.10
[13:01:31] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: TrMenu [3.1.10]
[13:01:31] [ForkJoinPool.commonPool-worker-9/INFO]: [0;30;1m[[0;36;22mTr[0;36;1mMenu[0;30;1m] [0;32;1m良好 [0;30;1m| [0;32;1m7 [0;36;22m个菜单已加载 [0;30;1m(329 ms)[m
[13:01:31] [Server thread/WARN]: SLF4J: No SLF4J providers were found.
[13:01:31] [Server thread/WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[13:01:31] [Server thread/WARN]: SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
[13:01:31] [Server thread/INFO]: [0;30;1m[[0;36;22mTr[0;36;1mMenu[0;30;1m] [0;36;1m良好 [0;30;1m| [0;36;22m插件启用. 当前运行版本 [0;32;22m3.1.10[0;37;22m.[m
[13:01:31] [Server thread/INFO]: [0;30;1m[[0;36;22mTr[0;36;1mMenu[0;30;1m] [0;33;22m挂钩 [0;30;1m| [0;37;22m软依赖 [0;37;1mSkinsRestorer [0;37;22m已兼容.[m
[13:01:31] [Server thread/INFO]: [0;30;1m[[0;36;22mTr[0;36;1mMenu[0;30;1m] [0;33;22m挂钩 [0;30;1m| [0;37;22m软依赖 [0;37;1mVault [0;37;22m已兼容.[m
[13:01:31] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.29-SNAPSHOT (build 2464)
[13:01:31] [Server thread/INFO]: [CMILib] Enabling CMILib v1.2.1.2
[13:01:32] [Server thread/INFO]: [0;36;22mServer version: v1_8_R3 - 1.8.8 - spigot[m
[13:01:33] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: cmil [1.2.1.2]
[13:01:33] [Server thread/INFO]: PlaceholderAPI hooked.[m
[13:01:33] [Server thread/INFO]: Updated (EN) language file. Took [0;33;22m37ms[m
[13:01:33] [Server thread/INFO]: [WarpSystem] Enabling WarpSystem v5.1.2-free
[13:01:33] [Server thread/INFO]: [WarpSystem]  
[13:01:33] [Server thread/INFO]: [WarpSystem] __________________________________________________________
[13:01:33] [Server thread/INFO]: [WarpSystem]  
[13:01:33] [Server thread/INFO]: [WarpSystem]                        WarpSystem [5.1.2-free]
[13:01:33] [Server thread/INFO]: [WarpSystem]  
[13:01:33] [Server thread/INFO]: [WarpSystem] Status:
[13:01:33] [Server thread/INFO]: [WarpSystem]  
[13:01:33] [Server thread/INFO]: [WarpSystem] MC-Version: 1.8.8 (R0.1-SNAPSHOT, Spigot)
[13:01:33] [Server thread/INFO]: [WarpSystem]  
[13:01:33] [Server thread/INFO]: [WarpSystem] Loading features
[13:01:33] [Server thread/INFO]: [WarpSystem]   > Loading Icons
[13:01:33] [Server thread/INFO]: [WarpSystem]     > Loading background
[13:01:33] [Server thread/INFO]: [WarpSystem]       ...got 1 background
[13:01:33] [Server thread/INFO]: [WarpSystem]     > Loading Icons
[13:01:33] [Server thread/INFO]: [WarpSystem]       ...got 0 Icons
[13:01:33] [Server thread/INFO]: [WarpSystem]   > Loading Animations
[13:01:33] [Server thread/INFO]: [WarpSystem]     ...got 0 animation(s)
[13:01:33] [Server thread/INFO]: [WarpSystem]   > Loading Portals
[13:01:33] [Server thread/INFO]: [WarpSystem]     ...got 0 Portal(s)
[13:01:33] [Server thread/INFO]: [WarpSystem]   > Loading WarpSigns
[13:01:33] [Server thread/INFO]: [WarpSystem]     ...got 0 WarpSign(s)
[13:01:33] [Server thread/INFO]: [WarpSystem]   > Loading RandomTeleporters
[13:01:33] [Server thread/INFO]: [WarpSystem]     ...got 3 WorldOption(s)
[13:01:33] [Server thread/INFO]: [WarpSystem]     ...got 0 InteractBlock(s)
[13:01:33] [Server thread/INFO]: [WarpSystem]   > Loading Shortcuts
[13:01:33] [Server thread/INFO]: [WarpSystem]     ...got 0 Shortcut(s)
[13:01:33] [Server thread/INFO]: [WarpSystem]   > Loading SimpleWarps
[13:01:33] [Server thread/INFO]: [WarpSystem]     ...got 0 SimpleWarp(s)
[13:01:33] [Server thread/INFO]: [WarpSystem]   > Loading PlayerWarps [Bungee: false; TimeDependent: true]
[13:01:33] [Server thread/INFO]: [WarpSystem]     ...got 6 Class(es)
[13:01:33] [Server thread/INFO]: [WarpSystem]     ...got 0 PlayerWarp(s)
[13:01:33] [Server thread/INFO]: [WarpSystem]  
[13:01:33] [Server thread/INFO]: [WarpSystem] Loading TeleportManager
[13:01:33] [Server thread/INFO]: [WarpSystem] Starting AutoSaver
[13:01:33] [Server thread/INFO]: [WarpSystem]  
[13:01:33] [Server thread/INFO]: [WarpSystem] Finished (388ms)
[13:01:33] [Server thread/INFO]: [WarpSystem]  
[13:01:33] [Server thread/INFO]: [WarpSystem] __________________________________________________________
[13:01:33] [Server thread/INFO]: [WarpSystem]  
[13:01:33] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: warpsystem [5.1.2-free]
[13:01:33] [Server thread/INFO]: [WarpSystem] ====================================================
[13:01:33] [Server thread/INFO]: [WarpSystem]  WarpSystem works better if you use Paper 
[13:01:33] [Server thread/INFO]: [WarpSystem]  as your server software. 
[13:01:33] [Server thread/INFO]: [WarpSystem]   
[13:01:33] [Server thread/INFO]: [WarpSystem]  Paper offers significant performance improvements,
[13:01:33] [Server thread/INFO]: [WarpSystem]  bug fixes, security enhancements and optional
[13:01:33] [Server thread/INFO]: [WarpSystem]  features for server owners to enhance their server.
[13:01:33] [Server thread/INFO]: [WarpSystem]   
[13:01:33] [Server thread/INFO]: [WarpSystem]  Paper includes Timings v2, which is significantly
[13:01:33] [Server thread/INFO]: [WarpSystem]  better at diagnosing lag problems over v1.
[13:01:33] [Server thread/INFO]: [WarpSystem]   
[13:01:33] [Server thread/INFO]: [WarpSystem]  All of your plugins should still work, and the
[13:01:33] [Server thread/INFO]: [WarpSystem]  Paper community will gladly help you fix any issues.
[13:01:33] [Server thread/INFO]: [WarpSystem]   
[13:01:33] [Server thread/INFO]: [WarpSystem]  Join the Paper Community @ https://papermc.io
[13:01:33] [Server thread/INFO]: [WarpSystem] ====================================================
[13:01:33] [Server thread/INFO]: [Residence] Enabling Residence v5.0.1.7
[13:01:34] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Loaded (2) groups[m
[13:01:34] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Found Vault using permissions plugin:UltraPermissions[m
[13:01:34] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Scanning for economy systems...[m
[13:01:34] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Found Vault using economy system: [0;35;22mUltraEconomy[m
[13:01:34] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Loaded world data into memory. (0 ms) -> 0 residences[m
[13:01:34] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: residence [5.0.1.7]
[13:01:34] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m PlaceholderAPI was found - Enabling capabilities.[m
[13:01:34] [Server thread/INFO]: [0;32;1m[[0;33;22mResidence[0;32;1m][0;37;22m Enabled! Version 5.0.1.7 by Zrips[m
[13:01:34] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:01:34] [Server thread/INFO]: Done (5.758s)! For help, type "help" or "?"
[13:01:34] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[13:01:34] [Server thread/INFO]: [Citizens] 已载入 0 个NPC.
[13:01:34] [Craft Scheduler Thread - 7/INFO]: [Vault] Checking for Updates ... 
[13:01:35] [Craft Scheduler Thread - 2/INFO]: [0;36;1m[[0;37;22mUltraPunishments[0;36;1m] [mCould not load translations from github[m
[13:01:35] [Craft Scheduler Thread - 6/WARN]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39mFailed to get release info from api.github.com. 
 If this message is repeated a lot, please see http://skinsrestorer.net/firewall[0;39m
[13:01:35] [Craft Scheduler Thread - 0/INFO]: [0;36;1m[[0;37;22mUltraEconomy[0;36;1m] [mCould not load translations from github[m
[13:01:35] [Craft Scheduler Thread - 3/INFO]: [0;36;1m[[0;37;22mUltraScoreboards[0;36;1m] [mCould not load translations from github[m
[13:01:35] [Craft Scheduler Thread - 2/INFO]: [0;36;1m[[0;37;22mUltraPunishments[0;36;1m] [mTranslations successfully loaded & applied[m
[13:01:35] [Craft Scheduler Thread - 0/INFO]: [0;36;1m[[0;37;22mUltraEconomy[0;36;1m] [mTranslations successfully loaded & applied[m
[13:01:35] [Craft Scheduler Thread - 3/INFO]: [0;36;1m[[0;37;22mUltraScoreboards[0;36;1m] [mTranslations successfully loaded & applied[m
[13:01:35] [Craft Scheduler Thread - 9/INFO]: [0;36;1m[[0;37;22mUltraPermissions[0;36;1m] [mCould not load translations from github[m
[13:01:35] [Craft Scheduler Thread - 9/INFO]: [0;36;1m[[0;37;22mUltraPermissions[0;36;1m] [mTranslations successfully loaded & applied[m
[13:01:35] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: bungee [1.0.1]
[13:01:35] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: pinger [1.0.1]
[13:01:35] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: player [2.0.3]
[13:01:35] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: server [2.6.1]
[13:01:35] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: vault [1.7.0]
[13:01:35] [Server thread/INFO]: [0;32;1m5 placeholder hook(s) registered! [0;33;22m1 placeholder hook(s) have an update available.[m
[13:01:35] [Craft Scheduler Thread - 1/INFO]: [0;36;1m[[0;37;22mUltraPermissions[0;36;1m] [mLoading Permission Database...[m
[13:01:35] [Server thread/INFO]: [0;36;1m[[0;37;22mUltraPunishments[0;36;1m] [mDetected PlaceholderAPI, hooking into it...[m
[13:01:35] [Craft Scheduler Thread - 1/INFO]: [0;36;1m[[0;37;22mUltraPermissions[0;36;1m] [m- 617 Permissions extracted from .jars[m
[13:01:35] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: upun [latest]
[13:01:35] [Craft Scheduler Thread - 1/INFO]: [0;36;1m[[0;37;22mUltraPermissions[0;36;1m] [mFailed to load Permissions from the Cloud[m
[13:01:35] [Craft Scheduler Thread - 1/INFO]: [0;36;1m[[0;37;22mUltraPermissions[0;36;1m] [m- 2415 Permissions loaded from the Cache[m
[13:01:35] [Craft Scheduler Thread - 7/INFO]: [Vault] No new version available
[13:02:06] [Thread-22/INFO]: UUID of player NoobKing_CN is 2296afdc-41d3-3a48-92c4-88f633dd5993
[13:02:07] [Server thread/INFO]: NoobKing_CN[/127.0.0.1:10804] logged in with entity id 21 at ([world]3.5854937608916844, 82.0, -0.10149646402440583)
[13:02:07] [Server thread/INFO]: [WarpSystem] Found a valid proxy > Init proxy-features (Server: 'RPG-Spawn')
[13:02:07] [Craft Scheduler Thread - 5/WARN]: Exception in thread "Craft Scheduler Thread - 5" 
[13:02:07] [Craft Scheduler Thread - 5/WARN]: org.apache.commons.lang.UnhandledException: Plugin TrMenu v3.1.10 generated an exception while executing task 198
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: net.skinsrestorer.bukkit.utils.BukkitProperty cannot be cast to com.mojang.authlib.properties.Property
	at me.arasple.mc.trmenu.module.internal.hook.impl.HookSkinsRestorer.getPlayerSkinTexture(HookSkinsRestorer.kt:31)
	at me.arasple.mc.trmenu.util.bukkit.Heads.playerTexture(Heads.kt:77)
	at me.arasple.mc.trmenu.util.bukkit.Heads.getPlayerHead(Heads.kt:47)
	at me.arasple.mc.trmenu.module.internal.listener.ListenerJoin$onJoin$1.invoke(ListenerJoin.kt:21)
	at me.arasple.mc.trmenu.module.internal.listener.ListenerJoin$onJoin$1.invoke(ListenerJoin.kt:19)
	at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$6.run(BukkitExecutor.kt:89)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

[13:02:15] [Server thread/INFO]: NoobKing_CN issued server command: /trmenu debug dump

```

### ⚙ 配置文件

```
仅将 datasource.yml ConnectionTestQuery: 由~ 改为 SELECT 1
```

**Comment by 157946a** [comment]
和trmenuapi关系不大，你更新了skin导致的的，更新trmenu
