### ISSUE TITLE
[Bug]: SkinsRestorer获取头颅错误

### ISSUE THREAD

**Issue by KaterzX** [InsinuateProjects/TrMenu#205]
### 🚀 Have you tried the latest version

- [X] I have updated TrMenu to the latest version and the same bug is reproduced.

### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

```
TrMenu Dump Information (Date: xxxx-xx-xx xx:xx:xx)

  | Server OS: xxxx
  | Server software: xxxx
  | Java version: 17

  | TabooLib: x.x.x
  | TrMenu: latest
Installed Plugins:
  · XXXXXX - x.x.x
  · XXXXXX - x.x.x
  · XXXXXX - x.x.x
```

### 🔍 Detailed description

无法获取头颅材质,且菜单中不会显示头颅按钮

### 🗄 Server log

[19:16:30] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.resolve(String)" because "this.skinsFolder" is null
[19:16:30] [Server thread/WARN]: 	at SkinsRestorer.jar//net.skinsrestorer.shared.storage.SkinStorage.getSkinData(SkinStorage.java:292)
[19:16:30] [Server thread/WARN]: 	at SkinsRestorer.jar//net.skinsrestorer.shared.storage.SkinStorage.getSkinData(SkinStorage.java:268)
[19:16:30] [Server thread/WARN]: 	at SkinsRestorer.jar//net.skinsrestorer.api.SkinsRestorerAPI.getSkinData(SkinsRestorerAPI.java:114)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.module.internal.hook.impl.HookSkinsRestorer.getPlayerSkinTexture(HookSkinsRestorer.kt:25)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.util.bukkit.Heads.playerTexture(Heads.kt:77)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.util.bukkit.Heads.getPlayerHead(Heads.kt:47)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.util.bukkit.Heads.getHead(Heads.kt:40)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.module.display.texture.Texture.generate(Texture.kt:41)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.api.menu.IItem$DefaultImpls.generate(IItem.kt:22)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.module.display.item.Item.generate(Item.kt:16)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.module.display.item.Item.build(Item.kt:39)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.module.display.item.Item.build$default(Item.kt:34)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.module.display.item.Item.get(Item.kt:31)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.module.display.icon.Icon.settingItem(Icon.kt:80)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.module.display.icon.Icon.filter(Icon.kt:156)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.module.display.icon.Icon.onRefresh(Icon.kt:85)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.module.display.Menu.loadIcon(Menu.kt:155)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.module.display.Menu.open(Menu.kt:90)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.module.internal.command.impl.CommandOpen$command$1$1$2.invoke(CommandOpen.kt:47)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.module.internal.command.impl.CommandOpen$command$1$1$2.invoke(CommandOpen.kt:36)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandExecutor.exec(CommandBuilder.kt:185)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:95)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:87)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandBase.execute(CommandBuilder.kt:108)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.taboolib.common.platform.command.CommandRegisterKt$command$1.execute(CommandRegister.kt:23)
[19:16:30] [Server thread/WARN]: 	at TrMenu.jar//me.arasple.mc.trmenu.taboolib.platform.BukkitCommand$registerCommand$1.invoke$lambda-0(BukkitCommand.kt:69)

### ⚙ Configurations

  'X':
    update: 20
    display:
      mat: 'head:%player_name%'
      name: '&f                       '

**Comment by Dirt233** [comment]
你的dump信息呢，插件版本skins版本呢？

**Comment by 157946a** [comment]
更新插件

**Comment by dongzh1** [comment]
trmenu和skinre均已更新到最新，存在同样问题

**Comment by dongzh1** [comment]
![image](https://user-images.githubusercontent.com/43366518/200163262-3db2322a-5d91-418c-ba4c-8f25af3dc6c3.png)
![image](https://user-images.githubusercontent.com/43366518/200163273-65ce9dd2-49f5-4744-a6a0-ff2fbd521646.png)
![image](https://user-images.githubusercontent.com/43366518/200163282-67e7f4e3-fc30-4f40-b216-d9a6724a6cfc.png)
