### ISSUE TITLE
[问题]: 报错

### ISSUE THREAD

**Issue by xbaimiao** [InsinuateProjects/TrMenu#206]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: xxxx-xx-xx xx:xx:xx)

  | Server OS: Centos7
  | Server software: xxxx
  | Java version:  18

  | TabooLib: x.x.x
  | TrMenu: 3.1.12
Installed Plugins:
SkinsRestorer


### 🔍 详细的描述

玩家进服出现如下报错

### 🗄 服务端日志

```
[13:15:58 WARN]: [TrMenu] Plugin TrMenu v3.1.10 generated an exception while executing task 322984
java.lang.ClassCastException: class net.skinsrestorer.bukkit.utils.BukkitProperty cannot be cast to class com.mojang.authlib.properties.Property (net.skinsrestorer.bukkit.utils.BukkitProperty is in unnamed module of loader 'SkinsRestorer.jar' @3bea31e3; com.mojang.authlib.properties.Property is in unnamed module of loader java.net.URLClassLoader @67424e82)
        at me.arasple.mc.trmenu.module.internal.hook.impl.HookSkinsRestorer.getPlayerSkinTexture(HookSkinsRestorer.kt:31) ~[TrMenu-3.1.10.jar:?]
        at me.arasple.mc.trmenu.util.bukkit.Heads.playerTexture(Heads.kt:77) ~[TrMenu-3.1.10.jar:?]
        at me.arasple.mc.trmenu.util.bukkit.Heads.getPlayerHead(Heads.kt:47) ~[TrMenu-3.1.10.jar:?]
        at me.arasple.mc.trmenu.module.internal.listener.ListenerJoin$onJoin$1.invoke(ListenerJoin.kt:21) ~[TrMenu-3.1.10.jar:?]
        at me.arasple.mc.trmenu.module.internal.listener.ListenerJoin$onJoin$1.invoke(ListenerJoin.kt:19) ~[TrMenu-3.1.10.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$6.run(BukkitExecutor.kt:89) ~[TrMenu-3.1.10.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-386]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-386]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-386]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

### ⚙ 配置文件

```
1
```

**Comment by 157946a** [comment]
更新插件
