### ISSUE TITLE
[Bug]: 插件无法加载

### ISSUE THREAD

**Issue by Xiaojin-serv** [InsinuateProjects/TrMenu#211]
### 🚀 Have you tried the latest version

- [X] I have updated TrMenu to the latest version and the same bug is reproduced.

### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [x] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

插件未载入, 无法使用指令.

### 🔍 Detailed description

服务器使用java8 (jdk8), 启动时无法载入TrMenu(报错)
核心是Paper-1.12.2

### 🗄 Server log

[21:12:24 ERROR]: Could not load 'plugins\TrMenu-3.1.13.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.InternalError: Malformed class name
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
Caused by: java.lang.InternalError: Malformed class name
        at java.lang.Class.getSimpleName(Class.java:1330) ~[?:1.8.0_261]
        at me.arasple.mc.trmenu.taboolib.common.io.Project1Kt.getInstance(Project1.kt:42) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.inject.RuntimeInjector.inject(RuntimeInjector.java:87) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.inject.RuntimeInjector.injectAll(RuntimeInjector.java:65) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:126) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:37) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_261]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_261]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1620]
        ... 6 more

### ⚙ Configurations

默认配置

**Comment by 157946a** [comment]
更换java版本至11或者使用旧版本trmenu
