### ISSUE TITLE
[Bug]: 匿名类在java8中错误无法启动trmenu

### ISSUE THREAD

**Issue by zhibeigg** [InsinuateProjects/TrMenu#212]
### 🚀 Have you tried the latest version

- [X] I have updated TrMenu to the latest version and the same bug is reproduced.

### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

```
TrMenu Dump Information (Date: xxxx-xx-xx xx:xx:xx)

  | Server OS: xxxx
  | Server software: xxxx
  | Java version: xxxx

  | TabooLib: x.x.x
  | TrMenu: x.x.x
Installed Plugins:
  · XXXXXX - x.x.x
  · XXXXXX - x.x.x
  · XXXXXX - x.x.x
```

### 🔍 Detailed description

```
1. ...
2. ...
3. ...
```

### 🗄 Server log

[09:05:54] [Server thread/ERROR]: Could not load 'plugins\TrMenu-3.1.13.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.InternalError: Malformed class name
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332]
Caused by: java.lang.InternalError: Malformed class name
	at java.lang.Class.getSimpleName(Class.java:1330) ~[?:1.8.0_332]
	at me.arasple.mc.trmenu.taboolib.common.io.Project1Kt.getInstance(Project1.kt:42) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.common.inject.RuntimeInjector.inject(RuntimeInjector.java:87) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.common.inject.RuntimeInjector.injectAll(RuntimeInjector.java:65) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:126) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:37) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_332]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_332]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	... 6 more

### ⚙ Configurations

```

```

**Comment by Score2** [comment]
Fixed
