### ISSUE TITLE
[问题]: 

### ISSUE THREAD

**Issue by MC54145** [InsinuateProjects/TrMenu#213]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2022-08-01 08:37:52)

| Server OS: Windows Server 2019 amd64 10.0
| Server software: git-Purpur-1745 (MC: 1.19.1) (1.19.1-R0.1-SNAPSHOT)
| Java version: 17.0.3.1

| TrMenu: 3.1.13
Installed Plugins: 
· ABCoreLib - 1.7.2 (0 KB)
· ABPresent - 1.6 (0 KB)
· AncientGates - 2.5.1 (0 KB)
· Around - 3.1 (0 KB)
· ArtMap - 3.9.3 (0 KB)
· AureliumSkills - Beta 1.3.6 (0 KB)
· AuthMe - 5.6.0-SNAPSHOT-b2501 (0 KB)
· BankPlus - 5.6 (0 KB)
· BedWars - 0.2.25 (0 KB)
· BlockLocker - 1.11 (0 KB)
· BloodFading - 0.5.2 (0 KB)
· CMILib - 1.2.3.1 (0 KB)
· ConsoleSpamFix - 1.9.0 (0 KB)
· ControlPlayer - 2.2.4 (0 KB)
· CrackShot - 0.98.11 (0 KB)
· CrazyAuctionsPlus - 1.2.2 (0 KB)
· CrazyCrates - 1.11.6-SNAPSHOT (0 KB)
· CustomCrafting - 3.16.6.2 (0 KB)
· DamageIndicator - 1.3.8 (0 KB)
· DeEnchantment - 1.3.1 (0 KB)
· DecentHolograms - 2.5.2 (0 KB)
· EvenMoreFish - 1.6.2 (0 KB)
· FaithlPack - 2.0.4 (0 KB)
· Fenestra - 1.1.1 (0 KB)
· FiniteNetherite - 1.0 (0 KB)
· ForcePack - 1.2.0 (0 KB)
· GCore - 8.37.0 (0 KB)
· GFly - [2.3.0.0] (0 KB)
· GSit - 1.2.1 (0 KB)
· Harbor - 1.6.3 (0 KB)
· Hat - 1.4.4 (0 KB)
· HuskHomes - 2.11.2 (0 KB)
· InfiniteScoreboard - 1.2.0 (0 KB)
· ItemEdit - 3.0.4 (0 KB)
· ItemTag - 3.0.1 (0 KB)
· LiteLottery - 1.3.1 (0 KB)
· LiteSignIn - 1.6.3.3 (0 KB)
· LuckPerms - 5.4.30 (0 KB)
· Multiverse-Core - 4.3.1-b861 (0 KB)
· Multiverse-Inventories - 4.2.3-b523 (0 KB)
· MusicBox - 2.0.9 (0 KB)
· NoBlackSky - 2.7 (0 KB)
· NoteBlockAPI - 1.6.1-SNAPSHOT (0 KB)
· Nova - 0.9.11 (0 KB)
· OpenInv - 4.2.0 (0 KB)
· PistonMOTD - 5.0.1 (0 KB)
· PlaceholderAPI - 2.11.2 (0 KB)
· PlayerKits - 2.24.2 (0 KB)
· PlayerPoints - 3.2.4 (0 KB)
· PlayerTitle - 2.10.8 (0 KB)
· PointLogger - 1.0.2 (0 KB)
· PortableCraftingInvs - 1.7.3 (0 KB)
· ProtocolLib - 5.0.0-SNAPSHOT-b584 (0 KB)
· PublicBin - 1.1.1 (0 KB)
· QuickShop-Hikari - 3.1.0.1 (0 KB)
· RandomTeleport - 3.0.1.190 (0 KB)
· RedPacket - 1.5.5 (0 KB)
· Residence - 5.0.1.7 (0 KB)
· RewardsLite - 3.0.6 (0 KB)
· ScriptBlockPlus - 2.2.2 (0 KB)
· ScriptEntityPlus - 1.2.1 (0 KB)
· ServerBackup - 2.7.4 (0 KB)
· Shopkeepers - 2.16.0 (0 KB)
· SkinsRestorer - 14.2.1 (0 KB)
· Skulls - 3.3.0 (0 KB)
· TabList - 5.6.3 (0 KB)
· TileDataSaver - 1.0.10 (0 KB)
· TrChat - 2.0.0-PRE-21 (0 KB)
· TrMenu - 3.1.13 (0 KB)
· Tweakin - 4.2.0 (0 KB)
· UltimateAutoRestart - Build 52c (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· VeinMiner - 1.17.10 (0 KB)
· WolfyUtilities - 4.16.4.1 (0 KB)
· WorldEdit - 7.2.11-beta-01+6200-0877589 (0 KB)
· WorldGuard - 7.0.6+1cff55f (0 KB)
· XConomy - 2.19.2 (0 KB)
· ZetaJoinAction - 1.1.0 (0 KB)
· eGlow - 3.1.7 (0 KB)
· qscompat-openinv - 3.1.0.1 (0 KB)
· qscompat-residence - 3.1.0.1 (0 KB)
· qscompat-worldedit - 3.1.0.1 (0 KB)
· spark - 1.9.29 (0 KB)
```

### 🔍 详细的描述

```
1. 无法打开菜单(包括自带)，并显示"An internal error occurred while attempting to perform this command"
    打开菜单有音效 使用命令：/menu open Example
2. 重载出错
3. 是否支持1.19.1?
```

### 🗄 服务端日志

/menu reload后日志
```
[08:27:36 WARN]: [TrMenu] Plugin TrMenu v3.1.13 generated an exception while executing task 104368
java.lang.LinkageError: loader me.arasple.mc.trmenu.taboolib.module.nms.AsmClassLoader @513a483d attempted duplicate class definition for me.arasple.mc.trmenu.api.receptacle.vanilla.window.NMSImpl. (me.arasple.mc.trmenu.api.receptacle.vanilla.window.NMSImpl is in unnamed module of loader me.arasple.mc.trmenu.taboolib.module.nms.AsmClassLoader @513a483d, parent loader 'TrMenu-3.1.13.jar' @4fe93105)
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.nms.AsmClassLoader.createNewClass(AsmClassLoader.kt:18) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.taboolib.module.nms.AsmClassTransfer.run(AsmClassTransfer.kt:23) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.taboolib.module.nms.MinecraftServerUtilKt.nmsProxy$lambda-1(MinecraftServerUtil.kt:29) ~[TrMenu-3.1.13.jar:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.nms.MinecraftServerUtilKt.nmsProxy(MinecraftServerUtil.kt:27) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.api.receptacle.vanilla.window.WindowReceptacle.initializationPackets$receptacle(WindowReceptacle.kt:142) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.api.receptacle.vanilla.window.WindowReceptacle$title$1.invoke(WindowReceptacle.kt:36) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.api.receptacle.vanilla.window.WindowReceptacle$title$1.invoke(WindowReceptacle.kt:35) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$4.run(BukkitExecutor.kt:70) ~[TrMenu-3.1.13.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.1.jar:git-Purpur-1745]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.1.jar:git-Purpur-1745]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

以下为/menu open Example执行后日志
```
[09:09:35 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'menu' in plugin TrMenu v3.1.13
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:940) ~[purpur-1.19.1.jar:git-Purpur-1745]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:59) ~[purpur-1.19.1.jar:git-Purpur-1745]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:312) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:296) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2371) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2336) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.1.jar:git-Purpur-1745]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1386) ~[purpur-1.19.1.jar:git-Purpur-1745]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.1.jar:git-Purpur-1745]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1363) ~[purpur-1.19.1.jar:git-Purpur-1745]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1356) ~[purpur-1.19.1.jar:git-Purpur-1745]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1334) ~[purpur-1.19.1.jar:git-Purpur-1745]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[purpur-1.19.1.jar:git-Purpur-1745]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.1.jar:git-Purpur-1745]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.nms.MinecraftServerUtilKt.nmsProxy$lambda-1(MinecraftServerUtil.kt:29) ~[TrMenu-3.1.13.jar:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.nms.MinecraftServerUtilKt.nmsProxy(MinecraftServerUtil.kt:27) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.api.receptacle.vanilla.window.WindowReceptacle.initializationPackets$receptacle(WindowReceptacle.kt:142) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.api.receptacle.vanilla.window.WindowReceptacle.open(WindowReceptacle.kt:80) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.module.display.Menu.open(Menu.kt:93) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.module.internal.command.impl.CommandOpen$command$1$1$2.invoke(CommandOpen.kt:47) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.module.internal.command.impl.CommandOpen$command$1$1$2.invoke(CommandOpen.kt:36) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandExecutor.exec(CommandBuilder.kt:185) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:95) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:87) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandBase.execute(CommandBuilder.kt:108) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandRegisterKt$command$1.execute(CommandRegister.kt:23) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitCommand$registerCommand$1.invoke$lambda-0(BukkitCommand.kt:68) ~[TrMenu-3.1.13.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.server.v1_19_R1.ItemStack org.bukkit.craftbukkit.v1_19_R1.inventory.CraftItemStack.asNMSCopy(org.bukkit.inventory.ItemStack)'
        at me.arasple.mc.trmenu.api.receptacle.vanilla.window.NMSImpl.<init>(NMSImpl.kt:25) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.nms.MinecraftServerUtilKt.nmsProxy$lambda-1(MinecraftServerUtil.kt:29) ~[TrMenu-3.1.13.jar:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.nms.MinecraftServerUtilKt.nmsProxy(MinecraftServerUtil.kt:27) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.api.receptacle.vanilla.window.WindowReceptacle.initializationPackets$receptacle(WindowReceptacle.kt:142) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.api.receptacle.vanilla.window.WindowReceptacle.open(WindowReceptacle.kt:80) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.module.display.Menu.open(Menu.kt:93) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.module.internal.command.impl.CommandOpen$command$1$1$2.invoke(CommandOpen.kt:47) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.module.internal.command.impl.CommandOpen$command$1$1$2.invoke(CommandOpen.kt:36) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandExecutor.exec(CommandBuilder.kt:185) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:95) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:87) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandBase.execute(CommandBuilder.kt:108) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandRegisterKt$command$1.execute(CommandRegister.kt:23) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitCommand$registerCommand$1.invoke$lambda-0(BukkitCommand.kt:68) ~[TrMenu-3.1.13.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more
[09:09:35 WARN]: [TrMenu] Plugin TrMenu v3.1.13 generated an exception while executing task 23210
java.lang.LinkageError: loader me.arasple.mc.trmenu.taboolib.module.nms.AsmClassLoader @44288270 attempted duplicate class definition for me.arasple.mc.trmenu.api.receptacle.vanilla.window.NMSImpl. (me.arasple.mc.trmenu.api.receptacle.vanilla.window.NMSImpl is in unnamed module of loader me.arasple.mc.trmenu.taboolib.module.nms.AsmClassLoader @44288270, parent loader 'TrMenu-3.1.13.jar' @7826fe20)
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.nms.AsmClassLoader.createNewClass(AsmClassLoader.kt:18) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.taboolib.module.nms.AsmClassTransfer.run(AsmClassTransfer.kt:23) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.taboolib.module.nms.MinecraftServerUtilKt.nmsProxy$lambda-1(MinecraftServerUtil.kt:29) ~[TrMenu-3.1.13.jar:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.nms.MinecraftServerUtilKt.nmsProxy(MinecraftServerUtil.kt:27) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.api.receptacle.vanilla.window.WindowReceptacle.initializationPackets$receptacle(WindowReceptacle.kt:142) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.api.receptacle.vanilla.window.WindowReceptacle$title$1.invoke(WindowReceptacle.kt:36) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.api.receptacle.vanilla.window.WindowReceptacle$title$1.invoke(WindowReceptacle.kt:35) ~[TrMenu-3.1.13.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$4.run(BukkitExecutor.kt:70) ~[TrMenu-3.1.13.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.1.jar:git-Purpur-1745]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.1.jar:git-Purpur-1745]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### ⚙ 配置文件

```

```

**Comment by Score2** [comment]
Fixed
