### ISSUE TITLE
[问题]: 

### ISSUE THREAD

**Issue by ShenMac** [InsinuateProjects/TrMenu#214]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

TrMenu Dump Information (Date: 2022-08-01 11:00:00)

| Server OS: Windows 11 amd64 10.0
| Server software: git-Mirai-12 (MC: 1.19.1) (1.19.1-R0.1-SNAPSHOT)
| Java version: 18.0.1.1

| TrMenu: 3.1.13
Installed Plugins: 
· BlockLocker - 1.11 (222 KB)
· CMI - 9.2.3.0 (3621 KB)
· CMILib - 1.2.3.1 (763 KB)
· ChanLang - 2.3 (153 KB)
· CoreProtect - 21.2 (835 KB)
· CreeperConfetti - 1.3 (12 KB)
· DemonMarket - 1.3.7 (3458 KB)
· GrimAC - 2.3.17 (5497 KB)
· IllegalStack - 2.5 (205 KB)
· JulyLibrary - 2.6.0 (789 KB)
· JulySafe - 3.1.1 (3696 KB)
· JulySafe-Bin - 0.0.7-beta (30 KB)
· KeepInventory - 1.3-SNAPSHOT (6 KB)
· LuckPerms - 5.4.30 (1364 KB)
· Multiverse-Core - 4.3.1-b861 (485 KB)
· NemoLibrary - 1.0.5 (126 KB)
· PlaceholderAPI - 2.11.2 (832 KB)
· ProtocolLib - 5.0.0-SNAPSHOT-b586 (4739 KB)
· QuickShop - 5.1.0.9 (7447 KB)
· Residence - 5.0.1.7 (962 KB)
· TrMenu - 3.1.13 (3073 KB)
· Vault - 1.7.3-CMI (268 KB)
· VeinMiner - 1.17.10 (161 KB)
· WorldEdit - 7.2.11+c43a877 (5859 KB)
· monster - 3.0.5 (491 KB)

### 🔍 详细的描述

玩家进不了服务器报错

### 🗄 服务端日志

```
[10:56:55 INFO]: UUID of player Shen_Mac is 67d78e4a-de5e-41d5-8ae6-c32ad5fbbe2b
[10:56:55 WARN]: java.lang.NoSuchFieldException: net.minecraft.world.entity.Entity#playerConnection
[10:56:55 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.library.reflex.JavaClassStructure.getField(JavaClassStructure.kt:20)
[10:56:55 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:25)
[10:56:55 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:28)
[10:56:55 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:28)
[10:56:55 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:28)
[10:56:55 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.library.reflex.Reflex$Companion.getLocalProperty(Reflex.kt:83)
[10:56:55 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:58)
[10:56:55 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:56)
[10:56:55 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.library.reflex.Reflex$Companion.getProperty$default(Reflex.kt:52)
[10:56:55 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.common.reflect.Reflex$Companion.getProperty(Reflex.kt:41)
[10:56:55 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.common.reflect.Reflex$Companion.getProperty$default(Reflex.kt:40)
[10:56:55 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.module.nms.ChannelExecutor.getPlayerChannel(ChannelExecutor.kt:29)
[10:56:55 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.module.nms.ChannelExecutor.addPlayerChannel$lambda-0(ChannelExecutor.kt:46)
[10:56:55 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[10:56:55 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[10:56:55 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:56:55 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:56:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[10:56:55 INFO]: Shen_Mac[/127.0.0.1:52935] logged in with entity id 290 at ([time]-241.03255436392033, 116.0, 121.29342855594514)
[10:56:56 INFO]: Shen_Mac lost connection: Internal Exception: io.netty.handler.codec.EncoderException: ac.grim.grimac.shaded.com.github.retrooper.packetevents.exception.PacketProcessException: Failed to process outgoing packet
[10:56:56 WARN]: java.lang.NoSuchFieldException: net.minecraft.world.entity.Entity#playerConnection
[10:56:56 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.library.reflex.JavaClassStructure.getField(JavaClassStructure.kt:20)
[10:56:56 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:25)
[10:56:56 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:28)
[10:56:56 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:28)
[10:56:56 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:28)
[10:56:56 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.library.reflex.Reflex$Companion.getLocalProperty(Reflex.kt:83)
[10:56:56 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:58)
[10:56:56 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:56)
[10:56:56 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.library.reflex.Reflex$Companion.getProperty$default(Reflex.kt:52)
[10:56:56 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.common.reflect.Reflex$Companion.getProperty(Reflex.kt:41)
[10:56:56 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.common.reflect.Reflex$Companion.getProperty$default(Reflex.kt:40)
[10:56:56 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.module.nms.ChannelExecutor.getPlayerChannel(ChannelExecutor.kt:29)
[10:56:56 WARN]:        at TrMenu-3.1.13.jar//me.arasple.mc.trmenu.taboolib.module.nms.ChannelExecutor.removePlayerChannel$lambda-1(ChannelExecutor.kt:56)
[10:56:56 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[10:56:56 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[10:56:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:56:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:56:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### ⚙ 配置文件

```

```

**Comment by Dirt233** [comment]
1.19.1请尝试更新至最新版本查看问题是否解决
