### ISSUE TITLE
[问题]: TrMenu 与 SkinsRestorer

### ISSUE THREAD

**Issue by NoobKing666** [InsinuateProjects/TrMenu#215]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2022-08-05 15:11:28)

| Server OS: Windows 10 amd64 10.0
| Server software: git-Spigot-21fe707-741a1bd (MC: 1.8.8) (1.8.8-R0.1-SNAPSHOT)
| Java version: 1.8.0_241

| TrMenu: 3.1.14
Installed Plugins: 
· AsyncKeepAlive - 1.1 (0 KB)
· BunKai - 1.0 (0 KB)
· CMILib - 1.2.3.2 (0 KB)
· Citizens - 2.0.29-SNAPSHOT (build 2464) (0 KB)
· CustomBaoShi - 1.2 (0 KB)
· Forge - 1.0 (0 KB)
· LevelCtrlU - 1.0 (0 KB)
· MinePrefix - 1.0 (0 KB)
· MobHealth - 10.0.1 (0 KB)
· PlaceholderAPI - 2.11.2 (0 KB)
· ProtocolLib - 4.8.0 (0 KB)
· Residence - 5.0.1.7 (0 KB)
· SkinsRestorer - 14.2.2 (0 KB)
· TrMenu - 3.1.14 (0 KB)
· UltraEconomy - 2.0.9 (0 KB)
· UltraPermissions - 5.2.3 (0 KB)
· UltraPunishments - 1.9.9 (0 KB)
· UltraScoreboards - 1.1.5 (0 KB)
· Vault - 1.7.3-b131 (0 KB)
· WarpSystem - 5.1.2-free (0 KB)
· WelcomeTitle - 1.0 (0 KB)
```

### 🔍 详细的描述

```
1. Spigot服务端开启 spigot.yml bungeecord: true 时，SkinsRestorer 生成BC配置文件，结果TrMenu无法加载玩家皮肤并报错，头颅无法加载。
```

### 🗄 服务端日志

```
[15:08:48 INFO]: UUID of player NoobKing_CN is 2296afdc-41d3-3a48-92c4-88f633dd5993
[15:08:48 INFO]: NoobKing_CN[/127.0.0.1:10117] logged in with entity id 21 at ([world]1.252641458510936, 82.0, -5.174531138312573)
[15:08:48 WARN]: Exception in thread "Craft Scheduler Thread - 9"
[15:08:48 WARN]: org.apache.commons.lang.UnhandledException: Plugin TrMenu v3.1.14 generated an exception while executing task 232
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: SkinStorage is not initialized. Is SkinsRestorer in proxy mode?
        at net.skinsrestorer.api.SkinsRestorerAPI.getSkinStorage(SkinsRestorerAPI.java:258)
        at net.skinsrestorer.api.SkinsRestorerAPI.getSkinData(SkinsRestorerAPI.java:115)
        at me.arasple.mc.trmenu.module.internal.hook.impl.HookSkinsRestorer.getPlayerSkinTexture(HookSkinsRestorer.kt:25)
        at me.arasple.mc.trmenu.util.bukkit.Heads.playerTexture(Heads.kt:77)
        at me.arasple.mc.trmenu.util.bukkit.Heads.getPlayerHead(Heads.kt:47)
        at me.arasple.mc.trmenu.module.internal.listener.ListenerJoin$onJoin$1.invoke(ListenerJoin.kt:21)
        at me.arasple.mc.trmenu.module.internal.listener.ListenerJoin$onJoin$1.invoke(ListenerJoin.kt:19)
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$6.run(BukkitExecutor.kt:89)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

[15:08:48 INFO]: [WarpSystem] Found a valid proxy > Init proxy-features (Server: 'RPG-Spawn')
[15:08:52 INFO]: NoobKing_CN issued server command: /weather clear
[15:08:52 INFO]: [NoobKing_CN: Changing to clear weather]
[15:08:59 INFO]: NoobKing_CN issued server command: /trmenu
[15:09:01 INFO]: NoobKing_CN issued server command: /trmenu list
[15:09:02 INFO]: NoobKing_CN issued server command: /trmenu open Menu
[15:09:03 WARN]: java.lang.IllegalStateException: SkinStorage is not initialized. Is SkinsRestorer in proxy mode?
[15:09:03 WARN]:        at net.skinsrestorer.api.SkinsRestorerAPI.getSkinStorage(SkinsRestorerAPI.java:258)
[15:09:03 WARN]:        at net.skinsrestorer.api.SkinsRestorerAPI.getSkinData(SkinsRestorerAPI.java:115)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.module.internal.hook.impl.HookSkinsRestorer.getPlayerSkinTexture(HookSkinsRestorer.kt:25)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.util.bukkit.Heads.playerTexture(Heads.kt:77)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.util.bukkit.Heads.getPlayerHead(Heads.kt:47)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.util.bukkit.Heads.getHead(Heads.kt:40)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.module.display.texture.Texture.generate(Texture.kt:41)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.module.display.item.Item.generate(Item.kt:36)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.module.display.item.Item.build(Item.kt:65)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.module.display.item.Item.build$default(Item.kt:60)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.module.display.item.Item.get(Item.kt:32)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.module.display.icon.Icon.settingItem(Icon.kt:80)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.module.display.icon.Icon.filter(Icon.kt:156)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.module.display.icon.Icon.onRefresh(Icon.kt:85)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.module.display.Menu.loadIcon(Menu.kt:155)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.module.display.Menu.open(Menu.kt:90)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.api.action.impl.menu.Open.onExecute(Open.kt:30)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.api.action.base.ActionBase$Option.evalPlayers(ActionBase.kt:115)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.api.action.base.ActionEntry.execute(ActionEntry.kt:31)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.api.action.ActionHandle.runAction(ActionHandle.kt:92)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.api.reaction.Reactions.eval(Reactions.kt:16)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.module.display.icon.IconProperty.handleClick(IconProperty.kt:42)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1$1.invoke(Layout.kt:93)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1$1.invoke(Layout.kt:91)
[15:09:03 WARN]:        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$7.run(BukkitExecutor.kt:98)
[15:09:03 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[15:09:03 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[15:09:03 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[15:09:03 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[15:09:03 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[15:09:03 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[15:09:03 WARN]:        at java.lang.Thread.run(Thread.java:748)
[15:09:03 INFO]: ICON: Info
[15:11:23 INFO]: NoobKing_CN issued server command: /tr
[15:11:28 INFO]: NoobKing_CN issued server command: /trmenu debug dump
```

### ⚙ 配置文件

```
没多大东西
```

**Comment by 157946a** [comment]
https://github.com/InsinuateProjects/TrMenu/issues/199
