### ISSUE TITLE
[问题]: 最新构建不支持1.19.2新服务端

### ISSUE THREAD

**Issue by shuiqing2046** [InsinuateProjects/TrMenu#217]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

TrMenu Dump Information (Date: 2022-08-07 11:58:11)

| Server OS: Windows 11 amd64 10.0
| Server software: git-Purpur-1752 (MC: 1.19.2) (1.19.2-R0.1-SNAPSHOT)
| Java version: 18.0.2

| TrMenu: 3.1.14
Installed Plugins: 
· BossShopPro - 2.0.15 (0 KB)
· CMILib - 1.2.3.2 (0 KB)
· ChatManager - 3.7.6 (0 KB)
· Citizens - 2.0.30-SNAPSHOT (build 2657) (0 KB)
· Essentials - 2.19.5-dev+29-09dc49a (0 KB)
· EssentialsAntiBuild - 2.19.5-dev+29-09dc49a (0 KB)
· EssentialsChat - 2.19.5-dev+29-09dc49a (0 KB)
· EssentialsProtect - 2.19.5-dev+29-09dc49a (0 KB)
· EssentialsSpawn - 2.19.5-dev+29-09dc49a (0 KB)
· GSit - 1.2.1 (0 KB)
· InteractiveChat - 4.2.3.0 (0 KB)
· ItemJoin - 5.2.5-SNAPSHOT-b845 (0 KB)
· LuckPerms - 5.4.30 (0 KB)
· Multiverse-Core - 4.3.2-SNAPSHOT-b870 (0 KB)
· PlaceholderAPI - 2.11.2 (0 KB)
· PlayerPoints - 2.1.5-SNAPSHOT (0 KB)
· ProtocolLib - 5.0.0-SNAPSHOT-b584 (0 KB)
· Residence - 5.0.1.7 (0 KB)
· SystemChat - 1.0.0 (0 KB)
· TrMenu - 3.1.14 (0 KB)
· Vault - 1.7.3-b${env.TRAVIS_BUILD_NUMBER} (0 KB)
· ViaBackwards - 4.4.1 (0 KB)
· ViaVersion - 4.4.1 (0 KB)
· ViaVersionStatus - 3.11 (0 KB)
· spark - 1.9.29 (0 KB)

### 🔍 详细的描述

```
1. 测试中启动无报错,有人进服后刷报错.
2. 上个版本1.19.1测试正常使用
3. 打开菜单后会无限循环刷报错,除了关服没法停止
4. 循环报错太多只截取了前面少部分报错：https://paste.helpch.at/ogodicexiy.rb
```

### 🗄 服务端日志

> trmenu debug dump
[11:58:11 INFO]: [TrMenu] 粘贴内容中 ...
[11:58:13 INFO]: [TrMenu] 内容已被粘贴至 https://paste.helpch.at/ezalufewif.
> .
[12:00:45 INFO]: 错误的命令,不能执行.
[12:01:00 INFO]: UUID of player allens is 9fd71684-7d84-3962-95b3-f0e9c4b3b1fd
[12:01:01 INFO]: [ViaVersionStatus] allens is using version 1.19.1(760).
[12:01:01 WARN]: java.lang.NoSuchFieldException: net.minecraft.world.entity.Entity#playerConnection
[12:01:01 WARN]:        at TrMenu-3.1.14.jar//me.arasple.mc.trmenu.taboolib.library.reflex.JavaClassStructure.getField(JavaClassStructure.kt:20)
[12:01:01 WARN]:        at TrMenu-3.1.14.jar//me.arasple.mc.trmenu.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:25)
[12:01:01 WARN]:        at TrMenu-3.1.14.jar//me.arasple.mc.trmenu.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:28)
[12:01:01 WARN]:        at TrMenu-3.1.14.jar//me.arasple.mc.trmenu.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:28)
[12:01:01 WARN]:        at TrMenu-3.1.14.jar//me.arasple.mc.trmenu.taboolib.library.reflex.ReflexClass.getField(ReflexClass.kt:28)
[12:01:01 WARN]:        at TrMenu-3.1.14.jar//me.arasple.mc.trmenu.taboolib.library.reflex.Reflex$Companion.getLocalProperty(Reflex.kt:83)
[12:01:01 WARN]:        at TrMenu-3.1.14.jar//me.arasple.mc.trmenu.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:58)
[12:01:01 WARN]:        at TrMenu-3.1.14.jar//me.arasple.mc.trmenu.taboolib.library.reflex.Reflex$Companion.getProperty(Reflex.kt:56)
[12:01:01 WARN]:        at TrMenu-3.1.14.jar//me.arasple.mc.trmenu.taboolib.library.reflex.Reflex$Companion.getProperty$default(Reflex.kt:52)
[12:01:01 WARN]:        at TrMenu-3.1.14.jar//me.arasple.mc.trmenu.taboolib.common.reflect.Reflex$Companion.getProperty(Reflex.kt:41)
[12:01:01 WARN]:        at TrMenu-3.1.14.jar//me.arasple.mc.trmenu.taboolib.common.reflect.Reflex$Companion.getProperty$default(Reflex.kt:40)
[12:01:01 WARN]:        at TrMenu-3.1.14.jar//me.arasple.mc.trmenu.taboolib.module.nms.ChannelExecutor.getPlayerChannel(ChannelExecutor.kt:29)
[12:01:01 WARN]:        at TrMenu-3.1.14.jar//me.arasple.mc.trmenu.taboolib.module.nms.ChannelExecutor.addPlayerChannel$lambda-0(ChannelExecutor.kt:46)
[12:01:01 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[12:01:01 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[12:01:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:01:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:01:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:01:01 INFO]: allens joined the game
[12:01:01 INFO]: allens[/127.0.0.1:51832] logged in with entity id 4 at ([world]-86.5, 66.0, -294.5)
[12:01:04 INFO]: allens has made the advancement [Getting an Upgrade]

### ⚙ 配置文件

```

```

**Comment by shuiqing2046** [comment]
2022年8月17日已支持1.19.2,感谢贡献者的更新.
August 17, 2022.
1.19.2 is supported, thanks to contributors for the update.
