### ISSUE TITLE
[问题]: 上下翻页会随机性抛出错误日志

### ISSUE THREAD

**Issue by shuiqing2046** [InsinuateProjects/TrMenu#220]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2022-08-19 01:34:14)

| Server OS: Windows 11 amd64 10.0
| Server software: git-Purpur-1761 (MC: 1.19.2) (1.19.2-R0.1-SNAPSHOT)
| Java version: 18.0.2

| TrMenu: 3.1.15
Installed Plugins: 
· ActionHealth - 3.5.8 (0 KB)
· AdvancedAchievements - 8.0.2 (0 KB)
· AntiPopup - 4.3 (0 KB)
· AntiSeedCracker - 1.0 (0 KB)
· BedBlock - 1.0 (0 KB)
· BetterRTP - 3.4.4 (0 KB)
· BlockLocker - 1.11 (0 KB)
· BossShopPro - 2.0.15 (0 KB)
· CMILib - 1.2.3.3 (0 KB)
· ChatManager - 3.7.6 (0 KB)
· ChestCommands - 3.1.4 (0 KB)
· Citizens - 2.0.30-SNAPSHOT (build 2665) (0 KB)
· ColorSigns - 1.0.0 (0 KB)
· CoreProtect - 21.2 (0 KB)
· DecentHolograms - 2.5.3 (0 KB)
· Dynmap-Essentials - 0.91-SNAPSHOT (0 KB)
· Elevator - 3.12.3 (0 KB)
· EpicPluginLib - 2.3.1 (0 KB)
· Essentials - 2.20.0-dev+1-b71fb52 (0 KB)
· EssentialsAntiBuild - 2.20.0-dev+1-b71fb52 (0 KB)
· EssentialsChat - 2.20.0-dev+1-b71fb52 (0 KB)
· EssentialsProtect - 2.20.0-dev+1-b71fb52 (0 KB)
· EssentialsSpawn - 2.20.0-dev+1-b71fb52 (0 KB)
· FastAsyncWorldEdit - 2.4.4-SNAPSHOT-265;cc1b466 (0 KB)
· GSit - 1.2.2 (0 KB)
· HoloDropsX - 3.0.0 (0 KB)
· IllegalStack - 2.5 (0 KB)
· InteractionVisualizer - 1.18.1.0 (0 KB)
· InteractiveChat - 4.2.3.0 (0 KB)
· ItemJoin - 5.2.5-SNAPSHOT-b847 (0 KB)
· KeepInventory - 1.3-SNAPSHOT (0 KB)
· LiteSignIn - 1.6.3.2 (0 KB)
· LuckPerms - 5.4.41 (0 KB)
· MarriageMaster - 2.6.7-Release (0 KB)
· Minepacks - 2.4.8-Release (0 KB)
· Multiverse-Core - 4.3.2-SNAPSHOT-b870 (0 KB)
· MyPet - 3.12 (0 KB)
· OpenInv - 4.2.1 (0 KB)
· PlaceholderAPI - 2.11.2 (0 KB)
· PlayMoreSounds - 4.2 (0 KB)
· PlayerCommands - 2.0.0 (0 KB)
· PlayerPoints - 3.2.4 (0 KB)
· PlotSquared - 6.9.4-Premium (0 KB)
· ProtocolLib - 5.0.0-SNAPSHOT-b586 (0 KB)
· PvPManager - 3.10.1 (0 KB)
· QuickShop-Hikari - 3.1.0.5 (0 KB)
· Residence - 5.0.2.0 (0 KB)
· ResidenceDynmap - 1.1 (0 KB)
· RespawnX - 2.3.0 (0 KB)
· SignEdit - 1.13.7 (0 KB)
· SimpleRename - 13.9 (0 KB)
· SimpleTpa - 6.1 (0 KB)
· SirBlobmanCore - 2.4.0 (0 KB)
· SystemChat - 1.0.0 (0 KB)
· TAB - 3.1.4 (0 KB)
· TrMenu - 3.1.15 (0 KB)
· Vault - 1.7.3-b${env.TRAVIS_BUILD_NUMBER} (0 KB)
· ViaBackwards - 4.4.1 (0 KB)
· ViaVersion - 4.4.1 (0 KB)
· ViaVersionStatus - 3.11 (0 KB)
· VipSystem - 4.13 (0 KB)
· WDLCompanion - 1.2.0 (0 KB)
· dynmap - 3.4-828 (0 KB)
· qssuite-dynmap - 1.0.0.4 (0 KB)
· qssuite-list - 1.0.0.4 (0 KB)
· spark - 1.9.33 (0 KB)
```

### 🔍 详细的描述

```
1. 创建两页菜单
2. 配置左击右击上下翻页按钮
3. 翻页中跳出报错
4. 似乎并没有什么不良后果
```

### 🗄 服务端日志

```
[01:26:02 WARN]: [TrMenu] Plugin TrMenu v3.1.15 generated an exception while executing task 216389
java.lang.NullPointerException: null
        at me.arasple.mc.trmenu.module.display.icon.Position.refreshCurrentPosition(Position.kt:25) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Position.currentPosition$lambda-0(Position.kt:21) ~[TrMenu-3.1.15.jar:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
        at me.arasple.mc.trmenu.module.display.icon.Position.currentPosition(Position.kt:21) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon.settingItem(Icon.kt:80) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon.onUpdate(Icon.kt:69) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon$startup$1$1.invoke(Icon.kt:27) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon$startup$1$1.invoke(Icon.kt:26) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$2.run(BukkitExecutor.kt:51) ~[TrMenu-3.1.15.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[01:26:15 WARN]: [TrMenu] Plugin TrMenu v3.1.15 generated an exception while executing task 217456
java.lang.NullPointerException: null
        at me.arasple.mc.trmenu.module.display.icon.Position.refreshCurrentPosition(Position.kt:25) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Position.currentPosition$lambda-0(Position.kt:21) ~[TrMenu-3.1.15.jar:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
        at me.arasple.mc.trmenu.module.display.icon.Position.currentPosition(Position.kt:21) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon.settingItem(Icon.kt:80) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon.onUpdate(Icon.kt:69) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon$startup$1$1.invoke(Icon.kt:27) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon$startup$1$1.invoke(Icon.kt:26) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$2.run(BukkitExecutor.kt:51) ~[TrMenu-3.1.15.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[01:26:16 WARN]: [TrMenu] Plugin TrMenu v3.1.15 generated an exception while executing task 217528
java.lang.NullPointerException: null
        at me.arasple.mc.trmenu.module.display.icon.Position.refreshCurrentPosition(Position.kt:25) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Position.currentPosition$lambda-0(Position.kt:21) ~[TrMenu-3.1.15.jar:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
        at me.arasple.mc.trmenu.module.display.icon.Position.currentPosition(Position.kt:21) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon.settingItem(Icon.kt:80) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon.onUpdate(Icon.kt:69) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon$startup$1$1.invoke(Icon.kt:27) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon$startup$1$1.invoke(Icon.kt:26) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$2.run(BukkitExecutor.kt:51) ~[TrMenu-3.1.15.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[01:26:29 WARN]: [TrMenu] Plugin TrMenu v3.1.15 generated an exception while executing task 218424
java.lang.NullPointerException: null
        at me.arasple.mc.trmenu.module.display.icon.Position.refreshCurrentPosition(Position.kt:25) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Position.currentPosition$lambda-0(Position.kt:21) ~[TrMenu-3.1.15.jar:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
        at me.arasple.mc.trmenu.module.display.icon.Position.currentPosition(Position.kt:21) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon.settingItem(Icon.kt:80) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon.onUpdate(Icon.kt:69) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon$startup$1$1.invoke(Icon.kt:27) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon$startup$1$1.invoke(Icon.kt:26) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$2.run(BukkitExecutor.kt:51) ~[TrMenu-3.1.15.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### ⚙ 配置文件

```
Title:
  - '  &4&n&l玩家商城'
  
Title-Update: -1

#菜单布局
Layout:
  - - '#########'
    - ' #      '
    - ' #      '
    - ' #       '
    - '#########'
    - ' #      '

  - - '#########'
    - '#       #'
    - '#       #'
    - '#       #'
    - '#       #'
    - '#       #'

#玩家库存布局
PlayerInventory:
  - - ' #     #-'
    - '#########'
  - - ' #     #N'
    - '#########'

Options:
  # 是否启用菜单传参功能
  Arguments: false
  # 默认填充参数
  Default-Arguments: [ ]
  # Not work with animated title
  Free-Slots:
    - 71-73
  # 默认布局页码
  Default-Layout: 0
  # 是否隐藏玩家容器
  Hide-Player-Inventory: true
  # 防频繁点击的间隔
  Min-Click-Delay: 200
  # 定义需强制安装需要的变量
  Depend-Expansions: [ 'server', 'player', 'progress', 'animations' ]

#打开方式
Bindings:
  #打开命令
  Commands:
    - 'vip'
    - 'VIP'
  #绑定打开的物品
#  Items:
#    - 'material:compass'

Events:
  #需要判定权限的打开
  Open:
    - actions: 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'

  Close: []



#图标内容
Icons:
  #挡板
  '#':
    update: [ -1, 10, -1, 10 ]
    display:
      material: RED_STAINED_GLASS_PANE

  #子一级菜单往返  
  '-':
    update: [ -1, 8, -1, -1 ]
    display:
      material: KNOWLEDGE_BOOK
      name: [ '&6&l往&7&l返菜单', '&6&l往返&7&l菜单', '&6&l往返菜&7&l单', '&6&l往返菜单', '&7&l往返菜单' ]
      #发光效果
      shiny: 'false'
      #隐藏属性
      #可用物品标签
      # HIDE_ENCHANTS
      # HIDE_ATTRIBUTES
      # HIDE_UNBREAKABLE
      # HIDE_POTION_EFFECTS
      # HIDE_DESTROYS
      # HIDE_PLACED_ON
      #flags:
       #- 'HIDE_POTION_EFFECTS'
      lore:
        - '&7左击&f: &7下一页'
        - '右击返回上一页'
    actions:
      left:
       - 'delay: 5'
       - 'page: %math_0_1+{trmenu_menu_page}%'
       - 'sound: BLOCK_CHEST_OPEN-1-2'
      right:
       - 'delay: 5'
       - 'open: CD'
  #子二级菜单往返  
  'N':
    update: [ -1, 8, -1, -1 ]
    display:
      material: KNOWLEDGE_BOOK
      name: [ '&6&l往&7&l返菜单', '&6&l往返&7&l菜单', '&6&l往返菜&7&l单', '&6&l往返菜单', '&7&l往返菜单' ]
      #发光效果
      shiny: 'false'
      #隐藏属性
      #可用物品标签
      # HIDE_ENCHANTS
      # HIDE_ATTRIBUTES
      # HIDE_UNBREAKABLE
      # HIDE_POTION_EFFECTS
      # HIDE_DESTROYS
      # HIDE_PLACED_ON
      #flags:
       #- 'HIDE_POTION_EFFECTS'
      lore:
        - '&7点击&f: &7下一页'
        - '当前第 %math_0_1+{trmenu_menu_page}% 页'
    actions:
      right:
       - 'delay: 5'
       - 'page: %math_0_{trmenu_menu_page}-1%'
       - 'sound: BLOCK_CHEST_OPEN-1-2'
      left:
       - 'delay: 5'
       - 'page: %math_0_1+{trmenu_menu_page}%'
       - 'sound: BLOCK_CHEST_OPEN-1-2'    
#-------------分割线--------------------
```

**Comment by shuiqing2046** [comment]
`
[02:47:49 WARN]: [TrMenu] Plugin TrMenu v3.1.15 generated an exception while executing task 563555
java.lang.NullPointerException: null
        at me.arasple.mc.trmenu.module.display.icon.Position.refreshCurrentPosition(Position.kt:25) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Position.currentPosition$lambda-0(Position.kt:21) ~[TrMenu-3.1.15.jar:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
        at me.arasple.mc.trmenu.module.display.icon.Position.currentPosition(Position.kt:21) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon.settingItem(Icon.kt:80) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon.onUpdate(Icon.kt:69) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon$startup$1$1.invoke(Icon.kt:27) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon$startup$1$1.invoke(Icon.kt:26) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$2.run(BukkitExecutor.kt:51) ~[TrMenu-3.1.15.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:47:51 WARN]: [TrMenu] Plugin TrMenu v3.1.15 generated an exception while executing task 563683
java.lang.NullPointerException: null
        at me.arasple.mc.trmenu.module.display.icon.Position.refreshCurrentPosition(Position.kt:25) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Position.currentPosition$lambda-0(Position.kt:21) ~[TrMenu-3.1.15.jar:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
        at me.arasple.mc.trmenu.module.display.icon.Position.currentPosition(Position.kt:21) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon.settingItem(Icon.kt:80) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon.onUpdate(Icon.kt:69) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon$startup$1$1.invoke(Icon.kt:27) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon$startup$1$1.invoke(Icon.kt:26) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$2.run(BukkitExecutor.kt:51) ~[TrMenu-3.1.15.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:48:13 INFO]: [TrMenu] 良好 | 自动重新载入菜单 VIP.yml (14ms)
[02:50:05 INFO]: [TrMenu] 良好 | 自动重新载入菜单 VIP.yml (12ms)
[02:50:16 INFO]: mcfen issued server command: /cd
[02:50:23 WARN]: [TrMenu] Plugin TrMenu v3.1.15 generated an exception while executing task 571476
java.lang.NullPointerException: null
        at me.arasple.mc.trmenu.module.display.icon.Position.refreshCurrentPosition(Position.kt:25) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Position.currentPosition$lambda-0(Position.kt:21) ~[TrMenu-3.1.15.jar:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
        at me.arasple.mc.trmenu.module.display.icon.Position.currentPosition(Position.kt:21) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon.settingItem(Icon.kt:80) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon.onUpdate(Icon.kt:69) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon$startup$1$1.invoke(Icon.kt:27) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.icon.Icon$startup$1$1.invoke(Icon.kt:26) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$2.run(BukkitExecutor.kt:51) ~[TrMenu-3.1.15.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:50:23 WARN]: [TrMenu] Task #571517 for TrMenu v3.1.15 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3
        at me.arasple.mc.trmenu.module.display.layout.MenuLayout.get-impl(MenuLayout.kt:26) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.MenuSession.layout(MenuSession.kt:93) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.Menu.page(Menu.kt:104) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.api.action.impl.menu.Page.onExecute(Page.kt:26) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionBase$Option.evalPlayers(ActionBase.kt:115) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry.execute(ActionEntry.kt:31) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.api.action.ActionHandle$runAction$1$2$1.invoke(ActionHandle.kt:87) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.api.action.ActionHandle$runAction$1$2$1.invoke(ActionHandle.kt:87) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$5.run(BukkitExecutor.kt:79) ~[TrMenu-3.1.15.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1519) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1443) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1213) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
> .
[02:50:40 WARN]: [TrMenu] Task #572399 for TrMenu v3.1.15 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3
        at me.arasple.mc.trmenu.module.display.layout.MenuLayout.get-impl(MenuLayout.kt:26) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.MenuSession.layout(MenuSession.kt:93) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.module.display.Menu.page(Menu.kt:104) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.api.action.impl.menu.Page.onExecute(Page.kt:26) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionBase$Option.evalPlayers(ActionBase.kt:115) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry$execute$proceed$1.invoke(ActionEntry.kt:29) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.api.action.base.ActionEntry.execute(ActionEntry.kt:31) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.api.action.ActionHandle$runAction$1$2$1.invoke(ActionHandle.kt:87) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.api.action.ActionHandle$runAction$1$2$1.invoke(ActionHandle.kt:87) ~[TrMenu-3.1.15.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$5.run(BukkitExecutor.kt:79) ~[TrMenu-3.1.15.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1519) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1443) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1213) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
> .
[02:51:32 INFO]: [TrMenu] 良好 | 自动重新载入菜单 VIP.yml (11ms)
[02:52:04 INFO]: [TrMenu] 良好 | 自动重新载入菜单 VIP.yml (10ms)
`

**Comment by shuiqing2046** [comment]
研究发现,没有修改任何配置的情况下,打开菜单发生错误具有随机性,并不是每次都抛出错误.每次都是当自己以为一切正常时又莫名其妙抛出了错误.
