### ISSUE TITLE
[Bug]: 无法启动，存在空指针报错

### ISSUE THREAD

**Issue by mrcang09** [InsinuateProjects/TrMenu#225]
### 🚀 Have you tried the latest version

- [X] I have updated TrMenu to the latest version and the same bug is reproduced.

### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

```
TrMenu Dump Information (Date: xxxx-xx-xx xx:xx:xx)

  | Server OS: windows and linux
  | Server software: Paperspigot 1.12.2
  | Java version: JDK8


  | TrMenu: 3.1.16

```

### 🔍 Detailed description

```
1.第一次启动服务器 没报错，第二次启动就启动不了了 提示了一个空指针报错
```

### 🗄 Server log

[22:20:53 ERROR]: Could not load 'plugins\TrMenu-3.1.16.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_341]
Caused by: java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_341]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_341]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1618]
        ... 6 more
Caused by: java.lang.NullPointerException
        at java.util.LinkedList$ListItr.next(LinkedList.java:893) ~[?:1.8.0_341]
        at me.arasple.mc.trmenu.taboolib.common.inject.VisitorGroup.get(VisitorGroup.java:37) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.inject.VisitorHandler.visitStart(VisitorHandler.java:106) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.inject.VisitorHandler.inject(VisitorHandler.java:99) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:64) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:150) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:37) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_341]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_341]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1618]
        ... 6 more

### ⚙ Configurations

```

```

**Comment by XiaoJie-150** [comment]
重新下载插件
