### ISSUE TITLE
Trmenu v3 pre10+无法正常启动

### ISSUE THREAD

**Issue by Spihea** [InsinuateProjects/TrMenu#24]
测试环境:Win21H2 22000.120 ,Java 8 301 
核心:PaperSpigot1.8.9
报错信息

[16:17:04 INFO]: [TrMenu] Enabling TrMenu v3.0-PRE-15
[16:17:04 WARN]: SLF4J: No SLF4J providers were found.
[16:17:04 WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[16:17:04 WARN]: SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
[16:17:04 ERROR]: Error occurred while enabling TrMenu v3.0-PRE-15 (Is it up to date?)
java.lang.AbstractMethodError: org.sqlite.Conn.isValid(I)Z
        at com.zaxxer.hikari_4_0_3.pool.PoolBase.checkValidationSupport(PoolBase.java:464) ~[?:?]
        at com.zaxxer.hikari_4_0_3.pool.PoolBase.checkDriverSupport(PoolBase.java:447) ~[?:?]
        at com.zaxxer.hikari_4_0_3.pool.PoolBase.setupConnection(PoolBase.java:416) ~[?:?]
        at com.zaxxer.hikari_4_0_3.pool.PoolBase.newConnection(PoolBase.java:369) ~[?:?]
        at com.zaxxer.hikari_4_0_3.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[?:?]
        at com.zaxxer.hikari_4_0_3.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[?:?]
        at com.zaxxer.hikari_4_0_3.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[?:?]
        at com.zaxxer.hikari_4_0_3.pool.HikariPool.<init>(HikariPool.java:115) ~[?:?]
        at com.zaxxer.hikari_4_0_3.HikariDataSource.<init>(HikariDataSource.java:81) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.database.Database.createDataSource(Database.kt:18) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.database.Database.createDataSource$default(Database.kt:17) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.database.Host.createDataSource(Host.kt:18) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.database.DatabaseLocal.<init>(DatabaseLocal.kt:34) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.data.Metadata$localDatabase$2.invoke(Metadata.kt:35) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.data.Metadata$localDatabase$2.invoke(Metadata.kt:35) ~[?:?]
        at taboolib.library.kotlin_1_5_10.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.data.Metadata.getLocalDatabase(Metadata.kt:35) ~[?:?]
        at me.arasple.mc.trmenu.TrMenu.onEnable(TrMenu.kt:38) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.onEnable(BukkitPlugin.java:55) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[start.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [start.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [start.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [start.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [start.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [start.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [start.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [start.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [start.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [start.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[16:17:04 INFO]: [TrMenu] Disabling TrMenu v3.0-PRE-15

**Comment by Score2** [comment]
https://www.mcbbs.net/forum.php?mod=redirect&goto=findpost&ptid=1240856&pid=23011569
