### ISSUE TITLE
聊天捕捉 AsyncPlayerChatEvent 失效无法执行command指令

### ISSUE THREAD

**Issue by CivicXFB** [InsinuateProjects/TrMenu#25]
[13:15:29 ERROR]: Could not pass event AsyncPlayerChatEvent to TrMenu v3.0-PRE-15
[13:15:29 ERROR]: Suspected Plugins:
[13:15:29 ERROR]:       TrMenu{enabled,ver=3.0-PRE-15,path=plugins\TrMenu-3.0-PRE-15.jar}
[13:15:29 ERROR]: Exception details below:
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.EventBus$inject$2.invoke(EventBus.kt:31) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.EventBus$inject$2.invoke(EventBus.kt:31) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitAdapter$registerListener$listener$1.invoke(BukkitAdapter.kt:54) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitAdapter$registerListener$listener$1.invoke(BukkitAdapter.kt:54) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitAdapter$BukkitListener.execute(BukkitAdapter.kt:75) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Paper-"f473807"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-"f473807"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-"f473807"]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:234) ~[patched_1.17.1.jar:git-Paper-"f473807"]
        at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:116) ~[patched_1.17.1.jar:git-Paper-"f473807"]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:65) ~[patched_1.17.1.jar:git-Paper-"f473807"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2182) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2093) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2058) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket$1.run(ServerboundChatPacket.java:40) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalStateException: PlayerCommandPreprocessEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:616) ~[patched_1.17.1.jar:git-Paper-"f473807"]
        at me.arasple.mc.trmenu.taboolib.platform.util.BukkitUtilKt.dispatchCommand(BukkitUtil.kt:34) ~[?:?]
        at me.arasple.mc.trmenu.api.action.impl.ActionCommand.onExecute(ActionCommand.kt:16) ~[?:?]
        at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1$1.invoke(AbstractAction.kt:41) ~[?:?]
        at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1$1.invoke(AbstractAction.kt:41) ~[?:?]
        at me.arasple.mc.trmenu.api.action.base.ActionOption.evalPlayers(ActionOption.kt:30) ~[?:?]
        at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1.invoke(AbstractAction.kt:41) ~[?:?]
        at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1.invoke(AbstractAction.kt:41) ~[?:?]
        at me.arasple.mc.trmenu.api.action.base.AbstractAction.run(AbstractAction.kt:43) ~[?:?]
        at me.arasple.mc.trmenu.api.action.Actions.runAction(Actions.kt:93) ~[?:?]
        at me.arasple.mc.trmenu.api.action.pack.Reactions$React.react(Reactions.kt:95) ~[?:?]
        at me.arasple.mc.trmenu.api.action.pack.Reactions.eval(Reactions.kt:70) ~[?:?]
        at me.arasple.mc.trmenu.api.action.pack.Reactions.eval(Reactions.kt:62) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.inputer.Inputer$run$1.invoke(Inputer.kt:55) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.inputer.Inputer$run$1.invoke(Inputer.kt:47) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.inputer.Inputer$Catcher$input$1$1.invoke(Inputer.kt:90) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.inputer.Inputer$Catcher$input$1$1.invoke(Inputer.kt:89) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.util.ChatListener.e(BukkitChat.kt:35) ~[?:?]
        ... 24 more
[13:15:29 INFO]: <CivicXFB> CivicXFB

**Comment by Score2** [comment]
请补充复现过程，例如菜单

**Comment by CivicXFB** [comment]
'3':
    display:
      material: <skull:9842dc3b917b1a796c303e15105474a8e315de7982b6ca54feafb5a4d13d4e95>
      name: '&c邀请成员'
      lore:
        - "&8➥ &a左键&f|邀请临时权限"
        - "&8➥ &a右键&f|邀请好友权限"
    actions:
      left:
        - close
        - catcher:
            player:
              type: CHAT
              start: 'tell: &3请输入邀请玩家名称'
              cancel: 'tell: &7已取消操作'
              end:
                - condition: '$ utils.isPlayerOnline(vars("{meta:input}"))'
                  actions:
                    - 'tell: 操作成功'
                    - 'command: plot add %trmenu_meta_input-player% '                  
                  deny:
                    - 'tell: &c目标玩家未在线'
                    - 'return'
      right: 
        - close
        - catcher:
            player:
              type: CHAT
              start: 'tell: &3请输入邀请玩家名称'
              cancel: 'tell: &7已取消操作'
              end:
                - condition: '$ utils.isPlayerOnline(vars("{meta:input}"))'
                  actions:
                    - 'tell: 操作成功'
                    - 'command: plot trust %trmenu_meta_input-player% '                  
                  deny:
                    - 'tell: &c目标玩家未在线'
                    - 'return'

**Comment by Score2** [comment]
虽然有报错，但命令是能够正常被执行。下一个构建将修复这个错误。

**Comment by CivicXFB** [comment]
但他无法执行command指令啊

**Comment by Score2** [comment]
测试一下最新的构建是否可用

**Comment by CivicXFB** [comment]
好的
