### ISSUE TITLE
material 设置 Spawn Egg 報錯 (1.16.5)

### ISSUE THREAD

**Issue by winnyok2042** [InsinuateProjects/TrMenu#26]
[21:44:54] [Server thread/WARN]: java.lang.UnsupportedOperationException: Must check item type to get spawned type
[21:44:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaSpawnEgg.getSpawnedType(CraftMetaSpawnEgg.java:199)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.taboolib.platform.util.ItemBuilder.<init>(ItemBuilder.kt:111)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.api.menu.IItem$DefaultImpls.generate(IItem.kt:59)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.module.display.item.Item.generate(Item.kt:17)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.module.display.item.Item.build(Item.kt:40)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.module.display.item.Item.build$default(Item.kt:35)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.module.display.item.Item.get(Item.kt:32)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.module.display.icon.Icon.settingItem(Icon.kt:75)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.module.display.icon.Icon.filter(Icon.kt:150)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.module.display.icon.Icon.onRefresh(Icon.kt:80)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.module.display.Menu.loadIcon(Menu.kt:137)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.module.display.Menu.open(Menu.kt:72)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.api.action.impl.ActionOpen.onExecute(ActionOpen.kt:25)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1$1.invoke(AbstractAction.kt:41)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1$1.invoke(AbstractAction.kt:41)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.api.action.base.ActionOption.evalPlayers(ActionOption.kt:30)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1.invoke(AbstractAction.kt:41)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1.invoke(AbstractAction.kt:41)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.api.action.base.AbstractAction.run(AbstractAction.kt:43)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.api.action.Actions.runAction(Actions.kt:93)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.api.action.pack.Reactions$React.react(Reactions.kt:95)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.api.action.pack.Reactions.eval(Reactions.kt:70)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.api.action.pack.Reactions.eval(Reactions.kt:62)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.module.display.icon.IconProperty.handleClick(IconProperty.kt:42)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1$1.invoke(Layout.kt:98)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.module.display.layout.Layout$initReceptacle$2$1$1.invoke(Layout.kt:96)
[21:44:54] [Server thread/WARN]: 	at me.arasple.mc.trmenu.taboolib.platform.BukkitExecutor$submit$7.run(BukkitExecutor.kt:98)
[21:44:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[21:44:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:469)
[21:44:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1504)
[21:44:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449)
[21:44:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1413)
[21:44:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1140)
[21:44:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292)
[21:44:54] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)

  M2:
    display:
      name: 'Test'
      material: PIG_SPAWN_EGG
      
上述是 material: pig_spawn_egg 显示报错 
版本: purpurclip  (Trmenu [3.0-pre15])

**Comment by Score2** [comment]
等待 TabooLib 合并以推送修复 https://github.com/TabooLib/TabooLib/pull/158
