### ISSUE TITLE
材质,动作等bug

### ISSUE THREAD

**Issue by 157946a** [InsinuateProjects/TrMenu#3]
下面这个是一系列的问题,我就不多说了,里面有解释
https://imgtu.com/i/fMSQOK
然后就是settings的右键玩家和蹲下右键玩家不传十字指针对着的玩家id了
https://imgtu.com/i/fMScfs
物品仓库的bug也有,保存后,重启服务器,保存的内容就清空了,还有就是函数,我测试用的函数,目前已无法使用,直接裸了调用函数的整条写法${time_%_s_%}比如这条,返回的应该是秒数,结果直接放出来了,不替换为数值,并且所有内置变量无法使用,看了下papi list里面没有trmenu,加上下面的物品特征的modeldata也无法使用

然后有个建议,就是动作takeitem和指令clear都会清理材质名一样的物品,不填name或者lore的话,即使物品有name或者lore,也会被扣除,所以我建议的是,能做个选项选择是否只扣除没有name或者lore的物品,或者和条件反选一样,可以在物品特征内这么写
"takeitem: material:diamond,amount:1,!lore:&a测试"   lore部分我用了感叹号,我想让他扣除材质名为diamond的物品,但不扣除有lore为 "&a测试" 的物品,能否可以在物品特征后面加个选项是否扣除有无lore或name的物品

**Comment by paulreob** [comment]
嘿，如果takeitem可以指定CustomModelData，那就更好了。

**Comment by 157946a** [comment]
> 嘿，如果takeitem可以指定CustomModelData，那就更好了。

这个可以的,Wiki里都写着,在物品特征部分

**Comment by paulreob** [comment]
> 这个可以的,Wiki里都写着,在物品特征部分,Take the liberty to ask, are you a foreigner

Yes I am, thank you
When trying to use ModelData it is throwing me this WARN `https://paste.helpch.at/uwupewiqiw.cpp` having no diamond with the modeldata or no diamond.

But having the diamond with the specified modeldata does not take it.

![image](https://user-images.githubusercontent.com/71041139/128632187-3cf7dba3-e81a-44f8-9627-4f0a24019a37.png)

**Comment by 157946a** [comment]
> > 这个可以的,Wiki里都写着,在物品特征部分,Take the liberty to ask, are you a foreigner
> 
> Yes I am, thank you
> When trying to use ModelData it is throwing me this WARN `https://paste.helpch.at/uwupewiqiw.cpp` having no diamond with the modeldata or no diamond.
> 
> But having the diamond with the specified modeldata does not take it.
> 
> ![image](https://user-images.githubusercontent.com/71041139/128632187-3cf7dba3-e81a-44f8-9627-4f0a24019a37.png)

Try to write deduction items and sound triggers in list format, example:
-'takeitem'
-'sound'

**Comment by 157946a** [comment]
[22:06:45 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'menu' in plugin TrMenu v3.0-PRE-14
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: openapi.kether.LocalizedException$Concat
        at openapi.kether.LocalizedException.batch(LocalizedException.java:50) ~[?:?]
        at openapi.kether.LocalizedException.then(LocalizedException.java:38) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.library.kether.SimpleQuestLoader$Parser.readActions(SimpleQuestLoader.java:104) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.library.kether.SimpleQuestLoader$Parser.readBlock(SimpleQuestLoader.java:117) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.library.kether.SimpleQuestLoader$Parser.parse(SimpleQuestLoader.java:131) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.library.kether.SimpleQuestLoader.load(SimpleQuestLoader.java:30) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.kether.KetherUtilKt.parseKetherScript(KetherUtil.kt:25) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.kether.KetherFunction.parse$lambda-1(KetherFunction.kt:28) ~[?:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1133) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.kether.KetherFunction.parse(KetherFunction.kt:27) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.kether.KetherFunction.parse$default(KetherFunction.kt:13) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.kether.KetherTransfer.translate(KetherTransfer.kt:20) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.lang.Type$DefaultImpls.translate(Type.kt:42) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.lang.TypeJson.translate(TypeJson.kt:16) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.lang.TypeJson$send$1.invoke(TypeJson.kt:36) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.lang.TypeJson$send$1.invoke(TypeJson.kt:32) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.chat.TellrawJson.sendTo(TellrawJson.kt:26) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.lang.TypeJson.send(TypeJson.kt:32) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.lang.TypeList.send(TypeList.kt:22) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.module.lang.LangKt.sendLang(Lang.kt:13) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.util.BukkitLangKt.sendLang(BukkitLang.kt:14) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.command.impl.CommandList$command$1$1.invoke(CommandList.kt:27) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.command.impl.CommandList$command$1$1.invoke(CommandList.kt:17) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.CommandBuilder$CommandExecutor.exec(CommandBuilder.kt:177) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:85) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.CommandBuilder$CommandBase.execute(CommandBuilder.kt:97) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.CommandRegisterKt$command$1.execute(CommandRegister.kt:23) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitCommand$registerCommand$1.invoke$lambda-0(BukkitCommand.kt:58) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1618]
        ... 15 more

**Comment by Bkm016** [comment]
> [22:06:45 ERROR]: null

请上传语言文件

**Comment by 157946a** [comment]
[Uploading lang.zip…]()
已上传

**Comment by Score2** [comment]
@Bkm016

**Comment by 157946a** [comment]
> 嘿，如果takeitem可以指定CustomModelData，那就更好了。

Try to use the latest version, if there is an error, send it up
