### ISSUE TITLE
take-point动作报错

### ISSUE THREAD

**Issue by qianchen36** [InsinuateProjects/TrMenu#59]
[菜单配置](https://blog.qianchen.ink/index.php/a/21/)
使用了PlayerPoints、Vault
在捕获器中使用condition，condition中的'take-point: 2500'动作报错
但仅使用condition的情况下不报错

```
[17:04:52 ERROR]: Could not pass event AsyncPlayerChatEvent to TrMenu v3.0-PRE-20
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301]
        at me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:35) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:35) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:34) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:57) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-558]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-558]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-558]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:223) ~[patched_1.16.5.jar:git-Paper-558]
        at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:104) ~[patched_1.16.5.jar:git-Paper-558]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:62) ~[patched_1.16.5.jar:git-Paper-558]
        at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:2085) ~[patched_1.16.5.jar:git-Paper-558]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[patched_1.16.5.jar:git-Paper-558]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1938) ~[patched_1.16.5.jar:git-Paper-558]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:43) ~[patched_1.16.5.jar:git-Paper-558]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_301]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_301]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_301]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_301]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.IllegalStateException: PlayerPointsChangeEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:595) ~[patched_1.16.5.jar:git-Paper-558]
        at org.black_ixx.playerpoints.PlayerPointsAPI.give(PlayerPointsAPI.java:41) ~[?:?]
        at org.black_ixx.playerpoints.PlayerPointsAPI.take(PlayerPointsAPI.java:79) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.hook.impl.HookPlayerPoints.takePoints(HookPlayerPoints.kt:53) ~[?:?]
        at me.arasple.mc.trmenu.api.action.impl.hook.ActionPointsTake.onExecute(ActionPointsTake.kt:17) ~[?:?]
        at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1$1.invoke(AbstractAction.kt:41) ~[?:?]
        at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1$1.invoke(AbstractAction.kt:41) ~[?:?]
        at me.arasple.mc.trmenu.api.action.base.ActionOption.evalPlayers(ActionOption.kt:35) ~[?:?]
        at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1.invoke(AbstractAction.kt:41) ~[?:?]
        at me.arasple.mc.trmenu.api.action.base.AbstractAction$run$proceed$1.invoke(AbstractAction.kt:41) ~[?:?]
        at me.arasple.mc.trmenu.api.action.base.AbstractAction.run(AbstractAction.kt:43) ~[?:?]
        at me.arasple.mc.trmenu.api.action.Actions.runAction(Actions.kt:93) ~[?:?]
        at me.arasple.mc.trmenu.api.action.pack.Reactions$React.react(Reactions.kt:95) ~[?:?]
        at me.arasple.mc.trmenu.api.action.pack.Reactions.eval(Reactions.kt:70) ~[?:?]
        at me.arasple.mc.trmenu.api.action.pack.Reactions.eval(Reactions.kt:62) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.inputer.Inputer$run$1.invoke(Inputer.kt:63) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.inputer.Inputer$run$1.invoke(Inputer.kt:55) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.inputer.Inputer$Catcher$input$2$1.invoke(Inputer.kt:101) ~[?:?]
        at me.arasple.mc.trmenu.module.internal.inputer.Inputer$Catcher$input$2$1.invoke(Inputer.kt:100) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.platform.util.ChatListener.e(BukkitChat.kt:63) ~[?:?]
        ... 24 more
```

| Server OS: Windows11
| Server software: Paper 1.16.5
| Java version: jre11

| TabooLib: 6.x
| TrMenu: 3.0-PRE-20
Installed Plugins: 
· Adyeshach - 1.3.0
· LuckPerms - 5.1.93
· PlaceholderAPI - 2.10.9
· TrMenu - 3.0-PRE-20
```

**Comment by Neige7** [comment]
condition里不能加动作的啊

**Comment by qianchen36** [comment]
> condition里不能加动作的啊

你可以先看一下我贴出来的菜单配置

**Comment by Neige7** [comment]
> > condition里不能加动作的啊
> 
> 你可以先看一下我贴出来的菜单配置

不好意思刚开始没看到。确实报错了

**Comment by Score2** [comment]
尝试使用最新版，如遇到报错，请贴上最新的报错信息:)
