### ISSUE TITLE
TrMenu无法加载type节点

### ISSUE THREAD

**Issue by GoaTham** [InsinuateProjects/TrMenu#70]
【问题起因】
起因是因为我想用漏斗的GUI写一个菜单，于是找到了type节点，但在写上Type: HOPPER后，使用/trmenu reload发生了报错

【菜单配置】
```
Title:
  - 'test'
Title-Update: 40

Layout:
  - '`1``1``1``1``1`'

Type: HOPPER

Icons:
  'test':
    update: [-1, 10, 15, -1]
    display:
      material: '{"type":"STAINED_GLASS_PANE","data":15,"amount":1,"meta":{}}'
      name: ['test']
      shiny: true
    actions:
      all: 'sound: BLOCK_NOTE_BLOCK_PLING-1-2'
```
```
【报错内容】(ubuntupaste用不了了)
[23:24:29] [Server thread/ERROR] [net.minecraft.network.NetHandlerPlayServer]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'trmenu' in plugin TrMenu v3.0-PRE-24
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-CatServer-1.12.2-26208f0]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[SimpleCommandMap.class:git-CatServer-1.12.2-26208f0]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[CraftServer.class:git-CatServer-1.12.2-26208f0]
	at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:1600) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:1443) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_301]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_301]
	at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:833) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:474) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:770) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
Caused by: java.lang.NoSuchFieldError: BARREL
	at me.arasple.mc.trmenu.taboolib.module.ui.receptacle.ReceptacleAPIKt$WhenMappings.<clinit>(ReceptacleAPI.kt) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.module.ui.receptacle.ReceptacleAPIKt.createReceptacle(ReceptacleAPI.kt:40) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.module.ui.receptacle.ReceptacleAPIKt.createReceptacle$default(ReceptacleAPI.kt:38) ~[?:?]
	at me.arasple.mc.trmenu.module.display.layout.Layout.baseReceptacle(Layout.kt:61) ~[?:?]
	at me.arasple.mc.trmenu.module.display.layout.Layout.<init>(Layout.kt:34) ~[?:?]
	at me.arasple.mc.trmenu.module.conf.MenuSerializer.serializeLayout(MenuSerializer.kt:150) ~[?:?]
	at me.arasple.mc.trmenu.module.conf.MenuSerializer.serializeMenu(MenuSerializer.kt:61) ~[?:?]
	at me.arasple.mc.trmenu.module.conf.Loader$loadMenus$2$func$1.invoke(Loader.kt:55) ~[?:?]
	at me.arasple.mc.trmenu.module.conf.Loader$loadMenus$2$func$1.invoke(Loader.kt:53) ~[?:?]
	at me.arasple.mc.trmenu.module.conf.Loader.loadMenus(Loader.kt:64) ~[?:?]
	at me.arasple.mc.trmenu.module.internal.command.impl.CommandReload$command$1$1.invoke(CommandReload.kt:16) ~[?:?]
	at me.arasple.mc.trmenu.module.internal.command.impl.CommandReload$command$1$1.invoke(CommandReload.kt:15) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandExecutor.exec(CommandBuilder.kt:179) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandBase.execute$process(CommandBuilder.kt:86) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandBuilder$CommandBase.execute(CommandBuilder.kt:98) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.common.platform.command.CommandRegisterKt$command$1.execute(CommandRegister.kt:22) ~[?:?]
	at me.arasple.mc.trmenu.taboolib.platform.BukkitCommand$registerCommand$1.invoke$lambda-0(BukkitCommand.kt:66) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-CatServer-1.12.2-26208f0]
	... 15 more
```

【DEBUG dump】
https://paste.helpch.at/puraguqoge

ServerCore: Catserver
| TabooLib: 6.x
| TrMenu: 3.0-PRE-24

**Comment by Neige7** [comment]
您好
首先您应该将'1``1``1``1``1'更改为'`1``1``1``1``1`'
其次您并没有写ID为“1”的Icon，因此您应该将
Icons:
  'test':
改为
Icons:
  '1':

**Comment by Neige7** [comment]
你应该考虑将菜单内容粘贴至txt中
并上传上来。
你这种直接粘贴的方式会导致吞掉很多东西
阻碍问题的判断

**Comment by Galaxy-VN** [comment]
这是一个很长的问题，但我总是忘记报告它，它出现在第一个 v3 版本中 :)

**Comment by Score2** [comment]
尝试使用最新的构建来验证该问题是否被修复:)
如果有更多与自定义容器样式的bug也欢迎继续反馈
