### ISSUE TITLE
[问题]: Could not pass event PlayerInteractEvent to TrMenu v3.0-RC-2

### ISSUE THREAD

**Issue by 1636578433** [InsinuateProjects/TrMenu#85]
### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [ ] 我已翻阅现有的所有 issue, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: 2021-10-09 01:16:27)

| Server OS: Linux amd64 4.15.0-51-generic
| Server software: loliserver 1.16.5-109 (MC: 1.16.5) (1.16.5-R0.1-SNAPSHOT)
| Java version: 11

| TabooLib: 6.0.0-PRE
| TrMenu: 3.0-RC-2
Installed Plugins: 
· AdvancedNMotd - 9.2.0 (0 KB)
· BanItem - 3.2 (0 KB)
· BetterMessages - 2.2.8 (0 KB)
· CMI - 9.0.4.6 (0 KB)
· CMILib - 1.0.3.11 (0 KB)
· Chunky - 1.2.86 (0 KB)
· Citizens - 2.0.28-SNAPSHOT (build 2385) (0 KB)
· ClearEntity - 2.0 (0 KB)
· CrazyAuctionsPlus - 1.1.9 (0 KB)
· CrazyCrates - 1.10.1-Build#107 (0 KB)
· Dantiao - EX-24 (0 KB)
· DiscordSRV - 1.24.1-SNAPSHOT (0 KB)
· HolographicDisplays - 2.4.9 (0 KB)
· JakesRTP - 0.13.12 (0 KB)
· LevelledMobs - 3.1.8 b517 (0 KB)
· LuckPerms - 5.3.47 (0 KB)
· MoneyFromMobs - 4.3 (0 KB)
· Multiverse-Core - 4.3.1-b861 (0 KB)
· PlaceholderAPI - 2.10.10 (0 KB)
· PlayerTitle - 2.8.3 (0 KB)
· QuickShop - 4.0.9.10 (0 KB)
· Residence - 5.0.0.3 (0 KB)
· TrChat - 1.90-R2 (0 KB)
· TrMenu - 3.0-RC-2 (0 KB)
· Vault - 1.7.3-b${env.TRAVIS_BUILD_NUMBER} (0 KB)
· WorldEdit - 7.2.6+4b2d1e7 (0 KB)
```

### 🔍 详细的描述

1.開啟服務器
2.一直報錯

### 🗄 服务端日志

```
[ERROR] ....[Server thread] Could not pass event PlayerInteractEvent to TrMenu v3.0-RC-2

java.lang.reflect.InvocationTargetException: null

at jdk.internal.reflect.GeneratedMethodAccessor256.invoke(Unknown Source) ~[?:?]

at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]

at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]

at me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:35) ~[?:?]

at me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus$inject$2.invoke(EventBus.kt:35) ~[?:?]

at me.arasple.mc.trmenu.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]

at me.arasple.mc.trmenu.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[?:?]

at me.arasple.mc.trmenu.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[?:?]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[?:?]

at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:38) ~[?:?]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[?:?]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:574) ~[?:?]

at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:431) ~[?:?]

at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:398) ~[?:?]

at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:394) ~[?:?]

at net.minecraft.network.play.ServerPlayNetHandler.func_175087_a(ServerPlayNetHandler.java:1846) ~[?:?]

at net.minecraft.network.play.client.CAnimateHandPacket.func_148833_a(SourceFile:31) ~[?:?]

at net.minecraft.network.play.client.CAnimateHandPacket.func_148833_a(SourceFile:9) ~[?:?]

at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22) ~[?:?]

at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]

at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:136) ~[?:?]

at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]

at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:868) ~[?:?]

at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:178) ~[?:?]

at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:109) ~[?:?]

at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:851) ~[?:?]

at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:845) ~[?:?]

at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:97) ~[?:?]

at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:830) ~[?:?]

at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:763) ~[?:?]

at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:271) ~[?:?]

at java.lang.Thread.run(Unknown Source) [?:?]

Caused by: java.lang.NullPointerException

at me.arasple.mc.trmenu.module.internal.listener.ListenerItemInteract.onInteract(ListenerItemInteract.kt:36) ~[?:?]

... 32 more
```

### ⚙ 配置文件

```
Loader:
  Menu-Files:
    - 'plugins/CustomMenusFolder'

Menu:
  Settings:
    Bound-Item-Interval: 2000
  Icon:
    Inherit: false
    Item:
      Default-Name-Color: "&7"
      Default-Lore-Color: "&7"
      Pre-Color: false

Action:
  Inputer:
    Cancel-Words:
      - 'cancel|quit|end'
      - 'q'

Shortcuts:
  Offhand: 'open: Example'
  Sneaking-Offhand:
    - condition: []
      execute: []
      deny: []
  Right-Click-Player: []
  Sneaking-Right-Click-Player: []
  PlayerInventory-Border-Left: []
  PlayerInventory-Border-Right: []
  PlayerInventory-Border-Middle: []

RegisterCommands:
  openMenus:
    aliases: [ ]
    permission: null
    execute:
      - 'tell: &7Argument `example` Required!'
    arguments:
      example: 'open: example'

Options:
  # High, Normal, Low
  Running-Performance: Normal
  Multi-Thread: true
  Async-Load-Menus: true
Database:
  # LOCAL, MONGODB
  Method: LOCAL
  Url:
    Client: 'mongodb://localhost:3307'
    Database: trixey
    Collection: menu

# ------------------------------------------------ #
# VERSION f1da3c0e49ca3d8d1c288b8636e1e83243d6796c #
# ------------------------------------------------ #
```

**Comment by Score2** [comment]
请提供详细复现步骤，该报错是因为菜单绑定物品发生
